### PR TITLE
fix: add support for nested maven properties

### LINKED ISSUE #13236: Dependabot fails -> /maven/update_checker/property_updater -> Passed nil into T.must
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

maven

### Package manager version

default

### Language version

default

### Manifest location and content before the Dependabot update

_No response_

### dependabot.yml content

```yaml
version: 2

registries:
  maven-mycompany:
    type: maven-repository
    url: https://repo.mycompany.com/repository/maven
    username: user
    password: ${{secrets.PASSWORD}}


updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries:
      - maven-mycompany
    schedule:
      interval: "weekly"
```

### Updated dependency

private dependency

### What you expected to see, versus what you actually saw

The dependabot job success, updating all needed dependencies

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

```
2025-10-06T12:53:41.8132896Z updater | 2025/10/06 12:53:41 INFO <job_1118360197> Checking if com.mycompany.mygroup:myartifact-0.3_2.12 1.0.0-abc123 needs updating
2025-10-06T12:53:41.9096570Z   proxy | 2025/10/06 12:53:41 [604] GET https://repo.mycompany.com/repository/maven/com/mycompany/parent/1.0.0/parent-1.0.0.pom
2025-10-06T12:53:41.9099620Z 2025/10/06 12:53:41 [604] 200 https://repo.mycompany.com/repository/maven/com/mycompany/parent/1.0.0/parent-1.0.0.pom (cached)
2025-10-06T12:53:42.0091735Z   proxy | 2025/10/06 12:53:42 [606] GET https://repo.mycompany.com/repository/maven/com/mycompany/mygroup/myartifact-0.3_2.12/maven-metadata.xml
2025-10-06T12:53:42.0092870Z 2025/10/06 12:53:42 [606] * authenticating maven repository request (host: repo.mycompany.com)
2025-10-06T12:53:42.8456939Z   proxy | 2025/10/06 12:53:42 [606] 200 https://repo.mycompany.com/repository/maven/com/mycompany/mygroup/myartifact-0.3_2.12/maven-metadata.xml
2025-10-06T12:53:42.9941993Z   proxy | 2025/10/06 12:53:42 [610] GET https://repo.mycompany.com/repository/maven/com/mycompany/mygroup/myartifact-0.3_2.12
2025-10-06T12:53:42.9943208Z   proxy | 2025/10/06 12:53:42 [610] * authenticating maven repository request (host: repo.mycompany.com)
2025-10-06T12:53:43.2087551Z   proxy | 2025/10/06 12:53:43 [610] 404 https://repo.mycompany.com/repository/maven/com/mycompany/mygroup/myartifact-0.3_2.12
2025-10-06T12:53:43.3292583Z   proxy | 2025/10/06 12:53:43 [612] GET https://repo.maven.apache.org/maven2/com/mycompany/mygroup/myartifact-0.3_2.12
2025-10-06T12:53:43.6815232Z   proxy | 2025/10/06 12:53:43 [612] 404 https://repo.maven.apache.org/maven2/com/mycompany/mygroup/myartifact-0.3_2.12
2025-10-06T12:53:43.7082540Z updater | 2025/10/06 12:53:43 INFO <job_1118360197> Filtered out 13 pre-release versions
2025-10-06T12:53:43.8111700Z   proxy | 2025/10/06 12:53:43 [614] HEAD https://repo.mycompany.com/repository/maven/com/mycompany/mygroup/myartifact-0.3_2.12/1.2.3-abc123/myartifact-0.3_2.12-1.2.3-abc123.jar
2025-10-06T12:53:43.8113519Z 2025/10/06 12:53:43 [614] * authenticating maven repository request (host: repo.mycompany.com)
2025-10-06T12:53:45.9408787Z   proxy | 2025/10/06 12:53:45 [614] 200 https://repo.mycompany.com/repository/maven/com/mycompany/mygroup/myartifact-0.3_2.12/1.2.3-abc123/myartifact-0.3_2.12-1.2.3-abc123.jar
2025-10-06T12:53:45.9501326Z updater | 2025/10/06 12:53:45 INFO <job_1118360197> Latest version is 
2025-10-06T12:53:45.9513928Z updater | 2025/10/06 12:53:45 INFO <job_1118360197> Filtered out 13 pre-release versions
2025-10-06T12:53:45.9554015Z updater | 2025/10/06 12:53:45 INFO <job_1118360197> Filtered out 13 pre-release versions
2025-10-06T12:53:45.9595767Z updater | 2025/10/06 12:53:45 INFO <job_1118360197> Filtered out 13 pre-release versions
2025-10-06T12:53:45.9632598Z updater | 2025/10/06 12:53:45 INFO <job_1118360197> Filtered out 13 pre-release versions
2025-10-06T12:53:45.9693245Z updater | 2025/10/06 12:53:45 INFO <job_1118360197> Filtered out 13 pre-release versions
2025-10-06T12:53:45.9730125Z updater | 2025/10/06 12:53:45 INFO <job_1118360197> Filtered out 13 pre-release versions
2025-10-06T12:53:45.9767624Z updater | 2025/10/06 12:53:45 INFO <job_1118360197> Filtered out 13 pre-release versions
2025-10-06T12:53:46.1106310Z updater | 2025/10/06 12:53:46 INFO <job_1118360197> Filtered out 13 pre-release versions
2025-10-06T12:53:46.1150637Z updater | 2025/10/06 12:53:46 INFO <job_1118360197> Filtered out 13 pre-release versions
2025-10-06T12:53:46.1197145Z updater | 2025/10/06 12:53:46 INFO <job_1118360197> Filtered out 13 pre-release versions
2025-10-06T12:53:46.1246699Z updater | 2025/10/06 12:53:46 INFO <job_1118360197> Filtered out 13 pre-release versions
2025-10-06T12:53:46.2785122Z   proxy | 2025/10/06 12:53:46 [616] POST /update_jobs/1118360197/record_update_job_unknown_error
2025-10-06T12:53:46.4611880Z   proxy | 2025/10/06 12:53:46 [616] 204 /update_jobs/1118360197/record_update_job_unknown_error
2025-10-06T12:53:46.5071637Z   proxy | 2025/10/06 12:53:46 [618] POST /update_jobs/1118360197/record_update_job_error
2025-10-06T12:53:46.6357008Z   proxy | 2025/10/06 12:53:46 [618] 204 /update_jobs/1118360197/record_update_job_error
2025-10-06T12:53:46.6821405Z   proxy | 2025/10/06 12:53:46 [620] POST /update_jobs/1118360197/increment_metric
2025-10-06T12:53:46.7950414Z   proxy | 2025/10/06 12:53:46 [620] 204 /update_jobs/1118360197/increment_metric
2025-10-06T12:53:46.8014481Z   proxy | 2025/10/06 12:53:46 [622] POST /update_jobs/1118360197/record_update_job_unknown_error
2025-10-06T12:53:46.9698484Z   proxy | 2025/10/06 12:53:46 [622] 204 /update_jobs/1118360197/record_update_job_unknown_error
2025-10-06T12:53:46.9707720Z updater | 2025/10/06 12:53:46 ERROR <job_1118360197> Error processing com.mycompany.mygroup:myartifact-0.3_2.12 (TypeError)
2025-10-06T12:53:46.9719809Z updater | 2025/10/06 12:53:46 ERROR <job_1118360197> Passed `nil` into T.must
2025-10-06T12:53:46.9720977Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/_types.rb:222:in 'T.must'
2025-10-06T12:53:46.9742984Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/maven/lib/dependabot/maven/update_checker/property_updater.rb:180:in 'Dependabot::Maven::UpdateChecker::PropertyUpdater#updated_version'
2025-10-06T12:53:46.9745268Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation_2_7.rb:108:in 'UnboundMethod#bind_call'
2025-10-06T12:53:46.9747783Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation_2_7.rb:108:in 'block in Dependabot::Maven::UpdateChecker::PropertyUpdater#create_validator_method_fast1'
2025-10-06T12:53:46.9750528Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/maven/lib/dependabot/maven/update_checker/property_updater.rb:53:in 'block in Dependabot::Maven::UpdateChecker::PropertyUpdater#update_possible?'
2025-10-06T12:53:46.9752401Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/maven/lib/dependabot/maven/update_checker/property_updater.rb:52:in 'Array#all?'
2025-10-06T12:53:46.9754436Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/maven/lib/dependabot/maven/update_checker/property_updater.rb:52:in 'Dependabot::Maven::UpdateChecker::PropertyUpdater#update_possible?'
2025-10-06T12:53:46.9757033Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation_2_7.rb:919:in 'UnboundMethod#bind_call'
2025-10-06T12:53:46.9759802Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation_2_7.rb:919:in 'block in Dependabot::Maven::UpdateChecker::PropertyUpdater#create_validator_method_medium0'
2025-10-06T12:53:46.9762431Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/maven/lib/dependabot/maven/update_checker.rb:129:in 'Dependabot::Maven::UpdateChecker#latest_version_resolvable_with_full_unlock?'
2025-10-06T12:53:46.9764885Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation_2_7.rb:919:in 'UnboundMethod#bind_call'
2025-10-06T12:53:46.9767576Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation_2_7.rb:919:in 'block in Dependabot::Maven::UpdateChecker#create_validator_method_medium0'
2025-10-06T12:53:46.9770032Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:352:in 'Dependabot::UpdateCheckers::Base#numeric_version_can_update?'
2025-10-06T12:53:46.9772185Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:179:in 'UnboundMethod#bind_call'
2025-10-06T12:53:46.9774871Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:179:in 'T::Private::Methods::CallValidation.validate_call_skip_block_type'
2025-10-06T12:53:46.9777413Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:121:in 'block in Dependabot::UpdateCheckers::Base#create_validator_slow_skip_block_type'
2025-10-06T12:53:46.9779528Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/maven/lib/dependabot/maven/update_checker.rb:148:in 'Dependabot::Maven::UpdateChecker#numeric_version_can_update?'
2025-10-06T12:53:46.9781689Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:179:in 'UnboundMethod#bind_call'
2025-10-06T12:53:46.9783972Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:179:in 'T::Private::Methods::CallValidation.validate_call_skip_block_type'
2025-10-06T12:53:46.9786763Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:121:in 'block in Dependabot::Maven::UpdateChecker#create_validator_slow_skip_block_type'
2025-10-06T12:53:46.9788933Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:293:in 'Dependabot::UpdateCheckers::Base#version_can_update?'
2025-10-06T12:53:46.9790792Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:179:in 'UnboundMethod#bind_call'
2025-10-06T12:53:46.9793281Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:179:in 'T::Private::Methods::CallValidation.validate_call_skip_block_type'
2025-10-06T12:53:46.9796407Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:121:in 'block in Dependabot::UpdateCheckers::Base#create_validator_slow_skip_block_type'
2025-10-06T12:53:46.9798548Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:109:in 'Dependabot::UpdateCheckers::Base#can_update?'
2025-10-06T12:53:46.9800373Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:179:in 'UnboundMethod#bind_call'
2025-10-06T12:53:46.9802788Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:179:in 'T::Private::Methods::CallValidation.validate_call_skip_block_type'
2025-10-06T12:53:46.9804900Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:121:in 'block in Dependabot::UpdateCheckers::Base#create_validator_slow_skip_block_type'
2025-10-06T12:53:46.9806423Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:303:in 'Dependabot::Updater::Operations::UpdateAllVersions#requirements_to_unlock'
2025-10-06T12:53:46.9807775Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation_2_7.rb:108:in 'UnboundMethod#bind_call'
2025-10-06T12:53:46.9809256Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation_2_7.rb:108:in 'block in Dependabot::Updater::Operations::UpdateAllVersions#create_validator_method_fast1'
2025-10-06T12:53:46.9810794Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:138:in 'Dependabot::Updater::Operations::UpdateAllVersions#check_and_create_pull_request'
2025-10-06T12:53:46.9812118Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation_2_7.rb:687:in 'UnboundMethod#bind_call'
2025-10-06T12:53:46.9813766Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation_2_7.rb:687:in 'block in Dependabot::Updater::Operations::UpdateAllVersions#create_validator_procedure_fast1'
2025-10-06T12:53:46.9815628Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:99:in 'Dependabot::Updater::Operations::UpdateAllVersions#check_and_create_pr_with_error_handling'
2025-10-06T12:53:46.9816999Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation_2_7.rb:687:in 'UnboundMethod#bind_call'
2025-10-06T12:53:46.9818471Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation_2_7.rb:687:in 'block in Dependabot::Updater::Operations::UpdateAllVersions#create_validator_procedure_fast1'
2025-10-06T12:53:46.9819982Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:59:in 'block in Dependabot::Updater::Operations::UpdateAllVersions#perform'
2025-10-06T12:53:46.9821133Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:59:in 'Array#each'
2025-10-06T12:53:46.9822356Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:59:in 'Dependabot::Updater::Operations::UpdateAllVersions#perform'
2025-10-06T12:53:46.9823596Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:282:in 'UnboundMethod#bind_call'
2025-10-06T12:53:46.9825029Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:282:in 'T::Private::Methods::CallValidation.validate_call'
2025-10-06T12:53:46.9826489Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/_methods.rb:277:in 'block in Dependabot::Updater::Operations::UpdateAllVersions#_on_method_added'
2025-10-06T12:53:46.9828021Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:138:in 'block in Dependabot::Updater::Operations::GroupUpdateAllVersions#run_ungrouped_dependency_updates'
2025-10-06T12:53:46.9829277Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:123:in 'Array#each'
2025-10-06T12:53:46.9830526Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:123:in 'Dependabot::Updater::Operations::GroupUpdateAllVersions#run_ungrouped_dependency_updates'
2025-10-06T12:53:46.9831946Z updater | 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:282:in 'UnboundMethod#bind_call'
2025-10-06T12:53:46.9833336Z updater | 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:282:in 'T::Private::Methods::CallValidation.validate_call'
2025-10-06T12:53:46.9834928Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/_methods.rb:277:in 'block in Dependabot::Updater::Operations::GroupUpdateAllVersions#_on_method_added'
2025-10-06T12:53:46.9836482Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:66:in 'Dependabot::Updater::Operations::GroupUpdateAllVersions#perform'
2025-10-06T12:53:46.9837753Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:282:in 'UnboundMethod#bind_call'
2025-10-06T12:53:46.9839085Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:282:in 'T::Private::Methods::CallValidation.validate_call'
2025-10-06T12:53:46.9840585Z updater | 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/_methods.rb:277:in 'block in Dependabot::Updater::Operations::GroupUpdateAllVersions#_on_method_added'
2025-10-06T12:53:46.9841795Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in 'Dependabot::Updater#run'
2025-10-06T12:53:46.9842823Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:282:in 'UnboundMethod#bind_call'
2025-10-06T12:53:46.9844416Z updater | 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:282:in 'T::Private::Methods::CallValidation.validate_call'
2025-10-06T12:53:46.9845836Z updater | 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/_methods.rb:277:in 'block in Dependabot::Updater#_on_method_added'
2025-10-06T12:53:46.9847081Z updater | 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:51:in 'block in Dependabot::UpdateFilesCommand#perform_job'
2025-10-06T12:53:46.9848276Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/opentelemetry-api-1.5.0/lib/opentelemetry/trace/tracer.rb:37:in 'block in OpenTelemetry::Trace::Tracer#in_span'
2025-10-06T12:53:46.9849525Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/opentelemetry-api-1.5.0/lib/opentelemetry/trace.rb:70:in 'block in OpenTelemetry::Trace#with_span'
2025-10-06T12:53:46.9850733Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/opentelemetry-api-1.5.0/lib/opentelemetry/context.rb:88:in 'OpenTelemetry::Context.with_value'
2025-10-06T12:53:46.9851934Z updater | 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/opentelemetry-api-1.5.0/lib/opentelemetry/trace.rb:70:in 'OpenTelemetry::Trace#with_span'
2025-10-06T12:53:46.9853165Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/opentelemetry-api-1.5.0/lib/opentelemetry/trace/tracer.rb:37:in 'OpenTelemetry::Trace::Tracer#in_span'
2025-10-06T12:53:46.9854402Z updater | 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:24:in 'Dependabot::UpdateFilesCommand#perform_job'
2025-10-06T12:53:46.9855552Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:282:in 'UnboundMethod#bind_call'
2025-10-06T12:53:46.9856867Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:282:in 'T::Private::Methods::CallValidation.validate_call'
2025-10-06T12:53:46.9858378Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/_methods.rb:277:in 'block in Dependabot::UpdateFilesCommand#_on_method_added'
2025-10-06T12:53:46.9859512Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:42:in 'Dependabot::BaseCommand#run'
2025-10-06T12:53:46.9860569Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:282:in 'UnboundMethod#bind_call'
2025-10-06T12:53:46.9861897Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/call_validation.rb:282:in 'T::Private::Methods::CallValidation.validate_call'
2025-10-06T12:53:46.9863268Z 2025/10/06 12:53:46 ERROR <job_1118360197> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.6.12544/lib/types/private/methods/_methods.rb:277:in 'block in Dependabot::BaseCommand#_on_method_added'
```

### Smallest manifest that reproduces the issue

_No response_

### LINKED ISSUE #13713: Complex yet valid maven project fails with `dependency_file_not_evaluatable {message: "ERROR: Invalid expression: /project/groupId}.channel"}`
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

maven

### Package manager version

_No response_

### Language version

java

### Manifest location and content before the Dependabot update

https://github.com/wildfly/wildfly/blob/main/pom.xml

### dependabot.yml content

Nothing special here.

```yml
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2/
  jboss-public-repository-group:
    type: maven-repository
    url: https://repository.jboss.org/nexus/content/groups/public/
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
       # Only allow for patch release upgrades
      - dependency-name: '*'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      # WildFly Clustering updates are usually non-trivial
      - dependency-name: 'org.wildfly.clustering:*'
      # Dependencies exclusive to Hibernate Search:
      # we'll only upgrade those when we upgrade to a newer version of Hibernate Search.
      - dependency-name: 'org.elasticsearch.client:*'
      - dependency-name: 'org.apache.lucene:*'
      - dependency-name: 'com.carrotsearch:hppc'
      - dependency-name: 'org.apache.avro:avro'
    rebase-strategy: "disabled"
    open-pull-requests-limit: 10
    registries:
      - maven-central
      - jboss-public-repository-group
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
```

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

What we are seeing: https://gist.github.com/bstansberry/5bbd2b64ac324421628c08958c4210b8

```
dependency_file_not_evaluatable {message: "ERROR: Invalid expression: /project/groupId}.channel"}
```

And why it's clear that it's a dependabot issue: there is no such property "channel" anywhere in the pom, only "channels". Something is being parsed incorrectly by dependabot.

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

https://gist.github.com/bstansberry/5bbd2b64ac324421628c08958c4210b8

### Smallest manifest that reproduces the issue

Impossible to isolate into a small reproducer.

### LINKED ISSUE #13988: Maven parser incorrectly interprets ${project.artifactId} as /project/artifactId}
## Description

Since approximately January 14, 2026, Dependabot's Maven parser has been incorrectly parsing Maven property expressions in `pom.xml` files. Specifically, the expression `${project.artifactId}` is being interpreted as `/project/artifactId}`.

## Error Message

```
ERROR: Invalid expression: /project/artifactId}-entrypoin
```

The parser appears to be converting:
- `${` → `/`
- The closing `}` remains

## Affected Code

The error occurs with property definitions like:

```xml
<properties>
  <webapp.entrypoint.artifactId>${project.artifactId}-entrypoint</webapp.entrypoint.artifactId>
</properties>
```

## Impact

- Dependabot version updates fail with `dependency_file_not_evaluatable` error
- Maven builds continue to work correctly (this is a Dependabot parser issue only)
- Affects repositories using Maven properties with `${project.*}` expressions

## Reproduction

1. Create a `pom.xml` with:
```xml
<properties>
  <my.property>${project.artifactId}-suffix</my.property>
</properties>
```

2. Run Dependabot Maven version updates
3. Observe the parsing error in Dependabot logs

## Workaround

Exclude affected directories using `exclude-paths` in `.github/dependabot.yml`:

```yaml
- package-ecosystem: "maven"
  directory: "/"
  exclude-paths:
    - "affected-directory/**"
```

## Environment

- First observed: January 14, 2026, ~06:00 UTC
- Ecosystem: Maven
- Package manager: maven

## Expected Behavior

`${project.artifactId}` should be recognized as a valid Maven property expression and parsed correctly.

## Additional Context

This appears to be a regression introduced around January 14, 2026. The same `pom.xml` files worked correctly before this date.

### PR DESCRIPTION
**Pull request by yeikel**
### What are you trying to accomplish?

Updates our maven parsing logic to allow parsing from more complex builds such as the ones that use nested properties

Fixes #13713
Fixes #13988
Fixes #13236

### How will you know you've accomplished your goal?

Using the image from main, this is the output we can expect as documented in #13713

Reproducer: https://github.com/yeikel/dependabot-issue-13713

> dependabot update -f job.json
> ... some logs omited for brevity 
> updater | +----------------------------------------------------------------------------------------------+
> updater | |                                            Errors                                            |
> updater | +---------------------------------+------------------------------------------------------------+
> updater | | Type                            | Details                                                    |
> updater | +---------------------------------+------------------------------------------------------------+
> updater | | dependency_file_not_evaluatable | {                                                          |
> updater | |                                 |   "message": "ERROR: Invalid expression: /project/.${grpc" |
> updater | |                                 | }                                                          |
> updater | +---------------------------------+------------------------------------------------------------+

After this change: 

>  proxy | 2025/12/10 00:44:05 [049] 200 http://host.docker.internal:58225/update_jobs/cli/create_pull_request
> {"data":{"base-commit-sha":"2743e98a2a25267ae9bfdab9a4c756625c50e439"},"type":"mark_as_processed"}
>   proxy | 2025/12/10 00:44:05 [050] PATCH http://host.docker.internal:58225/update_jobs/cli/mark_as_processed
>   proxy | 2025/12/10 00:44:05 [050] 200 http://host.docker.internal:58225/update_jobs/cli/mark_as_processed
> updater | 2025/12/10 00:44:05 INFO Finished job processing
> updater | 2025/12/10 00:44:05 INFO Results:
> updater | +--------------------------------------------------------+
> updater | |          Changes to Dependabot Pull Requests           |
> updater | +---------+----------------------------------------------+
> updater | | created | io.grpc:grpc-netty ( from 1.76.2 to 1.77.0 ) |
> updater | +---------+----------------------------------------------+
>   proxy | 2025/12/10 00:44:06 Skipping sending metrics because api endpoint is empty
>   proxy | 2025/12/10 00:44:06 5/23 calls cached (21%)

### Checklist

- [x] I have run the complete test suite to ensure all tests and linters pass.
- [x] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [x] I have written clear and descriptive commit messages.
- [x] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [x] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

**Comment by rhusar** [comment]
@yeikel Is there anything we can do help this move through?

Unfortunately the [workaround to hard code the property I was hoping to implement](https://github.com/dependabot/dependabot-core/issues/13713#issuecomment-3618717319) was not desirable.

**Comment by yeikel** [comment]
> @yeikel Is there anything we can do help this move through?
> 
> Unfortunately the [workaround to hard code the property I was hoping to implement](https://github.com/dependabot/dependabot-core/issues/13713#issuecomment-3618717319) was not desirable.

@rhusar Based on my understanding, @kbukum1 is currently testing this change in a controlled production release and through other methods. Since I’m not part of the Dependabot team, I’m unable to assist in progressing this further so let’s wait for their feedback. 

Once the change is merged and released, it would be helpful if you could confirm whether it resolves the issue for you.

**Comment by yeikel** [comment]
@kbukum1 Please note that I updated the body because this change also fixes #13236 as well as one more scenario that @rhusar [pointed out](https://github.com/dependabot/dependabot-core/issues/13236#issuecomment-3836029779)

**Comment by v-kbukum1** [comment]
> @kbukum1 Please note that I updated the body because this change also fixes #13236 as well as one more scenario that @rhusar [pointed out](https://github.com/dependabot/dependabot-core/issues/13236#issuecomment-3836029779)

Thanks @yeikel, I will try to find sometime this week or maybe next week to review it. It seems to be fixing a few issues. So I need sometime to review it.

File: maven/lib/dependabot/maven/file_parser/property_value_finder.rb [hunk 1]
```diff
@@ -63,53 +69,66 @@ def property_details(property_name:, callsite_pom:)
...
+          ).returns(T.nilable(T::Hash[Symbol, T.untyped]))
         end
-        def extract_value_from_expression(expression:, property_name:, callsite_pom:)
-          # and the expression is pointing to self then raise the error
-          if expression.eql?("${#{property_name}}")
-            raise Dependabot::DependencyFileNotParseable.new(
-              callsite_pom.name,
-              "Error trying to resolve recursive expression '#{expression}'."
+        def resolve_property_placeholder(content, callsite_pom, pom, node, seen_properties)
+          resolved_value = content.gsub(/\$\{(.+?)}/) do
```
Comment (JamieMagee) [inline maven/lib/dependabot/maven/file_parser/property_value_finder.rb:123]: Your docstring says it supports complex properties like `${my.property.${other.property}}`, but I think the non-greedy matching here prevents this.

Could you add a test case for that, if it is expected to match, or update the docstring if not.

EDIT: I don't think greedy would work either ☹️

File: maven/spec/dependabot/maven/file_parser/property_value_finder_spec.rb
Comment (JamieMagee) [inline maven/spec/dependabot/maven/file_parser/property_value_finder_spec.rb:1]: Could you add a test case where the property isn't resolved? That would help to clarify failure behaviour.

File: maven/lib/dependabot/maven/file_parser/property_value_finder.rb (hunk 1 above)
Comment (yeikel) [reply maven/lib/dependabot/maven/file_parser/property_value_finder.rb:123]: > Your docstring says it supports complex properties like ${my.property.${other.property}}, but I think the non-greedy matching here prevents this.

The existing test pom has the following property that is resolved as expected.

```
    <channels.maven.groupId.nested>${project.groupId}.${channels}</channels.maven.groupId.nested>
``` 

I tried to prove that in the spec `when the property is nested multiple times` 

https://github.com/yeikel/dependabot-core/blob/7baa71a17f88852dc610de037b9a2c135121fc71/maven/spec/dependabot/maven/file_parser/property_value_finder_spec.rb#L49-L54

Is that what you'd like to see or what do you mean? 

ps: Thanks for the question/feedback and for generally helping me move my changes forward 🤟

Comment (JamieMagee) [reply maven/lib/dependabot/maven/file_parser/property_value_finder.rb:123]: I think the format `${a}.${b}` is covered, but the nested/recursive style `${a.${b}}` isn't. I'm not familiar enough with maven to know if that's even supported, but just going by your docstring, your regex doesn't match that pattern.

And not a problem! Thank you for your contributions. I don't always have as much time as I'd like to review and merge open source contributions, but your changes are always high quality and well documented. You make it easy!

File: maven/spec/dependabot/maven/file_parser/property_value_finder_spec.rb
Comment (yeikel) [reply maven/spec/dependabot/maven/file_parser/property_value_finder_spec.rb:1]: This is already covered by a few of the existing existing tests and the expected behavior is to return `nil` (skip the dependency)

I’m not sure why it was designed this way, and the reasoning isn’t clear from the code

That said, I made a [few assumptions and tried to document it](https://github.com/yeikel/dependabot-core/blob/5046f30647dc5e5a5de128a53299951242de18e4/maven/lib/dependabot/maven/file_parser/property_value_finder.rb#L79-L86). I also added an [additional test to explicitly cover this scenario ](https://github.com/yeikel/dependabot-core/blob/5046f30647dc5e5a5de128a53299951242de18e4/maven/spec/dependabot/maven/file_parser/property_value_finder_spec.rb#L93-L103)and the log addition

File: maven/lib/dependabot/maven/file_parser/property_value_finder.rb (hunk 1 above)
Comment (yeikel) [reply maven/lib/dependabot/maven/file_parser/property_value_finder.rb:123]: > I think the format `${a}.${b}` is covered, but the nested/recursive style `${a.${b}}` isn't. I'm not familiar enough with maven to know if that's even supported, but just going by your docstring, your regex doesn't match that pattern.

Ah, I see what you mean now. Based on what I tested, maven does not seem to support this syntax 

For reference, this is what I tested 

<details>
  <summary>Pom file</summary>
  
 
  ```xml
 <?xml version="1.0" encoding="UTF-8"?>
<project
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.wildfly</groupId>
	<artifactId>test</artifactId>
	<version>1.0-SNAPSHOT</version>
	<packaging>jar</packaging>
	<properties>
		<a>4.9</a>
		<b>5</b>
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.taptap.sdk</groupId>
			<artifactId>tap-review</artifactId>
			<version>${a.${b}}</version>
		</dependency>
	</dependencies>
</project>
  ```
  
</details>


<details>
  <summary>Maven logs</summary>
  
   ```
 [ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for com.taptap.sdk:tap-review:jar must be a valid version but is '${a.${b}}'. @ line 19, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.wildfly:test:1.0-SNAPSHOT (C:\Users\Yeikel\reproducer-issue-13236\pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for com.taptap.sdk:tap-review:jar must be a valid version but is '${a.${b}}'. @ line 19, column 13
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
  ```
  
</details>


> And not a problem! Thank you for your contributions. I don't always have as much time as I'd like to review and merge open source contributions, but your changes are always high quality and well documented. You make it easy!

Thank you for the kind words; I do my best to document well because the goal is `main` :)

Comment (rhusar) [reply maven/lib/dependabot/maven/file_parser/property_value_finder.rb:123]: @JamieMagee No, Maven does not natively support nested property interpolation like ${my.property.${other.property}}.

Quick tip: you can see what maven resolved expressions to by using `mvn help:effective-pom` on a pom. But such expression ^ wold fail at validate time, e.g. `[ERROR] Non-resolvable import POM: The following artifacts could not be resolved: groupId:bom:pom:${my.property.${other.property}} (absent)`

Comment (yeikel) [reply maven/lib/dependabot/maven/file_parser/property_value_finder.rb:123]: @JamieMagee Did I answer your questions or do you have any other feedback/suggestion about the code/docs?

**Comment by yeikel** [comment]
> > @kbukum1 Please note that I updated the body because this change also fixes #13236 as well as one more scenario that @rhusar [pointed out](https://github.com/dependabot/dependabot-core/issues/13236#issuecomment-3836029779)
> 
> Thanks @yeikel, I will try to find sometime this week or maybe next week to review it. It seems to be fixing a few issues. So I need sometime to review it.

@kbukum1 Could you please take a look and let me know if you have any additional question, feedback or any scenario I should cover? Thanks as always for your time

**Review by JamieMagee — APPROVED** [review]
