### PR TITLE
fix go1.21 not a toolchain

### LINKED ISSUE #7895: gomod: go1.21 toolchain not available
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gomod

### Package manager version

_No response_

### Language version

1.21

### Manifest location and content before the Dependabot update

_No response_

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Paris"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
      - dependency-type: "all"
    reviewers:
      - "pierrre"
```

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

My `go.mod` contains this + some dependencies:
```
module github.com/pierrre/go-libs

go 1.21
```

Yesterday, dependabot was updating my dependencies without any issue.

Today it's failing with this error message (I didn't change anything on my side):

```
Dependabot can't parse your go.mod
Dependabot failed to update your dependencies because there was an error parsing the go.mod found at /go.mod.

Dependabot encountered the following error:

go: downloading go1.21 (linux/amd64)
go: download go1.21 for linux/amd64: toolchain not available
```

and logs
```
 proxy | 2023/08/24 06:55:13 proxy starting, commit: 9833ecd82095ae7ce56480f9538522148bf46c95
  proxy | 2023/08/24 06:55:13 Listening (:1080)
updater | 2023-08-24T06:55:13.604365688 [713250698:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2023-08-24T06:55:15Z" level=info msg="guest starting" commit=b5ee63832e5412942127524d25c88400573f5df7
updater | time="2023-08-24T06:55:15Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=713250698 updater_timeout=45m0s updater_version=1cc46f801e61cf6988ef5e35fc16f54675a17c52-gomod
updater | 2023/08/24 06:55:16 INFO Raven 3.1.2 ready to catch errors
updater | 2023/08/24 06:55:17 INFO <job_713250698> Starting job processing
  proxy | 2023/08/24 06:55:17 [002] GET https://github.com:443/pierrre/go-libs/info/refs?service=git-upload-pack
  proxy | 2023/08/24 06:55:17 [002] * authenticating git server request (host: github.com)
  proxy | 2023/08/24 06:55:17 [002] 200 https://github.com:443/pierrre/go-libs/info/refs?service=git-upload-pack
  proxy | 2023/08/24 06:55:17 [004] POST https://github.com:443/pierrre/go-libs/git-upload-pack
  proxy | 2023/08/24 06:55:17 [004] * authenticating git server request (host: github.com)
  proxy | 2023/08/24 06:55:17 [004] 200 https://github.com:443/pierrre/go-libs/git-upload-pack
  proxy | 2023/08/24 06:55:17 [006] POST https://github.com:443/pierrre/go-libs/git-upload-pack
  proxy | 2023/08/24 06:55:17 [006] * authenticating git server request (host: github.com)
  proxy | 2023/08/24 06:55:18 [006] 200 https://github.com:443/pierrre/go-libs/git-upload-pack
updater | 2023/08/24 06:55:18 INFO <job_713250698> Finished job processing
updater | time="2023-08-24T06:55:18Z" level=info msg="task complete" container_id=job-713250698-file-fetcher exit_code=0 job_id=713250698 step=fetcher
updater | 2023/08/24 06:55:19 INFO Raven 3.1.2 ready to catch errors
updater | 2023/08/24 06:55:19 INFO <job_713250698> Starting job processing
  proxy | 2023/08/24 06:55:20 [010] GET https://proxy.golang.org:443/golang.org/toolchain/@v/v0.0.1-go1.21.linux-amd64.zip
  proxy | 2023/08/24 06:55:21 [010] 404 https://proxy.golang.org:443/golang.org/toolchain/@v/v0.0.1-go1.21.linux-amd64.zip
  proxy | 2023/08/24 06:55:21 [012] GET https://golang.org:443/toolchain?go-get=1
  proxy | 2023/08/24 06:55:21 [012] 200 https://golang.org:443/toolchain?go-get=1
  proxy | 2023/08/24 06:55:21 [014] GET https://go.dev:443/dl/mod/golang.org/toolchain/@v/v0.0.1-go1.21.linux-amd64.zip
  proxy | 2023/08/24 06:55:21 [014] 302 https://go.dev:443/dl/mod/golang.org/toolchain/@v/v0.0.1-go1.21.linux-amd64.zip
  proxy | 2023/08/24 06:55:22 [016] GET https://dl.google.com:443/go/v0.0.1-go1.21.linux-amd64.zip
  proxy | 2023/08/24 06:55:22 [016] 404 https://dl.google.com:443/go/v0.0.1-go1.21.linux-amd64.zip
updater | 2023/08/24 06:55:22 INFO <job_713250698> Finished job processing
updater | 2023/08/24 06:55:22 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +-------------------------------+
updater | |            Errors             |
updater | +-------------------------------+
updater | | dependency_file_not_parseable |
updater | +-------------------------------+
updater | time="2023-08-24T06:55:22Z" level=info msg="task complete" container_id=job-713250698-updater exit_code=0 job_id=713250698 step=updater
```

### Native package manager behavior

It's updating dependencies without any issues.

It doesn't attempt to download a toolchain.

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

```
module github.com/pierrre/go-libs

go 1.21
```

### LINKED ISSUE #8052: Downloading of Go toolchain breaks update checker
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

go_modules

### Package manager version

_No response_

### Language version

1.21

### Manifest location and content before the Dependabot update

_No response_

### dependabot.yml content

_No response_

### Updated dependency

ariga.io/atlas

### What you expected to see, versus what you actually saw

When Dependabot needs to download a toolchain for go, it looks like the output of the command
```
go list -m -versions -json <dependency_name>
```

is not actually fully valid JSON, because it prepends it with "go: downloading go1.20.8 (linux/amd64)".

The full error is:

```
859: unexpected token at 'go: downloading go1.20.8 (linux/amd64)
{
	"Path": "ariga.io/atlas",
	"Versions": [
		"v0.0.1",
		"v0.1.0",
		"v0.1.1",
		"v0.2.0",
		"v0.3.0",
		"v0.3.1",
		"v0.3.2",
		"v0.3.3",
		"v0.3.4",
		"v0.3.5",
		"v0.3.6",
		"v0.3.7",
		"v0.3.8",
		"v0.4.0",
		"v0.4.1",
		"v0.4.2",
		"v0.5.0",
		"v0.6.0",
		"v0.6.1",
		"v0.6.2",
		"v0.6.3",
		"v0.6.4",
		"v0.6.5",
		"v0.7.0",
		"v0.7.1",
		"v0.7.2",
		"v0.8.0",
		"v0.8.1",
		"v0.8.2",
		"v0.8.3",
		"v0.9.0",
		"v0.9.1",
		"v0.10.0",
		"v0.10.1",
		"v0.11.0",
		"v0.12.0",
		"v0.12.1",
		"v0.13.0",
		"v0.13.1",
		"v0.13.2",
		"v0.13.3",
		"v0.14.0"
	],
	"Origin": {
		"VCS": "git",
		"URL": "https://github.com/ariga/atlas",
		"TagSum": "t1:orGpJxYxp30ZST7GMppFGP6ejkki9pU2RClRkELdvk0="
	}
}
'
```

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

_No response_

### PR DESCRIPTION
**Pull request by jakecoffman**
Fixes #7895 - People are setting `go 1.21` in their go.mod without a `toolchain` directive and this breaks the auto downloading since `1.21` isn't a valid toolchain.

Also fixes #8052 - When downloading the toolchain for the first time the output is to stdout which interferes with capturing the output of the tool.

Additionally, some customers have aggressive firewalls set on their Actions runners, and so it's not a great idea to have the Go tooling automatically download versions of the Go toolchain.

This change still pre-downloads and uses Go 1.20 for older `go.mod` versions, but for later ones it uses the "local" version which should usually be the latest release.

### CODE REVIEW

**Comment by jakecoffman** [comment]
The environment variable plus parallel tests is not a great combo.

File: go_modules/lib/dependabot/go_modules/file_parser.rb [hunk 1]
```diff
@@ -24,6 +27,15 @@ def parse
 
       private
 
+      # set GOTOOLCHAIN=local if go version >= 1.21
+      def set_gotoolchain_env
+        go_directive = go_mod.content.match(/^go\s(\d+\.\d+)/)&.captures&.first
+        return unless go_directive
```
Comment (deivid-rodriguez) [inline go_modules/lib/dependabot/go_modules/file_parser.rb:33]: Is it required for `go.mod` files to include a `go` directive? If not, should we set `GOTOOLCHAIN=local` in that case or is it better to keep `GOTOOLCHAIN=go1.20.8`?

File: go_modules/spec/dependabot/go_modules/file_parser_spec.rb [hunk 2]
```diff
@@ -10,6 +10,13 @@
 RSpec.describe Dependabot::GoModules::FileParser do
   it_behaves_like "a dependency file parser"
 
+  before(:all) do
+    ENV["LEGACY_GO"] = ENV.fetch("GOTOOLCHAIN")
+  end
+  after(:all) do
+    ENV["GOTOOLCHAIN"] = ENV.fetch("LEGACY_GO")
+  end
```
Comment (deivid-rodriguez) [inline go_modules/spec/dependabot/go_modules/file_parser_spec.rb:18]: The above hooks only run once before and after running all tests in this file. I generally tend to avoid it, except for very expensive setups. This seems only related to the test being added, right? Can we instead move it there?

**Review by deivid-rodriguez — COMMENTED** [review]
Don't know much about this but this makes sense to me. Just left a couple of questions/comments.

File: go_modules/lib/dependabot/go_modules/file_parser.rb (hunk 1 above)
Comment (jakecoffman) [reply go_modules/lib/dependabot/go_modules/file_parser.rb:33]: Surprisingly it is not required, and we do see a small handful of folks who still don't have one set. It's better to leave it for the older 1.20 since 1.21 will try to add a `toolchain` directive.

File: go_modules/spec/dependabot/go_modules/file_parser_spec.rb (hunk 2 above)
Comment (jakecoffman) [reply go_modules/spec/dependabot/go_modules/file_parser_spec.rb:18]: I was seeing a flake where a test in another suite was failing because the GOTOOLCHAIN was still set from what seemed to be a test in this suite. Adding this fixed it, maybe I should remove `before(:all)` and `after(:all)` and just do an `after` here so I can ensure the order of any of these doesn't affect the other tests inside or outside the suite?

Comment (deivid-rodriguez) [reply go_modules/spec/dependabot/go_modules/file_parser_spec.rb:16]: > I was seeing a flake where a test in another suite was failing because the GOTOOLCHAIN was still set from what seemed to be a test in this suite. Adding this fixed it, maybe I should remove after(:all) and just do an after here so I can ensure the order of any of these doesn't affect the other tests inside or outside the suite?

Yes, I think ideally each test that makes a change over the default `GOTOOLCHAIN` should clean up after itself and not leave any side effects. So I think removing the `:all` and doing this for every test would work?

Comment (deivid-rodriguez) [reply go_modules/spec/dependabot/go_modules/file_parser_spec.rb:16]: Sorry our messages crossed. I'll review the new changes.

Comment (jakecoffman) [reply go_modules/spec/dependabot/go_modules/file_parser_spec.rb:16]: I think it's good to review now!

**Review by deivid-rodriguez — APPROVED** [review]
