### PR TITLE
[github_actions] Fix: Update references to actions when they are single- or double-quoted strings

### LINKED ISSUE #2346: [github_actions] Fails to update references to actions when they are single- or double-quoted strings
**Package manager/ecosystem**

- `github_actions`

**Manifest contents prior to update**

See - for example - [`integrate.yaml`](https://github.com/ergebnis/playground/blob/baf17399fd0338453c5eea7ac47402a0d390ff34/.github/workflows/integrate.yaml):

<details>
  <summary>👉 Click here for workflow details</summary>

```yaml
# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Integrate"

on: # yamllint disable-line rule:truthy
  pull_request: null
  push:
    branches:
      - "main"

env:
  MIN_COVERED_MSI: 100
  MIN_MSI: 100
  PHP_EXTENSIONS: "mbstring"

jobs:
  coding-standards:
    name: "Coding Standards"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.4"

        dependencies:
          - "locked"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.1"

      - name: "Lint YAML files"
        uses: "ibiqlik/action-yamllint@v1.0.0"
        with:
          config_file: ".yamllint.yaml"
          file_or_dir: "."
          strict: true

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@2.3.2"
        with:
          coverage: "none"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          php-version: "${{ matrix.php-version }}"

      - name: "Validate composer.json and composer.lock"
        run: "composer validate --strict"

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2.0.0"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

      - name: "Install lowest dependencies from composer.json"
        if: "matrix.dependencies == 'lowest'"
        run: "composer update --no-interaction --no-progress --no-suggest --prefer-lowest"

      - name: "Install locked dependencies from composer.lock"
        if: "matrix.dependencies == 'locked'"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Install highest dependencies from composer.json"
        if: "matrix.dependencies == 'highest'"
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "Run ergebnis/composer-normalize"
        run: "composer normalize --dry-run"

      - name: "Create cache directory for friendsofphp/php-cs-fixer"
        run: "mkdir -p .build/php-cs-fixer"

      - name: "Cache cache directory for friendsofphp/php-cs-fixer"
        uses: "actions/cache@v2.0.0"
        with:
          path: ".build/php-cs-fixer"
          key: "php-${{ matrix.php-version }}-php-cs-fixer-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-php-cs-fixer-"

      - name: "Run friendsofphp/php-cs-fixer"
        run: "vendor/bin/php-cs-fixer fix --config=.php_cs --diff --diff-format=udiff --dry-run --verbose"

  dependency-analysis:
    name: "Dependency Analysis"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.4"

        dependencies:
          - "locked"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.1"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@2.3.2"
        with:
          coverage: "none"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          php-version: "${{ matrix.php-version }}"

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2.0.0"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

      - name: "Install lowest dependencies from composer.json"
        if: "matrix.dependencies == 'lowest'"
        run: "composer update --no-interaction --no-progress --no-suggest --prefer-lowest"

      - name: "Install locked dependencies from composer.lock"
        if: "matrix.dependencies == 'locked'"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Install highest dependencies from composer.json"
        if: "matrix.dependencies == 'highest'"
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "Run maglnet/composer-require-checker"
        run: "tools/composer-require-checker check"

  static-code-analysis:
    name: "Static Code Analysis"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.4"

        dependencies:
          - "locked"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.1"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@2.3.2"
        with:
          coverage: "none"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          php-version: "${{ matrix.php-version }}"

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2.0.0"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

      - name: "Install lowest dependencies from composer.json"
        if: "matrix.dependencies == 'lowest'"
        run: "composer update --no-interaction --no-progress --no-suggest --prefer-lowest"

      - name: "Install locked dependencies from composer.lock"
        if: "matrix.dependencies == 'locked'"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Install highest dependencies from composer.json"
        if: "matrix.dependencies == 'highest'"
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "Create cache directory for phpstan/phpstan"
        run: "mkdir -p .build/phpstan"

      - name: "Cache cache directory for phpstan/phpstan"
        uses: "actions/cache@v2.0.0"
        with:
          path: ".build/phpstan"
          key: "php-${{ matrix.php-version }}-phpstan-${{ github.sha }}"
          restore-keys: "php-${{ matrix.php-version }}-phpstan-"

      - name: "Run phpstan/phpstan"
        run: "vendor/bin/phpstan analyse --configuration=phpstan.neon"

      - name: "Create cache directory for vimeo/psalm"
        run: "mkdir -p .build/psalm"

      - name: "Cache cache directory for vimeo/psalm"
        uses: "actions/cache@v2.0.0"
        with:
          path: ".build/psalm"
          key: "php-${{ matrix.php-version }}-psalm-${{ github.sha }}"
          restore-keys: "php-${{ matrix.php-version }}-psalm-"

      - name: "Run vimeo/psalm"
        run: "vendor/bin/psalm --config=psalm.xml --diff --diff-methods --shepherd --show-info=false --stats --threads=4"

  tests:
    name: "Tests"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.4"

        dependencies:
          - "lowest"
          - "locked"
          - "highest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.1"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@2.3.2"
        with:
          coverage: "none"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          php-version: "${{ matrix.php-version }}"

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2.0.0"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

      - name: "Install lowest dependencies from composer.json"
        if: "matrix.dependencies == 'lowest'"
        run: "composer update --no-interaction --no-progress --no-suggest --prefer-lowest"

      - name: "Install locked dependencies from composer.lock"
        if: "matrix.dependencies == 'locked'"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Install highest dependencies from composer.json"
        if: "matrix.dependencies == 'highest'"
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "Run auto-review tests with phpunit/phpunit"
        run: "vendor/bin/phpunit --configuration=test/AutoReview/phpunit.xml"

      - name: "Run unit tests with phpunit/phpunit"
        run: "vendor/bin/phpunit --configuration=test/Unit/phpunit.xml"

      - name: "Run integration tests with phpunit/phpunit"
        run: "vendor/bin/phpunit --configuration=test/Integration/phpunit.xml"

  code-coverage:
    name: "Code Coverage"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.4"

        dependencies:
          - "locked"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.1"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@2.3.2"
        with:
          coverage: "pcov"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          php-version: "${{ matrix.php-version }}"

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2.0.0"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

      - name: "Install lowest dependencies from composer.json"
        if: "matrix.dependencies == 'lowest'"
        run: "composer update --no-interaction --no-progress --no-suggest --prefer-lowest"

      - name: "Install locked dependencies from composer.lock"
        if: "matrix.dependencies == 'locked'"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Install highest dependencies from composer.json"
        if: "matrix.dependencies == 'highest'"
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "Collect code coverage with pcov and phpunit/phpunit"
        run: "vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --coverage-clover=.build/logs/clover.xml"

      - name: "Send code coverage report to Codecov.io"
        env:
          CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
        run: "bash <(curl -s https://codecov.io/bash)"

  mutation-tests:
    name: "Mutation Tests"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.4"

        dependencies:
          - "locked"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.1"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@2.3.2"
        with:
          coverage: "pcov"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          php-version: "${{ matrix.php-version }}"

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2.0.0"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

      - name: "Install lowest dependencies from composer.json"
        if: "matrix.dependencies == 'lowest'"
        run: "composer update --no-interaction --no-progress --no-suggest --prefer-lowest"

      - name: "Install locked dependencies from composer.lock"
        if: "matrix.dependencies == 'locked'"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Install highest dependencies from composer.json"
        if: "matrix.dependencies == 'highest'"
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "Run mutation tests with pcov and infection/infection"
        run: "vendor/bin/infection --ignore-msi-with-no-mutations --min-covered-msi=${{ env.MIN_COVERED_MSI }} --min-msi=${{ env.MIN_MSI }}"

  merge:
    name: "Merge"

    runs-on: "ubuntu-latest"

    needs:
      - "code-coverage"
      - "coding-standards"
      - "dependency-analysis"
      - "mutation-tests"
      - "static-code-analysis"
      - "tests"

    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.draft == false && (
        github.event.action == 'opened' ||
        github.event.action == 'reopened' ||
        github.event.action == 'synchronize'
      ) && (
        (github.actor == 'dependabot[bot]' && startsWith(github.event.pull_request.title, 'composer(deps-dev)')) ||
        (github.actor == 'dependabot[bot]' && startsWith(github.event.pull_request.title, 'github-actions(deps)')) ||
        (github.actor == 'ergebnis-bot' && github.event.pull_request.title == 'Enhancement: Update license year') ||
        (github.actor == 'localheinz' && contains(github.event.pull_request.labels.*.name, 'merge'))
      )

    steps:
      - name: "Request review from @ergebnis-bot"
        uses: "actions/github-script@v2.0.0"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            const pullRequest = context.payload.pull_request
            const repository = context.repo

            const reviewers = [
              "ergebnis-bot",
            ]

            await github.pulls.createReviewRequest({
              owner: repository.owner,
              pull_number: pullRequest.number,
              repo: repository.repo,
              reviewers: reviewers,
            })

      - name: "Assign @ergebnis-bot"
        uses: "actions/github-script@v2.0.0"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            const pullRequest = context.payload.pull_request
            const repository = context.repo

            const reviewers = [
              "ergebnis-bot",
            ]

            await github.issues.addAssignees({
              assignees: reviewers,
              issue_number: pullRequest.number,
              owner: repository.owner,
              repo: repository.repo,
            })

      - name: "Approve pull request"
        uses: "actions/github-script@v2.0.0"
        if: "github.actor != 'ergebnis-bot'"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            const pullRequest = context.payload.pull_request
            const repository = context.repo

            await github.pulls.createReview({
              event: "APPROVE",
              owner: repository.owner,
              pull_number: pullRequest.number,
              repo: repository.repo,
            })

      - name: "Merge pull request"
        uses: "actions/github-script@v2.0.0"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            const pullRequest = context.payload.pull_request
            const repository = context.repo

            await github.pulls.merge({
              merge_method: "merge",
              owner: repository.owner,
              pull_number: pullRequest.number,
              repo: repository.repo,
            })
```

</details>

**What you expected to see, versus what you actually saw**

RecentlyI have observed the following error message in the GitHub UI when manually triggering updates of GitHub Action workflow dependencies:

Screen Shot 2020-07-20 at 14 42 03

In https://github.com/ergebnis/playground/pull/248 I manually downgraded dependencies, and then triggered an update of GitHub Action workflow dependencies through the GitHub UI.

I then expected the changes in https://github.com/ergebnis/playground/pull/248 to be reverted. Instead, the above error message was displayed in the GitHub UI.

**Images of the diff or a link to the PR, issue or logs**

Here is the corresponding log file:

<details>
  <summary>👉 Click here for update log details</summary>
```text
proxy | time="2020-07-20T10:37:15Z" level=info msg="proxy starting" commit=417a8c750c4f47906f9fcc309451323d68ecc0d3
  proxy | 2020/07/20 10:37:15 Listening (:1080)
updater | time="2020-07-20T10:37:17Z" level=info msg="guest starting" commit=9515e856c5a0d2b59dcd8b2ebf92da50f377b586
updater | time="2020-07-20T10:37:17Z" level=info msg="starting job..." job_id=38578059 updater_version=0.118.7-f934847545b1aadcbcc9cffbb9d1a38a72d9bc03
updater | yarn config v1.22.4
updater | success Set "cafile" to "/etc/ssl/certs/ca-certificates.crt".
updater | Done in 0.03s.
updater | warning: parser/current is loading parser/ruby26, which recognizes
updater | warning: 2.6.6-compliant syntax, but you are running 2.6.5.
updater | warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_38578059> Starting job processing
  proxy | 2020/07/20 10:37:23 GET https://api.github.com:443/repos/ergebnis/playground
  proxy | 2020/07/20 10:37:23 * authenticating github api request
  proxy | 2020/07/20 10:37:23 200 https://api.github.com:443/repos/ergebnis/playground
  proxy | 2020/07/20 10:37:23 GET https://api.github.com:443/repos/ergebnis/playground/git/refs/heads/main
  proxy | 2020/07/20 10:37:23 * authenticating github api request
  proxy | 2020/07/20 10:37:23 200 https://api.github.com:443/repos/ergebnis/playground/git/refs/heads/main
  proxy | 2020/07/20 10:37:23 GET https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:23 * authenticating github api request
  proxy | 2020/07/20 10:37:23 200 https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:23 GET https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/deployment-process.yaml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:23 * authenticating github api request
  proxy | 2020/07/20 10:37:24 200 https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/deployment-process.yaml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:24 GET https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/deployment-production-create.yaml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:24 * authenticating github api request
  proxy | 2020/07/20 10:37:24 200 https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/deployment-production-create.yaml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:24 GET https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/deployment-staging-create.yaml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:24 * authenticating github api request
  proxy | 2020/07/20 10:37:24 200 https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/deployment-staging-create.yaml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:24 GET https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/deployment-staging-delete.yaml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:24 * authenticating github api request
  proxy | 2020/07/20 10:37:24 200 https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/deployment-staging-delete.yaml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:24 GET https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/inform-context.yml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:24 * authenticating github api request
  proxy | 2020/07/20 10:37:24 200 https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/inform-context.yml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:24 GET https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/inform-system.yml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:24 * authenticating github api request
  proxy | 2020/07/20 10:37:24 200 https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/inform-system.yml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:24 GET https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/integrate.yaml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:24 * authenticating github api request
  proxy | 2020/07/20 10:37:24 200 https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/integrate.yaml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:24 GET https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/prune.yaml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:24 * authenticating github api request
  proxy | 2020/07/20 10:37:24 200 https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/prune.yaml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:24 GET https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/release.yaml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:24 * authenticating github api request
  proxy | 2020/07/20 10:37:24 200 https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/release.yaml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:24 GET https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/renew.yaml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:24 * authenticating github api request
  proxy | 2020/07/20 10:37:25 200 https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/renew.yaml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:25 GET https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/triage.yaml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
  proxy | 2020/07/20 10:37:25 * authenticating github api request
  proxy | 2020/07/20 10:37:25 200 https://api.github.com:443/repos/ergebnis/playground/contents/.github/workflows/triage.yaml?ref=baf17399fd0338453c5eea7ac47402a0d390ff34
updater | INFO <job_38578059> Finished job processing
updater | time="2020-07-20T10:37:25Z" level=info msg="task complete" container_id=job-38578059-file-fetcher exit_code=0 job_id=38578059 step=fetcher
updater | yarn config v1.22.4
updater | success Set "cafile" to "/etc/ssl/certs/ca-certificates.crt".
updater | Done in 0.03s.
updater | warning: parser/current is loading parser/ruby26, which recognizes
updater | warning: 2.6.6-compliant syntax, but you are running 2.6.5.
updater | warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_38578059> Starting job processing
updater | INFO <job_38578059> Starting update job for ergebnis/playground
updater | INFO <job_38578059> Checking if actions/stale  needs updating
  proxy | 2020/07/20 10:37:30 GET https://github.com:443/actions/stale.git/info/refs?service=git-upload-pack
  proxy | 2020/07/20 10:37:30 * authenticating git server request (host: github.com)
  proxy | 2020/07/20 10:37:30 200 https://github.com:443/actions/stale.git/info/refs?service=git-upload-pack
updater | INFO <job_38578059> Latest version is 32507178a3f24205bb0f785ecfafa063bd591660
updater | INFO <job_38578059> Requirements to unlock own
updater | INFO <job_38578059> Requirements update strategy 
updater | INFO <job_38578059> Updating actions/stale from  to 32507178a3f24205bb0f785ecfafa063bd591660
updater | I, [2020-07-20T10:37:30.354215 #73]  INFO -- sentry: ** [Raven] Sending event d25242dd0c4f4126a0f034764f01231a to Sentry
  proxy | 2020/07/20 10:37:30 POST https://sentry.io:443/api/1451818/store/
  proxy | 2020/07/20 10:37:30 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_38578059> Error processing actions/stale (RuntimeError)
updater | ERROR <job_38578059> No files changed!
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-github_actions-0.118.7/lib/dependabot/github_actions/file_updater.rb:28:in `updated_dependency_files'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:433:in `generate_dependency_files_for'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:230:in `check_and_create_pull_request'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:65:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `block in run'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `each'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `run'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:16:in `perform_job'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
updater | ERROR <job_38578059> bin/update_files.rb:21:in `<main>'
updater | INFO <job_38578059> Checking if ibiqlik/action-yamllint  needs updating
  proxy | 2020/07/20 10:37:30 GET https://github.com:443/ibiqlik/action-yamllint.git/info/refs?service=git-upload-pack
  proxy | 2020/07/20 10:37:30 * authenticating git server request (host: github.com)
  proxy | 2020/07/20 10:37:30 200 https://github.com:443/ibiqlik/action-yamllint.git/info/refs?service=git-upload-pack
updater | INFO <job_38578059> Latest version is 665205c3255fcf157ef8dc9a40d527fe025a4bc8
updater | INFO <job_38578059> No update needed for ibiqlik/action-yamllint 
updater | INFO <job_38578059> Checking if actions/github-script  needs updating
  proxy | 2020/07/20 10:37:30 GET https://github.com:443/actions/github-script.git/info/refs?service=git-upload-pack
  proxy | 2020/07/20 10:37:30 * authenticating git server request (host: github.com)
  proxy | 2020/07/20 10:37:30 200 https://github.com:443/actions/github-script.git/info/refs?service=git-upload-pack
updater | INFO <job_38578059> Latest version is 6e5ee1dc1cb3740e5e5e76ad668e3f526edbfe45
updater | INFO <job_38578059> No update needed for actions/github-script 
updater | INFO <job_38578059> Checking if shivammathur/setup-php  needs updating
  proxy | 2020/07/20 10:37:31 GET https://github.com:443/shivammathur/setup-php.git/info/refs?service=git-upload-pack
  proxy | 2020/07/20 10:37:31 * authenticating git server request (host: github.com)
  proxy | 2020/07/20 10:37:31 200 https://github.com:443/shivammathur/setup-php.git/info/refs?service=git-upload-pack
updater | INFO <job_38578059> Latest version is 38731c6386cb82423176e3eaf878615515c3da70
updater | INFO <job_38578059> Requirements to unlock own
updater | INFO <job_38578059> Requirements update strategy 
updater | INFO <job_38578059> Updating shivammathur/setup-php from  to 38731c6386cb82423176e3eaf878615515c3da70
updater | I, [2020-07-20T10:37:31.171050 #73]  INFO -- sentry: ** [Raven] Sending event 27e6c1e5660f4ab9afaff4fdf89756be to Sentry
  proxy | 2020/07/20 10:37:31 POST https://sentry.io:443/api/1451818/store/
  proxy | 2020/07/20 10:37:31 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_38578059> Error processing shivammathur/setup-php (RuntimeError)
updater | ERROR <job_38578059> No files changed!
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-github_actions-0.118.7/lib/dependabot/github_actions/file_updater.rb:28:in `updated_dependency_files'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:433:in `generate_dependency_files_for'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:230:in `check_and_create_pull_request'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:65:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `block in run'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `each'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `run'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:16:in `perform_job'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
updater | ERROR <job_38578059> bin/update_files.rb:21:in `<main>'
updater | INFO <job_38578059> Checking if actions/create-release  needs updating
  proxy | 2020/07/20 10:37:31 GET https://github.com:443/actions/create-release.git/info/refs?service=git-upload-pack
  proxy | 2020/07/20 10:37:31 * authenticating git server request (host: github.com)
  proxy | 2020/07/20 10:37:31 200 https://github.com:443/actions/create-release.git/info/refs?service=git-upload-pack
updater | INFO <job_38578059> Latest version is 25a1bf7b5927ddc2c8c2a67d3bb564da1d3428bf
updater | INFO <job_38578059> Requirements to unlock own
updater | INFO <job_38578059> Requirements update strategy 
updater | INFO <job_38578059> Updating actions/create-release from  to 25a1bf7b5927ddc2c8c2a67d3bb564da1d3428bf
updater | I, [2020-07-20T10:37:31.438450 #73]  INFO -- sentry: ** [Raven] Sending event c13cae2c8af945b7b5d5f611fbbfe928 to Sentry
  proxy | 2020/07/20 10:37:31 POST https://sentry.io:443/api/1451818/store/
  proxy | 2020/07/20 10:37:31 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_38578059> Error processing actions/create-release (RuntimeError)
updater | ERROR <job_38578059> No files changed!
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-github_actions-0.118.7/lib/dependabot/github_actions/file_updater.rb:28:in `updated_dependency_files'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:433:in `generate_dependency_files_for'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:230:in `check_and_create_pull_request'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:65:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `block in run'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `each'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `run'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:16:in `perform_job'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
updater | ERROR <job_38578059> bin/update_files.rb:21:in `<main>'
updater | INFO <job_38578059> Checking if actions/cache  needs updating
  proxy | 2020/07/20 10:37:31 GET https://github.com:443/actions/cache.git/info/refs?service=git-upload-pack
  proxy | 2020/07/20 10:37:31 * authenticating git server request (host: github.com)
  proxy | 2020/07/20 10:37:31 200 https://github.com:443/actions/cache.git/info/refs?service=git-upload-pack
updater | INFO <job_38578059> Latest version is b8204782bbb5f872091ecc5eb9cb7d004e35b1fa
updater | INFO <job_38578059> No update needed for actions/cache 
updater | INFO <job_38578059> Checking if actions/checkout  needs updating
  proxy | 2020/07/20 10:37:31 GET https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2020/07/20 10:37:31 * authenticating git server request (host: github.com)
  proxy | 2020/07/20 10:37:31 200 https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
updater | INFO <job_38578059> Latest version is 28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b
updater | INFO <job_38578059> Requirements to unlock own
updater | INFO <job_38578059> Requirements update strategy 
updater | INFO <job_38578059> Updating actions/checkout from  to 28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b
updater | I, [2020-07-20T10:37:31.880415 #73]  INFO -- sentry: ** [Raven] Sending event 497cd5ae74964a06b374c6731f8cac58 to Sentry
  proxy | 2020/07/20 10:37:31 POST https://sentry.io:443/api/1451818/store/
  proxy | 2020/07/20 10:37:31 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_38578059> Error processing actions/checkout (RuntimeError)
updater | ERROR <job_38578059> No files changed!
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-github_actions-0.118.7/lib/dependabot/github_actions/file_updater.rb:28:in `updated_dependency_files'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:433:in `generate_dependency_files_for'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:230:in `check_and_create_pull_request'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:65:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `block in run'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `each'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `run'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:16:in `perform_job'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
updater | ERROR <job_38578059> bin/update_files.rb:21:in `<main>'
updater | INFO <job_38578059> Checking if gr2m/create-or-update-pull-request-action  needs updating
  proxy | 2020/07/20 10:37:32 GET https://github.com:443/gr2m/create-or-update-pull-request-action.git/info/refs?service=git-upload-pack
  proxy | 2020/07/20 10:37:32 * authenticating git server request (host: github.com)
  proxy | 2020/07/20 10:37:32 200 https://github.com:443/gr2m/create-or-update-pull-request-action.git/info/refs?service=git-upload-pack
updater | INFO <job_38578059> Latest version is e9d2e020194f21ce97b3bf56d0c769178582c399
updater | INFO <job_38578059> Requirements to unlock own
updater | INFO <job_38578059> Requirements update strategy 
updater | INFO <job_38578059> Updating gr2m/create-or-update-pull-request-action from  to e9d2e020194f21ce97b3bf56d0c769178582c399
updater | I, [2020-07-20T10:37:32.152941 #73]  INFO -- sentry: ** [Raven] Sending event 9b7b6fc8d0a44f1a93ceca5c46b7ec88 to Sentry
  proxy | 2020/07/20 10:37:32 POST https://sentry.io:443/api/1451818/store/
  proxy | 2020/07/20 10:37:32 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_38578059> Error processing gr2m/create-or-update-pull-request-action (RuntimeError)
updater | ERROR <job_38578059> No files changed!
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-github_actions-0.118.7/lib/dependabot/github_actions/file_updater.rb:28:in `updated_dependency_files'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:433:in `generate_dependency_files_for'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:230:in `check_and_create_pull_request'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:65:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `block in run'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `each'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `run'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:16:in `perform_job'
updater | ERROR <job_38578059> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
updater | ERROR <job_38578059> bin/update_files.rb:21:in `<main>'
updater | INFO <job_38578059> Finished job processing
updater | time="2020-07-20T10:37:32Z" level=info msg="task complete" container_id=job-38578059-updater exit_code=0 job_id=38578059 step=updater
```
</details>

❗ Looking at the logs it appears as if the current version isn't correctly detected - at least it is missing in a log message:

```diff
-updater | INFO <job_38578059> Updating gr2m/create-or-update-pull-request-action from x.y.z to e9d2e020194f21ce97b3bf56d0c769178582c399
+updater | INFO <job_38578059> Updating gr2m/create-or-update-pull-request-action from  to e9d2e020194f21ce97b3bf56d0c769178582c399
```

Screen Shot 2020-07-20 at 14 51 38

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] asserts that references to actions are updated when they are single- or double-quoted strings
* [x] adjusts a regular expression to handle updates of action when they are single- or double-quoted strings

Fixes #2346.

### CODE REVIEW

File: github_actions/lib/dependabot/github_actions/file_updater.rb [hunk 1]
```diff
@@ -69,7 +69,7 @@ def updated_workflow_file_content(file)
           updated_content =
             updated_content.
             gsub(
-              /(?<=\W)#{Regexp.escape(old_declaration)}(?=\s|$)/,
+              /(?<=\W|"|')#{Regexp.escape(old_declaration)}(?=\s|"|'|$)/,
```
Comment (localheinz) [inline github_actions/lib/dependabot/github_actions/file_updater.rb:72]: @feelepxyz 

Does that make sense?

File: github_actions/spec/dependabot/github_actions/file_updater_spec.rb [hunk 2]
```diff
@@ -80,8 +80,10 @@
         updated_files.find { |f| f.name == ".github/workflows/workflow.yml" }
       end
 
-      its(:content) { is_expected.to include "actions/setup-node@v1.1.0\n" }
-      its(:content) { is_expected.to_not include "actions/setup-node@master" }
+      its(:content) { is_expected.to include "\"actions/setup-node@v1.1.0\"\n" }
+      its(:content) {
+        is_expected.to_not include "\"actions/setup-node@master\""
```
Comment (localheinz) [inline github_actions/spec/dependabot/github_actions/file_updater_spec.rb:85]: @feelepxyz 

Needed to wrap here, otherwise Rubocop complains.

**Comment by localheinz** [comment]
@feelepxyz 

Do you have a chance to look at this?

Would be great to get Dependabot update GitHub actions for cases where the actions are quoted strings!

**Comment by localheinz** [comment]
Thank you, @feelepxyz!
