### PR TITLE
bazel: Align version sorting with ecosystem conventions

### LINKED ISSUE #13624: Dependabot producing incorrect results from stale cache of api.github.com
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

bazel

### Package manager version

_No response_

### Language version

_No response_

### Manifest location and content before the Dependabot update

https://github.com/batfish/batfish/blob/2bcba3c8f7642761831c1fc9a99b28bc2cfb6722/MODULE.bazel#L102

### dependabot.yml content

https://github.com/batfish/batfish/blob/master/.github/dependabot.yml

### Updated dependency

rules_python from 1.6.3 to 1.7.0-rc4

### What you expected to see, versus what you actually saw

I expected to see an upgrade to rules_python-1.7.0, which was released a while ago. [RELEASES](https://github.com/bazel-contrib/rules_python/releases)

Instead, I saw that dependabot as of 2025-11-24 only sees 1.7.0-rc4 as the latest version of rules_python. It looks to me like it's incorrectly caching the result of `https://api.github.com/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python` -- this has only a 60s cache-age, and has returned 1.7.0-rc5 and -rc6 and a final release as well. It's weeks out of date at this point.

```
updater | 2025/11/24 00:42:29 INFO <job_1161802626> Checking if rules_python 1.6.3 needs updating
  proxy | 2025/11/24 00:42:29 [299] GET [https://api.github.com:443/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python](https://api.github.com/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python)
2025/11/24 00:42:29 [299] * authenticating github api request with token for api.github.com
  proxy | 2025/11/24 00:42:29 [299] 200 [https://api.github.com:443/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python](https://api.github.com/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python)
  proxy | 2025/11/24 00:42:29 [302] GET [https://api.github.com:443/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python](https://api.github.com/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python)
2025/11/24 00:42:29 [302] 200 [https://api.github.com:443/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python](https://api.github.com/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python) (cached)
  proxy | 2025/11/24 00:42:29 [304] GET [https://api.github.com:443/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python](https://api.github.com/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python)
2025/11/24 00:42:29 [304] 200 [https://api.github.com:443/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python](https://api.github.com/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python) (cached)
updater | 2025/11/24 00:42:29 INFO <job_1161802626> Latest version is 1.7.0-rc4
updater | 2025/11/24 00:42:29 INFO <job_1161802626> Pull request #9606 already exists for rules_python with latest version 1.7.0-rc4
  proxy | 2025/11/24 00:42:29 [306] POST /update_jobs/1161802626/record_ecosystem_meta
2025/11/24 00:42:29 [306] 204 /update_jobs/1161802626/record_ecosystem_meta (cached)
```

### Native package manager behavior

N/A

### Images of the diff or a link to the PR, issue, or logs

https://github.com/batfish/batfish/actions/runs/19619909157/job/56178271013

### Smallest manifest that reproduces the issue

_No response_

### PR DESCRIPTION
**Pull request by a-schur**
Refactors Bazel version handling to match patterns used across other ecosystems (composer, npm_and_yarn, cargo, pub, terraform, etc.):

- Store original version string in @version_string
- Override to_s to preserve original format (1.7.0-rc4, v1.2.3, etc.)
- Strip 'v' prefix before passing to Gem::Version for comparison
- Delegate sorting to Gem::Version's battle-tested <=> operator
- Simplify version_sort_key to return Version objects instead of arrays

This eliminates custom array-based sorting logic and leverages Ruby's built-in version comparison, making the code more maintainable and consistent with the rest of the codebase.

Fixes #13624

### How will you know you've accomplished your goal?
Update job correctly identifies the latest and doesnt fallback to the pre-release version, and matches the proven pattern of other ecosystems, (i.e. (https://github.com/dependabot/dependabot-core/pull/13734/commits/02e06d4f5db542e22da43c354e3b532c35e60b44) also fixes the issue but is not congruent with other ecosystems) @sachin-sandhu 

provided screenshot of before and after changes:
image

### Checklist

- [x] I have run the complete test suite to ensure all tests and linters pass.
- [x] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [x] I have written clear and descriptive commit messages.
- [x] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [x] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

File: bazel/spec/dependabot/bazel/update_checker_spec.rb [hunk 1]
```diff
@@ -908,12 +908,14 @@
...
-        expect(sort_key).to eq([1, 2, 3])
+        expect(sort_key).to be_a(Dependabot::Bazel::Version)
+        expect(sort_key.to_s).to eq("v1.2.3")
       end
 
       it "handles non-numeric version parts" do
         sort_key = checker.send(:version_sort_key, "1.2.beta")
-        expect(sort_key).to eq([1, 2, 0])
+        expect(sort_key).to be_a(Dependabot::Bazel::Version)
+        expect(sort_key.to_s).to eq("1.2.beta")
```
Comment (robaiken) [inline bazel/spec/dependabot/bazel/update_checker_spec.rb:925]: Should we be updating to beta?

Comment (a-schur) [reply bazel/spec/dependabot/bazel/update_checker_spec.rb]: do you want me to chanbge the test entirely to something like this:

      it "handles pre-release versions correctly" do
        sort_key = checker.send(:version_sort_key, "1.2.0-beta")
        stable = checker.send(:version_sort_key, "1.2.0")
        expect(sort_key).to be_a(Dependabot::Bazel::Version)
        expect(sort_key.to_s).to eq("1.2.0-beta")
        expect(sort_key <=> stable).to eq(-1) # Pre-release < stable
      end

File: bazel/spec/dependabot/bazel/update_checker_spec.rb [hunk 2]
```diff
@@ -897,9 +897,9 @@
         sort_key_one_two_zero = checker.send(:version_sort_key, "1.2.0")
         sort_key_one_ten_zero = checker.send(:version_sort_key, "1.10.0")
 
-        expect(sort_key_one_zero_zero).to eq([1, 0, 0])
-        expect(sort_key_one_two_zero).to eq([1, 2, 0])
-        expect(sort_key_one_ten_zero).to eq([1, 10, 0])
+        expect(sort_key_one_zero_zero).to be_a(Dependabot::Bazel::Version)
+        expect(sort_key_one_two_zero).to be_a(Dependabot::Bazel::Version)
+        expect(sort_key_one_ten_zero).to be_a(Dependabot::Bazel::Version)
```
Comment (robaiken) [inline bazel/spec/dependabot/bazel/update_checker_spec.rb:907]: can you update this test to check the version numbers, or something more valuable?

Comment (a-schur) [reply bazel/spec/dependabot/bazel/update_checker_spec.rb]: it now checks the actual version numbers
