### PR TITLE
Let `pip-compile` unlock sub-dependencies when necessary

### LINKED ISSUE #6428: Dependabot fails to create updates for `requirements.in`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

pip-compile

### Language version

_No response_

### Manifest location and content before the Dependabot update

- [requirements.in](https://github.com/GW2ToolBelt/api-generator/blob/0b456a2d0b70354cbf3dd1b9c616359c3791f9a2/.github/workflows/mkdocs-requirements.in)
- [requirements.txt](https://github.com/GW2ToolBelt/api-generator/blob/0b456a2d0b70354cbf3dd1b9c616359c3791f9a2/.github/workflows/mkdocs-requirements.txt)

### dependabot.yml content

[See here](https://github.com/GW2ToolBelt/api-generator/blob/0b456a2d0b70354cbf3dd1b9c616359c3791f9a2/.github/dependabot.yml)

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

According to the logs, Dependabot does correctly identify an outdated dependency (`mkdocs-material 9.0.3`) but does not update it (to `9.0.4`). This is rather unexpected and I can't find anything that should prevent the update. Regardless, the log output is imprecise and rather obscure which makes the exact reason hard to nail down.

It is worth to point out that this did work earlier (for example in https://github.com/GW2ToolBelt/api-generator/pull/198).

(Note. Despite the similarity, this is probably not a duplicate of #2894 since all dependencies are pinned in my case.)

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

Potentially relevant log:
```
updater | INFO <job_578050760> Checking if mkdocs-material 9.0.3 needs updating
  proxy | 2023/01/13 09:15:12 [016] GET https://pypi.org:443/simple/mkdocs-material/
  proxy | 2023/01/13 09:15:12 [016] 200 https://pypi.org:443/simple/mkdocs-material/
updater | INFO <job_578050760> Latest version is 9.0.4

[...]

updater | INFO <job_578050760> Requirements to unlock update_not_possible
updater | INFO <job_578050760> Requirements update strategy bump_versions
updater | INFO <job_578050760> No update possible for mkdocs-material 9.0.3
```

<details>
<summary>Full log</summary>

   ```  proxy | time="2023-01-13T10:22:45Z" level=info msg="proxy starting" commit=3abeec33cb134273ac052ed3ba8262cd42fb53e9
  proxy | 2023/01/13 10:22:45 Listening (:1080)
updater | 2023-01-13T10:22:45.577200491 [578091745:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2023-01-13T10:22:47Z" level=info msg="guest starting" commit=d57a4d446ce4537f92c1c1e90de5561fb5c53247
updater | time="2023-01-13T10:22:47Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=578091745 updater_timeout=45m0s updater_version=51252f33f0e8534939c2fbb5b4180f8bcc8a2c35
updater | I, [2023-01-13T10:22:49.770692 #6]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | INFO <job_578091745> Starting job processing
  proxy | 2023/01/13 10:22:53 [002] GET https://api.github.com:443/repos/GW2ToolBelt/api-generator
  proxy | 2023/01/13 10:22:53 [002] * authenticating github api request
  proxy | 2023/01/13 10:22:53 [002] 200 https://api.github.com:443/repos/GW2ToolBelt/api-generator
  proxy | 2023/01/13 10:22:53 [004] GET https://api.github.com:443/repos/GW2ToolBelt/api-generator/git/refs/heads/master
  proxy | 2023/01/13 10:22:53 [004] * authenticating github api request
  proxy | 2023/01/13 10:22:53 [004] 200 https://api.github.com:443/repos/GW2ToolBelt/api-generator/git/refs/heads/master
  proxy | 2023/01/13 10:22:53 [006] GET https://api.github.com:443/repos/GW2ToolBelt/api-generator/contents/.github/workflows?ref=0b456a2d0b70354cbf3dd1b9c616359c3791f9a2
  proxy | 2023/01/13 10:22:53 [006] * authenticating github api request
  proxy | 2023/01/13 10:22:53 [006] 200 https://api.github.com:443/repos/GW2ToolBelt/api-generator/contents/.github/workflows?ref=0b456a2d0b70354cbf3dd1b9c616359c3791f9a2
  proxy | 2023/01/13 10:22:53 [008] GET https://api.github.com:443/repos/GW2ToolBelt/api-generator/contents/.github/workflows/mkdocs-requirements.in?ref=0b456a2d0b70354cbf3dd1b9c616359c3791f9a2
  proxy | 2023/01/13 10:22:53 [008] * authenticating github api request
  proxy | 2023/01/13 10:22:54 [008] 200 https://api.github.com:443/repos/GW2ToolBelt/api-generator/contents/.github/workflows/mkdocs-requirements.in?ref=0b456a2d0b70354cbf3dd1b9c616359c3791f9a2
  proxy | 2023/01/13 10:22:54 [010] GET https://api.github.com:443/repos/GW2ToolBelt/api-generator/contents/.github/workflows/mkdocs-requirements.txt?ref=0b456a2d0b70354cbf3dd1b9c616359c3791f9a2
  proxy | 2023/01/13 10:22:54 [010] * authenticating github api request
  proxy | 2023/01/13 10:22:54 [010] 200 https://api.github.com:443/repos/GW2ToolBelt/api-generator/contents/.github/workflows/mkdocs-requirements.txt?ref=0b456a2d0b70354cbf3dd1b9c616359c3791f9a2
  proxy | 2023/01/13 10:22:54 [012] GET https://api.github.com:443/repos/GW2ToolBelt/api-generator/contents/?ref=0b456a2d0b70354cbf3dd1b9c616359c3791f9a2
  proxy | 2023/01/13 10:22:54 [012] * authenticating github api request
  proxy | 2023/01/13 10:22:54 [012] 200 https://api.github.com:443/repos/GW2ToolBelt/api-generator/contents/?ref=0b456a2d0b70354cbf3dd1b9c616359c3791f9a2
  proxy | 2023/01/13 10:22:54 [014] GET https://api.github.com:443/repos/GW2ToolBelt/api-generator/contents/.python-version?ref=0b456a2d0b70354cbf3dd1b9c616359c3791f9a2
  proxy | 2023/01/13 10:22:54 [014] * authenticating github api request
  proxy | 2023/01/13 10:22:54 [014] 200 https://api.github.com:443/repos/GW2ToolBelt/api-generator/contents/.python-version?ref=0b456a2d0b70354cbf3dd1b9c616359c3791f9a2
updater | INFO <job_578091745> Finished job processing
updater | time="2023-01-13T10:22:54Z" level=info msg="task complete" container_id=job-578091745-file-fetcher exit_code=0 job_id=578091745 step=fetcher
updater | I, [2023-01-13T10:22:55.922217 #7]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | INFO <job_578091745> Starting job processing
updater | INFO <job_578091745> Starting update job for GW2ToolBelt/api-generator
updater | INFO <job_578091745> Checking if mkdocs-material-extensions 1.1.1 needs updating
  proxy | 2023/01/13 10:23:02 [018] GET https://pypi.org:443/simple/mkdocs-material-extensions/
  proxy | 2023/01/13 10:23:02 [018] 200 https://pypi.org:443/simple/mkdocs-material-extensions/
updater | INFO <job_578091745> Latest version is 1.1.1
updater | INFO <job_578091745> No update needed for mkdocs-material-extensions 1.1.1
updater | INFO <job_578091745> Checking if mkdocs-material 9.0.3 needs updating
  proxy | 2023/01/13 10:23:03 [020] GET https://pypi.org:443/simple/mkdocs-material/
  proxy | 2023/01/13 10:23:03 [020] 200 https://pypi.org:443/simple/mkdocs-material/
updater | INFO <job_578091745> Latest version is 9.0.4
  proxy | 2023/01/13 10:23:05 [022] GET https://pypi.org:443/simple/mike/
  proxy | 2023/01/13 10:23:05 [022] 200 https://pypi.org:443/simple/mike/
  proxy | 2023/01/13 10:23:05 [024] GET https://files.pythonhosted.org:443/packages/66/8a/f226f8c512a4e3ee36438613fde32d371262e985643d308850cf4bdaed15/mike-1.1.2-py3-none-any.whl
  proxy | 2023/01/13 10:23:05 [024] 200 https://files.pythonhosted.org:443/packages/66/8a/f226f8c512a4e3ee36438613fde32d371262e985643d308850cf4bdaed15/mike-1.1.2-py3-none-any.whl
  proxy | 2023/01/13 10:23:05 [026] GET https://pypi.org:443/simple/mkdocs-material/
  proxy | 2023/01/13 10:23:05 [026] 200 https://pypi.org:443/simple/mkdocs-material/
  proxy | 2023/01/13 10:23:05 [028] GET https://files.pythonhosted.org:443/packages/10/60/7a3dbba418ca5e1412efa25d8a52bb0078bbb10ac3e9edd94fe36518fdab/mkdocs_material-9.0.4-py3-none-any.whl
  proxy | 2023/01/13 10:23:05 [028] 200 https://files.pythonhosted.org:443/packages/10/60/7a3dbba418ca5e1412efa25d8a52bb0078bbb10ac3e9edd94fe36518fdab/mkdocs_material-9.0.4-py3-none-any.whl
  proxy | 2023/01/13 10:23:06 [030] GET https://pypi.org:443/simple/mkdocs-material-extensions/
  proxy | 2023/01/13 10:23:06 [030] 200 https://pypi.org:443/simple/mkdocs-material-extensions/
  proxy | 2023/01/13 10:23:06 [032] GET https://files.pythonhosted.org:443/packages/fd/c9/35af8ceabace3e33d1fb64b1749c6f4dac6129faa32f8a4229791f89f56a/mkdocs_material_extensions-1.1.1-py3-none-any.whl
  proxy | 2023/01/13 10:23:06 [032] 200 https://files.pythonhosted.org:443/packages/fd/c9/35af8ceabace3e33d1fb64b1749c6f4dac6129faa32f8a4229791f89f56a/mkdocs_material_extensions-1.1.1-py3-none-any.whl
  proxy | 2023/01/13 10:23:06 [034] GET https://pypi.org:443/simple/jinja2/
  proxy | 2023/01/13 10:23:06 [034] 200 https://pypi.org:443/simple/jinja2/
  proxy | 2023/01/13 10:23:06 [036] GET https://files.pythonhosted.org:443/packages/bc/c3/f068337a370801f372f2f8f6bad74a5c140f6fda3d9de154052708dd3c65/Jinja2-3.1.2-py3-none-any.whl
  proxy | 2023/01/13 10:23:06 [036] 200 https://files.pythonhosted.org:443/packages/bc/c3/f068337a370801f372f2f8f6bad74a5c140f6fda3d9de154052708dd3c65/Jinja2-3.1.2-py3-none-any.whl
  proxy | 2023/01/13 10:23:06 [038] GET https://pypi.org:443/simple/mkdocs/
  proxy | 2023/01/13 10:23:06 [038] 200 https://pypi.org:443/simple/mkdocs/
  proxy | 2023/01/13 10:23:06 [040] GET https://files.pythonhosted.org:443/packages/ff/00/58f2939f8e6c5f981d9ad9b685c9915a3b315c8f34ba93f0020d64929f70/mkdocs-1.4.2-py3-none-any.whl
  proxy | 2023/01/13 10:23:06 [040] 200 https://files.pythonhosted.org:443/packages/ff/00/58f2939f8e6c5f981d9ad9b685c9915a3b315c8f34ba93f0020d64929f70/mkdocs-1.4.2-py3-none-any.whl
  proxy | 2023/01/13 10:23:07 [042] GET https://pypi.org:443/simple/pyyaml/
  proxy | 2023/01/13 10:23:07 [042] 200 https://pypi.org:443/simple/pyyaml/
  proxy | 2023/01/13 10:23:07 [044] GET https://files.pythonhosted.org:443/packages/56/8f/e8b49ad21d26111493dc2d5cae4d7efbd0e2e065440665f5023515f87f64/PyYAML-6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  proxy | 2023/01/13 10:23:07 [044] 200 https://files.pythonhosted.org:443/packages/56/8f/e8b49ad21d26111493dc2d5cae4d7efbd0e2e065440665f5023515f87f64/PyYAML-6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  proxy | 2023/01/13 10:23:07 [046] GET https://pypi.org:443/simple/verspec/
  proxy | 2023/01/13 10:23:07 [046] 200 https://pypi.org:443/simple/verspec/
  proxy | 2023/01/13 10:23:07 [048] GET https://files.pythonhosted.org:443/packages/a4/ce/3b6fee91c85626eaf769d617f1be9d2e15c1cca027bbdeb2e0d751469355/verspec-0.1.0-py3-none-any.whl
  proxy | 2023/01/13 10:23:07 [048] 200 https://files.pythonhosted.org:443/packages/a4/ce/3b6fee91c85626eaf769d617f1be9d2e15c1cca027bbdeb2e0d751469355/verspec-0.1.0-py3-none-any.whl
  proxy | 2023/01/13 10:23:07 [050] GET https://pypi.org:443/simple/colorama/
  proxy | 2023/01/13 10:23:07 [050] 200 https://pypi.org:443/simple/colorama/
  proxy | 2023/01/13 10:23:07 [052] GET https://files.pythonhosted.org:443/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl
  proxy | 2023/01/13 10:23:07 [052] 200 https://files.pythonhosted.org:443/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl
  proxy | 2023/01/13 10:23:07 [054] GET https://pypi.org:443/simple/markdown/
  proxy | 2023/01/13 10:23:07 [054] 200 https://pypi.org:443/simple/markdown/
  proxy | 2023/01/13 10:23:07 [056] GET https://files.pythonhosted.org:443/packages/f3/df/ca72f352e15b6f8ce32b74af029f1189abffb906f7c137501ffe69c98a65/Markdown-3.3.7-py3-none-any.whl
  proxy | 2023/01/13 10:23:07 [056] 200 https://files.pythonhosted.org:443/packages/f3/df/ca72f352e15b6f8ce32b74af029f1189abffb906f7c137501ffe69c98a65/Markdown-3.3.7-py3-none-any.whl
  proxy | 2023/01/13 10:23:07 [058] GET https://pypi.org:443/simple/pygments/
  proxy | 2023/01/13 10:23:07 [058] 200 https://pypi.org:443/simple/pygments/
  proxy | 2023/01/13 10:23:08 [060] GET https://files.pythonhosted.org:443/packages/0b/42/d9d95cc461f098f204cd20c85642ae40fbff81f74c300341b8d0e0df14e0/Pygments-2.14.0-py3-none-any.whl
  proxy | 2023/01/13 10:23:08 [060] 200 https://files.pythonhosted.org:443/packages/0b/42/d9d95cc461f098f204cd20c85642ae40fbff81f74c300341b8d0e0df14e0/Pygments-2.14.0-py3-none-any.whl
  proxy | 2023/01/13 10:23:08 [062] GET https://pypi.org:443/simple/pymdown-extensions/
  proxy | 2023/01/13 10:23:08 [062] 200 https://pypi.org:443/simple/pymdown-extensions/
  proxy | 2023/01/13 10:23:08 [064] GET https://files.pythonhosted.org:443/packages/7d/18/5b6ed8ccc6a82f4ce0e9f8b23faef75473e36822795a185df13f54e19c1c/mkdocs_material-9.0.3-py3-none-any.whl
  proxy | 2023/01/13 10:23:08 [064] 200 https://files.pythonhosted.org:443/packages/7d/18/5b6ed8ccc6a82f4ce0e9f8b23faef75473e36822795a185df13f54e19c1c/mkdocs_material-9.0.3-py3-none-any.whl
  proxy | 2023/01/13 10:23:08 [066] GET https://files.pythonhosted.org:443/packages/30/73/042b9e78175b2f57e544ee745b940caf14365053016ea8e3320ea798cfbc/pymdown_extensions-9.9-py3-none-any.whl
  proxy | 2023/01/13 10:23:08 [066] 200 https://files.pythonhosted.org:443/packages/30/73/042b9e78175b2f57e544ee745b940caf14365053016ea8e3320ea798cfbc/pymdown_extensions-9.9-py3-none-any.whl
  proxy | 2023/01/13 10:23:08 [068] GET https://pypi.org:443/simple/regex/
  proxy | 2023/01/13 10:23:08 [068] 200 https://pypi.org:443/simple/regex/
  proxy | 2023/01/13 10:23:10 [070] GET https://files.pythonhosted.org:443/packages/3e/cf/97a89e2b798988118beed6620dbfbc9b4bd72d8177b3b4ed47d80da26df9/regex-2022.10.31-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  proxy | 2023/01/13 10:23:10 [070] 200 https://files.pythonhosted.org:443/packages/3e/cf/97a89e2b798988118beed6620dbfbc9b4bd72d8177b3b4ed47d80da26df9/regex-2022.10.31-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  proxy | 2023/01/13 10:23:10 [072] GET https://pypi.org:443/simple/requests/
  proxy | 2023/01/13 10:23:10 [072] 200 https://pypi.org:443/simple/requests/
  proxy | 2023/01/13 10:23:11 [074] GET https://pypi.org:443/simple/markupsafe/
  proxy | 2023/01/13 10:23:11 [074] 200 https://pypi.org:443/simple/markupsafe/
  proxy | 2023/01/13 10:23:11 [076] GET https://files.pythonhosted.org:443/packages/1d/97/2288fe498044284f39ab8950703e88abbac2abbdf65524d576157af70556/MarkupSafe-2.1.1.tar.gz
  proxy | 2023/01/13 10:23:11 [076] 200 https://files.pythonhosted.org:443/packages/1d/97/2288fe498044284f39ab8950703e88abbac2abbdf65524d576157af70556/MarkupSafe-2.1.1.tar.gz
  proxy | 2023/01/13 10:23:12 [078] GET https://pypi.org:443/simple/click/
  proxy | 2023/01/13 10:23:12 [078] 200 https://pypi.org:443/simple/click/
  proxy | 2023/01/13 10:23:12 [080] GET https://pypi.org:443/simple/ghp-import/
  proxy | 2023/01/13 10:23:12 [080] 200 https://pypi.org:443/simple/ghp-import/
  proxy | 2023/01/13 10:23:12 [082] GET https://files.pythonhosted.org:443/packages/f7/ec/67fbef5d497f86283db54c22eec6f6140243aae73265799baaaa19cd17fb/ghp_import-2.1.0-py3-none-any.whl
  proxy | 2023/01/13 10:23:12 [082] 200 https://files.pythonhosted.org:443/packages/f7/ec/67fbef5d497f86283db54c22eec6f6140243aae73265799baaaa19cd17fb/ghp_import-2.1.0-py3-none-any.whl
  proxy | 2023/01/13 10:23:12 [084] GET https://pypi.org:443/simple/mergedeep/
  proxy | 2023/01/13 10:23:12 [084] 200 https://pypi.org:443/simple/mergedeep/
  proxy | 2023/01/13 10:23:12 [086] GET https://files.pythonhosted.org:443/packages/2c/19/04f9b178c2d8a15b076c8b5140708fa6ffc5601fb6f1e975537072df5b2a/mergedeep-1.3.4-py3-none-any.whl
  proxy | 2023/01/13 10:23:12 [086] 200 https://files.pythonhosted.org:443/packages/2c/19/04f9b178c2d8a15b076c8b5140708fa6ffc5601fb6f1e975537072df5b2a/mergedeep-1.3.4-py3-none-any.whl
  proxy | 2023/01/13 10:23:12 [088] GET https://pypi.org:443/simple/packaging/
  proxy | 2023/01/13 10:23:12 [088] 200 https://pypi.org:443/simple/packaging/
  proxy | 2023/01/13 10:23:12 [090] GET https://files.pythonhosted.org:443/packages/8f/7b/42582927d281d7cb035609cd3a543ffac89b74f3f4ee8e1c50914bcb57eb/packaging-22.0-py3-none-any.whl
  proxy | 2023/01/13 10:23:12 [090] 200 https://files.pythonhosted.org:443/packages/8f/7b/42582927d281d7cb035609cd3a543ffac89b74f3f4ee8e1c50914bcb57eb/packaging-22.0-py3-none-any.whl
  proxy | 2023/01/13 10:23:13 [092] GET https://pypi.org:443/simple/pyyaml-env-tag/
  proxy | 2023/01/13 10:23:13 [092] 200 https://pypi.org:443/simple/pyyaml-env-tag/
  proxy | 2023/01/13 10:23:13 [094] GET https://files.pythonhosted.org:443/packages/5a/66/bbb1dd374f5c870f59c5bb1db0e18cbe7fa739415a24cbd95b2d1f5ae0c4/pyyaml_env_tag-0.1-py3-none-any.whl
  proxy | 2023/01/13 10:23:13 [094] 200 https://files.pythonhosted.org:443/packages/5a/66/bbb1dd374f5c870f59c5bb1db0e18cbe7fa739415a24cbd95b2d1f5ae0c4/pyyaml_env_tag-0.1-py3-none-any.whl
  proxy | 2023/01/13 10:23:13 [096] GET https://pypi.org:443/simple/watchdog/
  proxy | 2023/01/13 10:23:13 [096] 200 https://pypi.org:443/simple/watchdog/
  proxy | 2023/01/13 10:23:13 [098] GET https://files.pythonhosted.org:443/packages/6f/94/b777029fdc7b1353e24ddc9f9f9bc0fe7788e684d036db20ded1a1b07aa6/watchdog-2.2.1-py3-none-manylinux2014_x86_64.whl
  proxy | 2023/01/13 10:23:13 [098] 200 https://files.pythonhosted.org:443/packages/6f/94/b777029fdc7b1353e24ddc9f9f9bc0fe7788e684d036db20ded1a1b07aa6/watchdog-2.2.1-py3-none-manylinux2014_x86_64.whl
  proxy | 2023/01/13 10:23:13 [100] GET https://pypi.org:443/simple/charset-normalizer/
  proxy | 2023/01/13 10:23:13 [100] 200 https://pypi.org:443/simple/charset-normalizer/
  proxy | 2023/01/13 10:23:13 [102] GET https://pypi.org:443/simple/idna/
  proxy | 2023/01/13 10:23:13 [102] 200 https://pypi.org:443/simple/idna/
  proxy | 2023/01/13 10:23:13 [104] GET https://pypi.org:443/simple/urllib3/
  proxy | 2023/01/13 10:23:13 [104] 200 https://pypi.org:443/simple/urllib3/
  proxy | 2023/01/13 10:23:14 [106] GET https://pypi.org:443/simple/certifi/
  proxy | 2023/01/13 10:23:14 [106] 200 https://pypi.org:443/simple/certifi/
  proxy | 2023/01/13 10:23:14 [108] GET https://pypi.org:443/simple/python-dateutil/
  proxy | 2023/01/13 10:23:14 [108] 200 https://pypi.org:443/simple/python-dateutil/
  proxy | 2023/01/13 10:23:14 [110] GET https://files.pythonhosted.org:443/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl
  proxy | 2023/01/13 10:23:14 [110] 200 https://files.pythonhosted.org:443/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl
  proxy | 2023/01/13 10:23:14 [112] GET https://pypi.org:443/simple/six/
  proxy | 2023/01/13 10:23:14 [112] 200 https://pypi.org:443/simple/six/
updater | INFO <job_578091745> Requirements to unlock update_not_possible
updater | INFO <job_578091745> Requirements update strategy bump_versions
updater | INFO <job_578091745> No update possible for mkdocs-material 9.0.3
updater | INFO <job_578091745> Checking if mike 1.1.2 needs updating
  proxy | 2023/01/13 10:23:18 [114] GET https://pypi.org:443/simple/mike/
  proxy | 2023/01/13 10:23:18 [114] 200 https://pypi.org:443/simple/mike/
updater | INFO <job_578091745> Latest version is 1.1.2
updater | INFO <job_578091745> No update needed for mike 1.1.2
updater | INFO <job_578091745> Finished job processing
updater | time="2023-01-13T10:23:18Z" level=info msg="task complete" container_id=job-578091745-updater exit_code=0 job_id=578091745 step=updater
   ```  
</details>

### Smallest manifest that reproduces the issue

_No response_

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
This is what's normally done when updating a direct dependency through pip-compile:

* Say we have `mkdocs-material==9.0.3` in the requirements.in file.
* We'll first unlock the requirement to allow the latest version, like this: `mkdocs-material>=9.0.3,<=9.0.4`.
* Then we'll run something like `pip-compile -v --build-isolation --allow-unsafe --resolver backtracking --output-file=requirements.txt -P mkdocs-material requirements.in`.
* Then we'll look at the version of `mkdocs-material` in the new requirements.txt and we'll consider that version as the latest resolvable version.

However, if updating to 9.0.4 requires an indirect dependency to also be updated, the above `pip-compile` command won't update anything in the lockfile, since it finds an existing `requirement.txt` and is happy with that.

BUT I observed that forcing the requirement to be `9.0.4` instead through `mkdocs-material==9.0.4`, then `pip-compile` will run into a conflict and automatically resolve it by unlock what needs to be unlocked, showing the following output:

```
  ERROR: Cannot install -r mkdocs-requirements.in (line 2) because these package versions have conflicting dependencies.
Discarding pymdown-extensions==9.9 (from -r mkdocs-requirements.txt (line 17)) to proceed the resolution
...
```

And happily updates the `requirements.txt` to use the latest version of `mkdocs-material` and also a compatible version of the subdependency.

This is exactly what security updates do to "force" the fixed version, but I think we can leverage that for version updates too.

With this change, an update running into this situation succeeds:

```
$ bin/dry-run.rb pip GW2ToolBelt/api-generator --dep mkdocs-material --cache=files --dir /.github/workflows/

=> reading dependency files from cache manifest: ./dry-run/GW2ToolBelt/api-generator/.github/workflows/cache-manifest-pip.json
=> parsing dependency files
=> updating 1 dependencies: mkdocs-material

=== mkdocs-material (9.0.3)
 => checking for updates 1/1
🌍 https://pypi.org/simple/mkdocs-material/
 => latest available version is 9.0.4
 => latest allowed version is 9.0.4
 => requirements to unlock: own
 => requirements update strategy: bump_versions
 => updating mkdocs-material from 9.0.3 to 9.0.4

    ± mkdocs-requirements.in
    ~~~
    2c2
    < mkdocs-material==9.0.3
    ---
    > mkdocs-material==9.0.4
    ~~~

    ± mkdocs-requirements.txt
    ~~~
    13c13
    < mkdocs-material==9.0.3
    ---
    > mkdocs-material==9.0.4
    17c17
    < pymdown-extensions==9.9
    ---
    > pymdown-extensions==9.9.1
    ~~~
🌍 Total requests made: '1'
```

~Still needs tests but should fix #6428.~

Tests added.

Fixes #6428.

### CODE REVIEW

File: python/spec/dependabot/python/update_checker_spec.rb [hunk 1]
```diff
@@ -366,7 +393,7 @@
       context "including pep621 dependencies" do
         let(:pyproject_fixture_name) { "pep621_exact_requirement.toml" }
 
-        it "delegates to PoetryVersionResolver" do
```
Comment (jeffwidman) [inline python/spec/dependabot/python/update_checker_spec.rb:369]: nice spot

**Review by jeffwidman — APPROVED** [review]
The PR description makes sense, but the code change is a little harder to parse because it looks like there's some refactoring going on that took a bit to step through. I _think_ it all makes sense, and I'm comfortable trusting our CI suite here. So let's 🚢 and if it turns out we overlooked something we can fix that when we encounter it.
