### PR TITLE
Fix Elixir support for new mix.lock format

### LINKED ISSUE #1675: Elixir dependency parsing fails with latest `mix.lock` format
Dependabot opened an issue called "Dependabot can't evaluate your Elixir dependency files" with the following error:

```
** (FunctionClauseError) no function clause matching in Parser.parse_lock/1    
    
    The following arguments were given to Parser.parse_lock/1:
    
        # 1
        {:hex, :libcluster, "3.1.1", "cbab97b96141f47f2fe5563183c444bbce9282b3991ef054d69b8805546f0122", [:mix], [{:jason, "~> 1.1.2", [hex: :jason, repo: "hexpm", optional: false]}], "hexpm", "8eaf6b0ca713f70ff588596743becba3e0ddda9ec14873adf7634ea705afc6f3"}
    
    parse_deps.exs:69: Parser.parse_lock/1
    parse_deps.exs:19: Parser.build_dependency/2
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    parse_deps.exs:101: (file)

{"error":""}
```

This appears to be due to an update to [the hex package to `v0.20.2`](https://github.com/hexpm/hex/releases). Specifically, [this PR](https://github.com/hexpm/hex/pull/708) adds `outer_checksum` to the end of the `mix.lock` dependency tuple. This issue is still present in the latest version, `v0.20.4`.

The error shown above is occurring because `parse_lock` pattern matches against the `mix.lock` tuple and it doesn't have a match for the new tuple format with the new checksum at the end.

---

There isn't a straightforward way to roll back the version of `hex` for a given project. You run `mix local.hex` and it goes and finds the latest version for your version of elixir. I looked in the code for that mix task and found that it identifies the latest version by looking at the CSV https://repo.hex.pm/installs/hex-1.x.csv. hex `v0.20.4` is listed for all Elixir versions from `1.0.0` to `1.10.0`, so this isn't limited to the latest version of Elixir. However, the problem does not occur until you run `mix local.hex` and commit the updated `mix.lock` file.

### PR DESCRIPTION
**Pull request by barthez**
Hello,

Recently hex was updated and new mix.lock file format is not supported by Dependabot. I prepared a fix for that. It also fixes #1675

### CODE REVIEW

File: hex/helpers/lib/parse_deps.exs [hunk 1]
```diff
@@ -69,6 +69,9 @@ defmodule Parser do
   defp parse_lock({:git, repo_url, checksum, opts}),
     do: {nil, checksum, git_source(repo_url, opts)}
 
+  defp parse_lock({:hex, _app, version, checksum, _managers, _dependencies, _source, _outer_checksum}),
```
Comment (ericmj) [inline hex/helpers/lib/parse_deps.exs]: This checksum is deprecated, the `outer_checksum` should be used instead.

Comment (ericmj) [reply hex/helpers/lib/parse_deps.exs]: To make sure you don't crash again when a new field is added to the lockfile entry you can do something like this:
```
destructure [:hex, _app, version, checksum], Tuple.to_list(lock)
```

Comment (feelepxyz) [reply hex/helpers/lib/parse_deps.exs]: Ahh should the outer checksum be used in the following line? `do: {version, _outer_checksum, nil}`

How would you write this with the suggested `destructure`?

Comment (ericmj) [reply hex/helpers/lib/parse_deps.exs]: Yes:

```elixir
destructure(
  [:hex, _app, version, _inner_checksum, _managers, _dependencies, _source, outer_checksum],
  Tuple.to_list(lock)
)

{version, outer_checksum, nil}
```

Though I don't know if changing the checksum will cause issues for dependendabot, for example if it will cause conflicts with an internal database of existing checksums.

Comment (feelepxyz) [reply hex/helpers/lib/parse_deps.exs]: @ericmj cheers! Shouldn't cause any issues for Dependabot as we're not storing any of this info.

I'm still a bit unclear on the exact codes 🤠(don't actually know Elixir), would the method look like so?:

```
defp parse_lock(destructure(
  [:hex, _app, version, _inner_checksum, _managers, _dependencies, _source, outer_checksum],
  Tuple.to_list(lock)
)),
  do: {version, outer_checksum, nil}
```

Would this still would work with the existing method signatures? If you have the time, would love a PR fixing this up 🙇‍♂️

Comment (ericmj) [reply hex/helpers/lib/parse_deps.exs]: It would look like this:

```elixir
defp parse_lock(tuple) when elem(tuple, 0) == :hex do
  destructure(
    [:hex, _app, version, _inner_checksum, _managers, _dependencies, _source, outer_checksum],
    Tuple.to_list(lock)
  )

  {version, outer_checksum, nil}
end
```

And it would remove the need for the other `parse_lock({:hex, ...` clauses.

I can send a PR.
