### PR TITLE
fix(gradle): update dependencies only if group and artifact ids are the same

### LINKED ISSUE #7002: Wrong dependency get its version increased
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Gradle

### Package manager version

_No response_

### Language version

Java

### Manifest location and content before the Dependabot update

_No response_

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
```

### Updated dependency

name com.graphql-java:graphql-java
to 20.2
from 20.0

### What you expected to see, versus what you actually saw

I expected to see:
```
-    implementation 'com.graphql-java:graphql-java:20.0'
+   implementation 'com.graphql-java:graphql-java:20.2'
```
But I actually saw:
```
-    implementation 'com.graphql-java:graphql-java-extended-scalars:20.0'
-    implementation 'com.graphql-java:graphql-java:20.0'
+    implementation 'com.graphql-java:graphql-java-extended-scalars:20.2'
+   implementation 'com.graphql-java:graphql-java:20.2'
```

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

Bump com graphql-java graphql-java from 20 0 to 20 2 by dependabot

### Smallest manifest that reproduces the issue

plugins {
    id 'war'
}

compileJava {
    sourceCompatibility = 1.8
    targetCompatibility = 1.8
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

repositories {
    google()
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation 'com.graphql-java:graphql-java-extended-scalars:20.0'
    implementation 'com.graphql-java:graphql-java:20.0'
}

### PR DESCRIPTION
**Pull request by yeikel**
With the current implementation, any line matching the requirement is upgraded. That leads to undesired side effects as described in the issue

Fixes #7002

### CODE REVIEW

File: gradle/lib/dependabot/gradle/file_updater.rb [hunk 1]
```diff
@@ -150,9 +151,25 @@ def original_buildfile_declarations(dependency, requirement)
...
-          line.include?(requirement.fetch(:requirement))
+          if dependency.name.include?(":")
+            group, name = dependency.name.split(":")
+            version = requirement.fetch(:requirement)
+
+            pattern = if line.include?("group")
+                        # rubocop:disable Layout/LineLength
+                        /group\s*[=:]\s*['"]#{group}['"]\s*,\s*name\s*[=:]\s*['"]#{name}['"]\s*,\s*version\s*[=:]\s*['"]#{version}['"]/
+                        # rubocop:enable Layout/LineLength
+                      else
```
Comment (yeikel) [inline gradle/lib/dependabot/gradle/file_updater.rb:162]: This regex logic is very brittle, it took me many iterations to accommodate all the different specs that we have

Is there any better way to do this? (without native helpers?)

Sadly, there are a lot of different ways to declare a dependency in gradle and that does not help

Comment (yeikel) [reply gradle/lib/dependabot/gradle/file_updater.rb:162]: Also, I decided to disable `Layout/LineLength` because I think that multiple lines would make the regex even more confusing. But we can revert it if needed

Comment (Nishnha) [reply gradle/lib/dependabot/gradle/file_updater.rb:162]: Agreed that this isn't ideal - Gradle does support other styles of declaring dependencies in its DSL including a [map notation](https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyHandler.java#L159) and it isn't clear if/how it's supported here

Renovate has a [Gradle parser](https://github.com/renovatebot/renovate/pull/75210) that we could shell out to but I think we can open it as a separate issue since it's pretty involved

Comment (yeikel) [reply gradle/lib/dependabot/gradle/file_updater.rb:162]: I agree. At some point, I think that we should see if we can leverage native Gradle code directly to do all of this

**Comment by jeffwidman** [comment]
👋 I haven't forgotten about this / missed the notifications, just been busy with some other work and this PR requires deeper review than a cursory approve/merge. I hope to get to this soon.

**Comment by yeikel** [comment]
> 👋 I haven't forgotten about this / missed the notifications, just been busy with some other work and this PR requires deeper review than a cursory approve/merge. I hope to get to this soon if no one else on the team gets to it first.

Understandable, please let me know if anything is unclear or if I can add any additional explanation to the change (comments, more tests, etc)

**Comment by deivid-rodriguez** [comment]
@yeikel What do you think about this alternative implementation?

```diff
diff --git a/gradle/lib/dependabot/gradle/file_updater.rb b/gradle/lib/dependabot/gradle/file_updater.rb
index cf8053bfb..3875b0406 100644
--- a/gradle/lib/dependabot/gradle/file_updater.rb
+++ b/gradle/lib/dependabot/gradle/file_updater.rb
@@ -139,15 +139,27 @@ module Dependabot
           line = evaluate_properties(line, buildfile)
           line = line.gsub(%r{(?<=^|\s)//.*$}, "")
 
-          if dependency.name.include?(":")
-            next false unless line.include?(dependency.name.split(":").first)
-            next false unless line.include?(dependency.name.split(":").last)
-          elsif requirement.fetch(:file).end_with?(".toml")
-            next false unless line.include?(dependency.name)
+          line_in_file_matches_dep?(line, dependency, requirement)
+        end
+      end
+
+      def line_in_file_matches_dep?(line, dependency, requirement)
+        if dependency.name.include?(":")
+          group, name = dependency.name.split(":")
+          version = requirement.fetch(:requirement)
+
+          line.include?("#{group}:#{name}:#{version}") || (
+            /group\s*[=:]\s*['"]#{group}['"]/.match?(line) &&
+            /name\s*[=:]\s*['"]#{name}['"]/.match?(line) &&
+            /version\s*[=:]\s*['"]#{version}['"]/.match?(line)
+          )
+        else
+          if requirement.fetch(:file).end_with?(".toml")
+            return false unless line.include?(dependency.name)
           else
             name_regex_value = /['"]#{Regexp.quote(dependency.name)}['"]/
             name_regex = /(id|kotlin)(\s+#{name_regex_value}|\(#{name_regex_value}\))/
-            next false unless line.match?(name_regex)
+            return false unless line.match?(name_regex)
           end
 
           line.include?(requirement.fetch(:requirement))
```

I think it's simpler.

I wasn't sure whether `group`, `name` and `version` can be defined in different order, so I splitted your regex into three. But if the order is fixed, then your unified regex would be better?

**Comment by yeikel** [comment]
> @yeikel What do you think about this alternative implementation?

> I wasn't sure whether `group`, `name` and `version` can be defined in different order, so I splitted your regex into three. But if the order is fixed, then your unified regex would be better?

I just verified this, Gradle is such a mess :sight


All these combinations are valid

```
    implementation name: 'graphql-java', version: '20.0',group: 'com.graphql-java'
    implementation version: '20.0',group: 'com.graphql-java',name: 'graphql-java'
    implementation group: 'com.graphql-java' version: '20.0',name: 'graphql-java'
```

I'll update the PR with your suggestion and add these as specs

**Comment by yeikel** [comment]
Good to go now. Thank you!

**Review by deivid-rodriguez — APPROVED** [review]
Awesome thanks!

**Comment by jakecoffman** [comment]
Looks like the Gradle version catalog smoke test is failing from this change: https://github.com/dependabot/smoke-tests/actions/runs/4958126997/jobs/8870933950

It's not listed in this repo's smoke.yaml workflow which is why we didn't see it sooner.

**Comment by deivid-rodriguez** [comment]
Thanks for the quick notice!

**Comment by deivid-rodriguez** [comment]
@yeikel You'd need to reopen this now and we need to figure out how this broke gradle version catalog updates. Sorry about that 😬.

**Comment by yeikel** [comment]
I am surprised that no spec caught this
 

I'll take a look at it later today. Sorry for the trouble!

**Comment by yeikel** [comment]
> Yeah, that's my mistake since we I added a smoke test for gradle version catalogs, I forgot to add it to dependabot-core CI, only added it to the smoke-tests repo CI. I hope we make some improvements so this kind of mistake is less likely to happen. Anyways, the smoke test has been added and should catch the issue now!

Thank you

Maybe a bit off topic, but is there any reason/benefits  to have the smoke tests in a separate repository?

When a pull request involves updating smoke tests, it is quite challenging to test the changes together without touching the CI configuration

**Comment by deivid-rodriguez** [comment]
Totally agree with you @yeikel and I hope to eventually move the smoke tests themselves inside this repo to ease working with the smoke test CI.
