### PR TITLE
Fix allow update-types filtering for individual dependency updates

### LINKED ISSUE #12668: Add support for `update-types` in `allow` block
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature description

Here’s a polished and professional rewording of your message, maintaining clarity while improving flow and tone:

---

While working with an open source project to [[onboard to Dependabot](https://github.com/vert-x3/vertx-micrometer-metrics/issues/267)](https://github.com/vert-x3/vertx-micrometer-metrics/issues/267), I was asked to implement the following requirements:

> Can we configure it to:
>
> * Watch only Micrometer upgrades
> * Propose PRs for micro releases only

Implementing this with Dependabot wasn't straightforward, primarily because it required combining both `allow` and `ignore` rules in a non-obvious way.

Intuitively, one might expect the configuration to look like this:

```yaml
version: 2
updates:
  - package-ecosystem: maven
    base-directory: /
    target-branch: master
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "io.micrometer:micrometer-core"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
```

However, since `update-types` is not supported under the `allow` block, the actual working configuration seems to be:

```yml

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: master
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "io.micrometer:micrometer-core"
    ignore:
      - dependency-name: "io.micrometer:micrometer-core"
        update-types:
          - "version-update:semver-major"
```

While this workaround achieves the goal, I believe it's unintuitive—especially for users new to Dependabot. Supporting `update-types` directly in the `allow` block would simplify these kinds of use cases and reduce the need for complex configuration patterns.

### PR DESCRIPTION
**Pull request by kbukum1**
### What are you trying to accomplish?

Fixes #12668

Follow-up to #12925. The `update-types` check in `allowed_update?` runs pre-resolution when `previous_version` is nil, so the filter is silently skipped for individual updates.

This moves `update-types` filtering to `ignore_conditions_for`, converting allowed types into inverse ignore version ranges — the same mechanism `ignore` update-types already uses, which only needs the current version.

Related: #12925, [API #8052](https://github.com/github/dependabot-api/pull/8052), [CLI #605](https://github.com/dependabot/cli/pull/605)

### Anything you want to highlight for special attention from reviewers?

`allowed_update?` is a dependency-level gate (name, type) that runs pre-resolution. Version-level filtering belongs in `ignore_conditions_for` which only needs the current installed version to compute ranges.

Test repo: https://github.com/dsp-testing/dependabot-allow-update-types

### How will you know you have accomplished your goal?

- Existing and new tests pass
- Re-running Dependabot on the test repo should only create PRs matching the configured `update-types` filters

### Checklist

- [x] I have run the complete test suite to ensure all tests and linters pass.
- [x] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [x] I have written clear and descriptive commit messages.
- [x] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [x] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

File: updater/lib/dependabot/job.rb [hunk 1]
```diff
@@ -324,15 +326,6 @@ def allowed_update?(dependency, check_previous_version: false)
...
         next false unless name_match?(condition_name, dependency.name)
 
-        # Check update-types (semver-based filtering) - security updates bypass this
-        allowed_update_types = update.fetch("update-types", nil)
-        if allowed_update_types.is_a?(Array) && !allowed_update_types.empty? && !security_update
-          dep_update_type = update_type_for_dependency(dependency)
-          config_type = "version-update:semver-#{dep_update_type}" if dep_update_type
-          normalized_types = allowed_update_types.filter_map { |t| t.is_a?(String) ? t.downcase.strip : nil }
-          next false if config_type && !normalized_types.include?(config_type)
-        end
```
Comment (v-kbukum1) [inline updater/lib/dependabot/job.rb:334]: **Review Tip**: For allow update types we need previous and current versions to ignore updates that are not allowed for the dependency name or dependency-type. We can only apply this in post resolution to see if update is necessary or not. It is different then ignore conditions where we are adding range versions conditions and using this to filter out the other versions.

Comment (v-kbukum1) [reply updater/lib/dependabot/job.rb:334]: We moved the allow update-types check here https://github.com/dependabot/dependabot-core/pull/14598/changes#diff-34dc1223111daeab5d87bd29022531c9516f20494e99e1363ef537f6de549595R447

File: updater/spec/dependabot/job_spec.rb [hunk 2]
```diff
@@ -466,20 +470,7 @@
...
-          [
-            {
-              "dependency-name" => "business",
-              "update-types" => ["version-update:semver-minor"]
-            }
-          ]
-        end
-
-        it { is_expected.to be(true) }
-      end
```
Comment (v-kbukum1) [inline updater/spec/dependabot/job_spec.rb:480]: **Review tip**: All tests are moved in the new section, `ignore_conditions_for`

File: updater/spec/dependabot/job_spec.rb [hunk 3]
```diff
@@ -489,118 +480,7 @@
...
-        end
-
-        let(:allowed_updates) do
-          [
-            {
-              "dependency-name" => "business",
-              "update-types" => ["version-update:semver-minor"]
-            }
-          ]
-        end
```
Comment (v-kbukum1) [inline updater/spec/dependabot/job_spec.rb:601]: **Review tip**: All tests are moved in the new section, `ignore_conditions_for`

File: updater/spec/dependabot/job_spec.rb [hunk 4]
```diff
@@ -628,35 +508,7 @@
...
-          [
-            {
-              "dependency-name" => "business",
-              "update-types" => ["version-update:semver-patch"]
-            },
-            {
-              "dependency-name" => "business"
-            }
-          ]
-        end
```
Comment (v-kbukum1) [inline updater/spec/dependabot/job_spec.rb:657]: **Review tip**: All tests are moved in the new section, `ignore_conditions_for`

File: updater/lib/dependabot/job.rb [hunk 5]
```diff
@@ -485,6 +483,101 @@ def completely_ignored?(dependency)
...
+    sig { params(update: T::Hash[String, T.untyped], dependency: Dependabot::Dependency).returns(T::Boolean) }
+    def allow_rule_matches_dependency?(update, dependency)
+      condition_name = update.fetch("dependency-name", nil)
+      return false if condition_name && !name_match?(condition_name, dependency.name)
+
+      dep_type = update.fetch("dependency-type", nil)
+      return true if dep_type.nil? || dep_type == "all"
+
+      # Indirect deps don't match top-level type rules (matching allowed_update? behavior)
+      return false if dependency.requirements.none? && TOP_LEVEL_DEPENDENCY_TYPES.include?(dep_type)
```
[the remark this answers is not in the document]
Comment (v-kbukum1) [reply updater/lib/dependabot/job.rb:549]: False positive. If the only matching rule is `update-type: security`, the dep is already blocked by `allowed_update?` (requires `vulnerable?`) and never reaches `ignore_conditions_for`. If another non-security rule also matches and lacks `update-types`, `allow_rule_permits_all_types?` returns true and no filtering is applied. The union logic is correct.

File: updater/lib/dependabot/job.rb [hunk 6]
```diff
@@ -443,10 +435,16 @@ def security_advisories_for(dependency)
...
         dependency,
         security_updates_only: security_updates_only?
       )
+
+      # Supplement with implicit ignore ranges derived from allow update-types.
+      # allow update-types cannot be checked in allowed_update? because it runs
+      # pre-resolution when only the current version is known. Version ranges
+      # only need the current version — the same mechanism as ignore update-types.
+      conditions + ignored_versions_from_allowed_update_types(dependency)
     end
```
[the remark this answers is not in the document]
Comment (v-kbukum1) [reply updater/lib/dependabot/job.rb:448]: Valid observation but minor. `log_ignore_conditions_for` only logs raw `ignore_conditions` — this is pre-existing behavior and not specific to this change. Could be improved in a follow-up but not a bug.

File: updater/lib/dependabot/job.rb [hunk 7]
```diff
@@ -485,6 +483,101 @@ def completely_ignored?(dependency)
...
+        when Dependabot::Config::IgnoreCondition::PATCH_VERSION_TYPE
+          version.ignored_patch_versions
+        when Dependabot::Config::IgnoreCondition::MINOR_VERSION_TYPE
+          version.ignored_minor_versions
+        when Dependabot::Config::IgnoreCondition::MAJOR_VERSION_TYPE
+          version.ignored_major_versions
+        else
+          []
+        end
+      end.compact
```
[the remark this answers is not in the document]
Comment (v-kbukum1) [reply updater/lib/dependabot/job.rb:512]: The suggested code is incorrect — `IgnoreCondition.new` does not accept `source` or `version` params, and `ignored_versions` takes `(dependency, security_updates_only)` not `(version)`. A correct version could use `IgnoreCondition.new(dependency_name: dependency.name, update_types: disallowed_types).ignored_versions(dependency, false)`, but line 43 of `ignore_condition.rb` returns `[ALL_VERSIONS]` when both `versions` and `update_types` are empty — so if `disallowed_types` is empty it would block everything. The current explicit `case` is safer and clearer.

File: updater/lib/dependabot/updater/update_type_helper.rb [hunk 8]
```diff
@@ -119,6 +138,12 @@ def update_type_for_dependency(dep)
         prev_ver, curr_ver = versions
         classify_semver_update(prev_ver, curr_ver)
       end
+
+      # Maps a semver label ("major", "minor", "patch") to the full config update-type string
+      sig { params(label: String).returns(T.nilable(String)) }
+      def semver_label_to_update_type(label)
```
Comment (v-abhishekbhaskar) [inline updater/lib/dependabot/updater/update_type_helper.rb]: Is this function being called anywhere? If not, can we remove it?

File: updater/lib/dependabot/job.rb [hunk 9]
```diff
@@ -485,6 +483,100 @@ def completely_ignored?(dependency)
...
+    # For example, if allow says only "semver-patch", this computes ignore ranges for
+    # major and minor — using the same mechanism as IgnoreCondition#versions_by_type.
+    sig { params(dependency: Dependabot::Dependency).returns(T::Array[String]) }
+    def ignored_versions_from_allowed_update_types(dependency)
+      return [] if security_updates_only?
+
+      permitted_types = collect_permitted_update_types(dependency)
+      return [] if permitted_types.empty?
+
+      disallowed_types = Dependabot::Updater::UpdateTypeHelper::ALL_SEMVER_UPDATE_TYPES - permitted_types
```
[the remark this answers is not in the document]
Comment (v-abhishekbhaskar) [reply updater/lib/dependabot/job.rb:496]: This seems to be a valid suggestion.

File: updater/lib/dependabot/updater/update_type_helper.rb (hunk 8 above)
Comment (v-kbukum1) [reply updater/lib/dependabot/updater/update_type_helper.rb]: Good catch! Removed both the method and the SEMVER_LABEL_TO_UPDATE_TYPE map (which was only used to derive ALL_SEMVER_UPDATE_TYPES). I think I did a few changes and I did forget that this is not used anymore
