### PR TITLE
cargo: strip credential-provider from .cargo/config.toml via TOML parsing

### LINKED ISSUE #14354: Cargo: no token found for Artifactory
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Cargo

### Package manager version

Cargo 1.90.0

### Language version

Rust 1.90.0

### Manifest location and content before the Dependabot update

Private repo.  This is a redacted .cargo/config.toml:

```toml
[registries.artifactory]
index = "sparse+https://example.com/api/cargo/cargo-local/index/"
credential-provider = "cargo:token"

[registries.artifactory-remote]
index = "sparse+https://example.com/api/cargo/cargo-crates-remote/index/"
credential-provider = "cargo:token"

# Add these 2 sections for resolving dependencies from Artifactory
[source.artifactory-remote]
registry = "sparse+https://example.com/api/cargo/cargo-crates-remote/index/"

[source.crates-io]
replace-with = "artifactory-remote"

[net]
git-fetch-with-cli = true
```

### dependabot.yml content

Private repo.  Similarly redacted .github/dependabot.yml:

```yaml
version: 2
registries:
  artifactory:
    type: cargo-registry
    registry: artifactory
    url: https://example.com/api/cargo/cargo-local/index/
    token: "Bearer ${{ secrets.CARGO_TOKEN }}"
  artifactory-remote:
    type: cargo-registry
    registry: artifactory-remote
    url: https://example.com/api/cargo/cargo-crates-remote/index/
    token: "Bearer ${{ secrets.CARGO_TOKEN }}"
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - artifactory
      - artifactory-remote
```

### Updated dependency

Among others:

    Updating anyhow v1.0.101 -> v1.0.102

### What you expected to see, versus what you actually saw

Expected: a successful Dependabot run on GitHub with several PRs opened.

Received: a failed run with the following log:

```
Updating `artifactory-remote` index
note: name of alternative registry `sparse+https://example.com/api/cargo/cargo-crates-remote/index/` set to `artifactory-remote`
  Credential cargo:token get artifactory-remote
error: failed to get `anyhow` as a dependency of package `my-private-app v0.1.0 (dependabot_tmp_dir)`

Caused by:
  failed to query replaced source registry `crates-io`

Caused by:
  no token found for `artifactory-remote`
  consider setting up an alternate registry in Cargo's configuration
  as described by https://doc.rust-lang.org/cargo/reference/registries.html

  [registries]
  my-registry = { index = "sparse+https://example.com/api/cargo/cargo-crates-remote/index/" }

[Troubleshoot Dependabot errors](https://docs.github.com/github/managing-security-vulnerabilities/troubleshooting-dependabot-errors)
```

- Started failing this way between January 28 and February 3.
- Still failing this way after #14030 
- Probable duplicate of #14094

### Native package manager behavior

Succeeds:

```
    Updating `artifactory-remote` index
    Updating `artifactory` index
     Locking 28 packages to latest Rust 1.90.0 compatible versions
    Updating anyhow v1.0.101 -> v1.0.102
    ...
```

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

_No response_

### PR DESCRIPTION
**Pull request by jeffwidman**
## Problem

PR #14340 set `CARGO_REGISTRY_GLOBAL_CREDENTIAL_PROVIDERS` to an empty string to disable Cargo's credential lookup globally. However, per-registry `credential-provider` settings in `.cargo/config.toml` override the global env var:

```toml
[registries.artifactory]
credential-provider = "cargo:token"
```

Cargo then tries to look up tokens locally and fails with `no token found`.

## Solution

Parse `.cargo/config.toml` with TomlRB and remove `credential-provider` keys from both per-registry (`[registries.*]`) and global (`[registry]`) sections before writing the config to the temporary working directory.

Combined with the existing `CARGO_REGISTRY_GLOBAL_CREDENTIAL_PROVIDERS=""` from #14340, this ensures Cargo never tries to authenticate on its own. All HTTP requests go through the dependabot proxy unauthenticated, and the proxy injects the real credentials transparently.

### Why this works

Dependabot always proxies all Cargo HTTP traffic. The proxy intercepts requests and injects the real registry credentials. Cargo itself never needs to authenticate — it just needs to *not try* to look up tokens. This PR + #14340 together ensure that:

1. **Global providers disabled** (via `CARGO_REGISTRY_GLOBAL_CREDENTIAL_PROVIDERS=""`) — #14340
2. **Per-registry providers removed** (via TOML parsing in this PR)

### Approach

Uses TomlRB to properly parse and rewrite the config rather than regex, avoiding edge cases with TOML formatting. Falls back to the original content if parsing fails.

### See also

- Comparison PRs exploring alternative approaches: #14356, #14357, #14358

Fixes #14354
Related: #14030, #14094

### CODE REVIEW

File: cargo/lib/dependabot/cargo/helpers.rb [hunk 1]
```diff
@@ -16,6 +18,39 @@ def self.bypass_cargo_credential_providers
...
+            case registry_config
+            when Hash
+              registry_config.delete("credential-provider")
+            end
+          end
+        end
+
+        # Also strip global credential-provider if set under [registry]
+        registry = T.let(parsed["registry"], T.nilable(T::Hash[String, T.untyped]))
+        registry&.delete("credential-provider")
```
[the remark this answers is not in the document]
Comment (jeffwidman) [reply cargo/lib/dependabot/cargo/helpers.rb]: Good catch. I broadened the rescue to `StandardError` so that unexpected structure (e.g. `registries = "foo"`) raising `TypeError` from `T.let` casts or `NoMethodError` from method calls on non-Hash values is also handled. This keeps the Sorbet `typed: strong` annotations while ensuring the method never crashes the update process.

File: cargo/lib/dependabot/cargo/helpers.rb [hunk 2]
```diff
@@ -1,21 +1,61 @@
-# typed: strong
+# typed: strict
```
Comment (jeffwidman) [inline cargo/lib/dependabot/cargo/helpers.rb:1]: This had to be dropped down a level because the TOML format is untyped since it's user input... all the `is_a()` calls don't work with `strong`

File: cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb [hunk 3]
```diff
@@ -307,7 +307,7 @@ def write_temporary_dependency_files
           return unless config
 
           FileUtils.mkdir_p(File.dirname(T.must(config).name))
-          File.write(T.must(config).name, T.must(config).content)
+          File.write(T.must(config).name, Helpers.sanitize_cargo_config(T.must(T.must(config).content)))
```
Comment (v-kbukum1) [inline cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb]: Instead of `T.must`  I think it may be better to have something like the following? What do you think?

configContent = config.content
return unless config && configContent

Comment (jeffwidman) [reply cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb]: Good suggestion. I replaced the `T.must(T.must(config).content)` with local variable extraction and early returns:

```ruby
config_file = config
return unless config_file

config_content = config_file.content
return unless config_content

FileUtils.mkdir_p(File.dirname(config_file.name))
File.write(config_file.name, Helpers.sanitize_cargo_config(config_content))
```

Note: used `config_file = config` as a local variable because Sorbet can't flow-narrow `T.nilable` instance method return values after `return unless` — it only narrows local variables.

Comment (v-kbukum1) [reply cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb]: Yes. That sounds better now.

**Review by kbukum1 — DISMISSED** [review]

File: cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb [hunk 4]
```diff
@@ -304,10 +304,11 @@ def write_temporary_dependency_files
 
           File.write(lockfile.name, lockfile.content)
           File.write(T.must(toolchain).name, T.must(toolchain).content) if toolchain
-          return unless config
+          config_file = config
```
Comment (jeffwidman) [inline cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb:307]: This is Sorbet variable narrowing... so that we don't have to have another `T.must()` call... this is arguably more readable.

File: cargo/lib/dependabot/cargo/helpers.rb [hunk 5]
```diff
@@ -1,21 +1,61 @@
...
+        # from CI may have this set. It's a per-registry override that takes precedence over the global env var,
+        # so we need to remove it to prevent Cargo from trying to look up a token.
+        registry = parsed["registry"]
+        registry.delete("credential-provider") if registry.is_a?(Hash)
+
+        TomlRB.dump(parsed)
+      rescue TomlRB::ParseError => e
+        # If the TOML is malformed, Cargo itself would also fail to parse it, so falling back to the original
+        # content is safe — Cargo will produce its own error.
+        Dependabot.logger.warn("Failed to parse .cargo/config.toml, skipping credential-provider removal: #{e.message}")
```
[the remark this answers is not in the document]
Comment (jeffwidman) [reply cargo/lib/dependabot/cargo/helpers.rb]: Good catch — `TomlRB::ValueOverwriteError` (duplicate keys) is a real case. I widened the rescue to `TomlRB::Error`, which is the common parent of both `ParseError` and `ValueOverwriteError`. This catches all TomlRB processing failures without going as broad as `StandardError` (which would mask genuine bugs in our code).

File: cargo/lib/dependabot/cargo/helpers.rb [hunk 6]
```diff
@@ -1,21 +1,61 @@
...
+
+        # Also strip credential-provider from [registry] (crates.io default registry). Users who `cargo publish`
+        # from CI may have this set. It's a per-registry override that takes precedence over the global env var,
+        # so we need to remove it to prevent Cargo from trying to look up a token.
+        registry = parsed["registry"]
+        registry.delete("credential-provider") if registry.is_a?(Hash)
+
+        TomlRB.dump(parsed)
+      rescue TomlRB::Error => e
+        raise Dependabot::DependencyFileNotParseable.new(
```
Comment (jeffwidman) [inline cargo/lib/dependabot/cargo/helpers.rb:54]: This is a well-known error that we display to users so that if they hit problems, they can hopefully self-diagnose.
