### PR TITLE
Fix upgrades when docker registry API does not provide digests

### LINKED ISSUE #6612: Dependabot doesn't recognize updated Docker images.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Docker

### Package manager version

No response

### Language version

_No response_

### Manifest location and content before the Dependabot update

/bundle.Dockerfile
/oauth.Dockerfile

### dependabot.yml content
```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: daily
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
```
### Updated dependency

from registry.access.redhat.com/ubi8/ubi-minimal:8.7-923.1669829893
to registry.access.redhat.com/ubi8/ubi-minimal:8.7-1049

### What you expected to see, versus what you actually saw

Expect - registry.access.redhat.com/ubi8/ubi-minimal:8.7-1049
SAW- no updates

### Native package manager behavior

No response

### Images of the diff or a link to the PR, issue, or logs

No response

### Smallest manifest that reproduces the issue
```
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.7-923.1669829893 as spi-oauth
```

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Some Docker registry API implementations don't provide a "content digest" header. For example, `https://registry.access.redhat.com/v2`.

In this case, we would incorrectly miss updates because the digests for any two images would be considered equal (`nil == nil`), and that would trigger our logic to not update to latest since we assumed it was actually the same version, just a change in version precision.

This PR should fix the problem.

Closes #6612.

### CODE REVIEW

File: docker/lib/dependabot/docker/update_checker.rb [hunk 1]
```diff
@@ -152,17 +156,21 @@ def fetch_latest_version(version)
         candidate_tags = sort_tags(candidate_tags, version)
 
         latest_tag = candidate_tags.last
+        return version unless latest_tag
```
Comment (mctofu) [inline docker/lib/dependabot/docker/update_checker.rb:159]: ⚡ Nice improvement to this section!

**Review by mctofu — APPROVED** [review]

File: docker/lib/dependabot/docker/update_checker.rb (hunk 1 above)
Comment (deivid-rodriguez) [reply docker/lib/dependabot/docker/update_checker.rb:159]: Thank you! :)

**Comment by jeffwidman** [comment]
Related discussion in:
* https://github.com/dependabot/dependabot-core/pull/6748

Redhat is planning to provide digests in the not too distant future... although other registries may still have this behavior.
