### PR TITLE
Honor NuGet.config sources and search all build files for properties

### LINKED ISSUE #8470: Latest release not respecting nuget.config sources and not resolving variables correctly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Package manager version

_No response_

### Language version

_No response_

### Manifest location and content before the Dependabot update

_No response_

### dependabot.yml content

version: 2
registries:
  nuget-feed-pkgs-dev-azure-com-redactedorgname-packaging-artifactrep:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/RedactedOrgName/_packaging/ArtifactRepository/nuget/v3/index.json
    username: "${{secrets.NUGET_FEED_PKGS_DEV_AZURE_COM_PACKAGING_ARTIFACTREP_USERNAME}}"
    password: "${{secrets.NUGET_FEED_PKGS_DEV_AZURE_COM_PACKAGING_ARTIFACTREP_PASSWORD}}"

updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "dependencies"
  open-pull-requests-limit: 25
  rebase-strategy: disabled
  registries:
    - nuget-feed-pkgs-dev-azure-com-redactedorgname-packaging-artifactrep

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

The repository also includes the NuGet.config as such (renamed accordingly the org part in all files on the issue):
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="Azure" value="https://pkgs.dev.azure.com/RedactedOrgName/_packaging/ArtifactRepository/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

3 days ago (on 24 November 2023) the output of one of the dependency checks, for example Newtonsoft.Json was correctly:
```
updater | 2023/11/24 19:26:27 INFO <job_754141353> Checking if Newtonsoft.Json 13.0.3 needs updating
  proxy | 2023/11/24 19:26:27 [376] GET https://pkgs.dev.azure.com:443/RedactedOrgName/_packaging/ArtifactRepository/nuget/v3/index.json
  proxy | 2023/11/24 19:26:27 [376] * authenticating nuget feed request (host: pkgs.dev.azure.com, basic auth)
  proxy | 2023/11/24 19:26:27 [376] 200 https://pkgs.dev.azure.com:443/RedactedOrgName/_packaging/ArtifactRepository/nuget/v3/index.json
  proxy | 2023/11/24 19:26:28 [378] GET https://pkgs.dev.azure.com:443/RedactedOrgName/_packaging/d8b4d1eb-aeb3-4b5b-9b43-37b4fc985e2f/nuget/v3/flat2/newtonsoft.json/index.json
  proxy | 2023/11/24 19:26:28 [378] * authenticating nuget feed request (host: pkgs.dev.azure.com, basic auth)
  proxy | 2023/11/24 19:26:28 [378] 200 https://pkgs.dev.azure.com:443/RedactedOrgName/_packaging/d8b4d1eb-aeb3-4b5b-9b43-37b4fc985e2f/nuget/v3/flat2/newtonsoft.json/index.json
updater | 2023/11/24 19:26:28 INFO <job_754141353> Latest version is 13.0.3
updater | 2023/11/24 19:26:28 INFO <job_754141353> No update needed for Newtonsoft.Json 13.0.3
updater | 2023/11/24 19:26:28 INFO <job_754141353> Finished job processing
```

Now today (on 27 November 2023) the output is:
```
updater | 2023/11/27 17:28:47 INFO <job_754874199> Checking if Newtonsoft.Json $NewtonsoftJsonVersion needs updating
  proxy | 2023/11/27 17:28:47 [878] GET https://pkgs.dev.azure.com:443/RedactedOrgName/_packaging/ArtifactRepository/nuget/v3/index.json
  proxy | 2023/11/27 17:28:47 [878] * authenticating nuget feed request (host: pkgs.dev.azure.com, basic auth)
  proxy | 2023/11/27 17:28:47 [878] 200 https://pkgs.dev.azure.com:443/RedactedOrgName/_packaging/ArtifactRepository/nuget/v3/index.json
  proxy | 2023/11/27 17:28:47 [880] GET https://pkgs.dev.azure.com:443/RedactedOrgName/_packaging/d8b4d1eb-aeb3-4b5b-9b43-37b4fc985e2f/nuget/v3/flat2/newtonsoft.json/index.json
  proxy | 2023/11/27 17:28:47 [880] * authenticating nuget feed request (host: pkgs.dev.azure.com, basic auth)
  proxy | 2023/11/27 17:28:48 [880] 200 https://pkgs.dev.azure.com:443/RedactedOrgName/_packaging/d8b4d1eb-aeb3-4b5b-9b43-37b4fc985e2f/nuget/v3/flat2/newtonsoft.json/index.json
  proxy | 2023/11/27 17:28:48 [882] GET https://api.nuget.org:443/v3-flatcontainer/newtonsoft.json/$NewtonsoftJsonVersion/newtonsoft.json.nuspec
  proxy | 2023/11/27 17:28:48 [882] 404 https://api.nuget.org:443/v3-flatcontainer/newtonsoft.json/$NewtonsoftJsonVersion/newtonsoft.json.nuspec
  proxy | 2023/11/27 17:28:48 [884] GET https://pkgs.dev.azure.com:443/RedactedOrgName/_apis/packaging/feeds/ArtifactRepository/nuget/packages/Newtonsoft.Json/versions/$NewtonsoftJsonVersion/content?sourceProtocolVersion=nuget&api-version=7.0-preview
  proxy | 2023/11/27 17:28:48 [884] 401 https://pkgs.dev.azure.com:443/RedactedOrgName/_apis/packaging/feeds/ArtifactRepository/nuget/packages/Newtonsoft.Json/versions/$NewtonsoftJsonVersion/content?sourceProtocolVersion=nuget&api-version=7.0-preview
  proxy | 2023/11/27 17:28:48 [884] Remote response: {"$id":"1","innerException":null,"message":"TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
updater | 2023/11/27 17:28:48 INFO <job_754874199> Latest version is 13.0.3
updater | 2023/11/27 17:28:48 INFO <job_754874199> No update needed for Newtonsoft.Json $NewtonsoftJsonVersion
```

So it not only is not able to search for the correct version numbers that are defined in Directory.Build.prop files in the root of the repository, but it is also completely ignoring the </ clear> instruction on the nuget sources, making it search directly on nuget.org.

image

This is specially bad on private nugets that are only available on the private source, leaking information on requests to nuget.org and bypassing any gatekeeping of versions that may exist on the private source.

It also has the side effect of having closed all the PR's that already existed for libraries in this situation (at least for the private artifacts, not sure why it did not do the same for libraries that were also available on nuget.org, probably it did not close the ones that were not using Variables to define the versions, but all my private ones have that pattern):
image

Id's of the version update operations
 - Working: 754141353
 - Not Working: 754874199

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

_No response_

### PR DESCRIPTION
**Pull request by brettfo**
Fixes #8470 (2 issues)

1. `api.nuget.org` was always queried, even if not listed in the `NuGet.Config` file; this simply removes that and also adds a test to ensure it's not hit.
2. When searching `Directory.Build.props/.targets`, only the first found file was considered; instead, _all_ files up to the root of the repo need to be searched for the specified properties.

### CODE REVIEW

**Review by jakecoffman — APPROVED** [review]

File: nuget/lib/dependabot/nuget/file_fetcher.rb [hunk 1]
```diff
@@ -42,7 +43,10 @@ def fetch_files
         fetched_files << dotnet_tools_json if dotnet_tools_json
         fetched_files << packages_props if packages_props
 
-        fetched_files = fetched_files.uniq
+        # dedup files based on their absolute path
+        fetched_files = fetched_files.uniq do |fetched_file|
+          Pathname.new(File.join(fetched_file.directory, fetched_file.name)).cleanpath.to_path
+        end
```
Comment (deivid-rodriguez) [inline nuget/lib/dependabot/nuget/file_fetcher.rb:49]: Nice simplification to dedupe just once, and correctly!

File: nuget/lib/dependabot/nuget/file_fetcher.rb [hunk 2]
```diff
@@ -124,36 +122,29 @@ def fetch_directory_build_files
...
           possible_dirs.each do |possible_dir|
             break if attempted_dirs.include?(possible_dir)
 
             attempted_dirs << possible_dir
-            file = repo_contents(dir: possible_dir).find { |f| possible_build_file_paths.include?(f.name) }
-            directory_build_files << fetch_file_from_host(File.join(possible_dir, file.name)) if file
+            build_files = repo_contents(dir: possible_dir).select { |f| f.name.match?(BUILD_FILE_NAMES) }
+            directory_build_files += build_files.map do |file|
+              possible_file = File.join(possible_dir, file.name)
+              possible_file = possible_file[1..-1] if possible_file.start_with?("/") # remove leading slash
```
Comment (deivid-rodriguez) [inline nuget/lib/dependabot/nuget/file_fetcher.rb:139]: `possible_file.delete_prefix("/")` is probably a bit more clear, and it self explains so you can remove the comment.

File: nuget/lib/dependabot/nuget/file_fetcher.rb [hunk 3]
```diff
@@ -187,35 +178,23 @@ def sln_files
...
+        @fsproj_file ||= find_and_fetch_with_suffix(".fsproj")
       end
 
       def directory_packages_props_file
-        @directory_packages_props_file ||=
-          begin
-            file = repo_contents.find { |f| f.name.casecmp?("directory.packages.props") }
-            fetch_file_from_host(file.name) if file
-          end
+        @directory_packages_props_file ||= repo_contents.find { |f| f.name.casecmp("Directory.Packages.props").zero? }
```
Comment (deivid-rodriguez) [inline nuget/lib/dependabot/nuget/file_fetcher.rb:193]: Why moving away from `casecmp?`?

File: nuget/lib/dependabot/nuget/file_fetcher.rb [hunk 4]
```diff
@@ -187,35 +178,23 @@ def sln_files
...
+      end
+
+      def find_and_fetch_with_suffix(suffix)
+        repo_contents.select { |f| f.name.end_with?(suffix) }.map { |f| fetch_file_from_host(f.name) }
```
Comment (deivid-rodriguez) [inline nuget/lib/dependabot/nuget/file_fetcher.rb:197]: I guess this is the key part, going from `find` to `select`?

**Review by deivid-rodriguez — APPROVED** [review]
I left a few minor comments, but looks great, and no merge blockers!

Nice work on both the fix and the thorough tests!

**Comment by jakecoffman** [comment]
This is deployed now.

File: nuget/lib/dependabot/nuget/file_fetcher.rb (hunk 4 above)
Comment (brettfo) [reply nuget/lib/dependabot/nuget/file_fetcher.rb:197]: Correct; instead of only reporting the first file up the chain, we need all of them because the property declaration might be several directories up with multiple intervening `Directory.Build.*` files.

File: nuget/lib/dependabot/nuget/file_fetcher.rb (hunk 2 above)
Comment (brettfo) [reply nuget/lib/dependabot/nuget/file_fetcher.rb:139]: My lack of Ruby experience is showing :)

**Comment by deivid-rodriguez** [comment]
If you think they are good suggestions, yes!
