### PR TITLE
Fix GitHub actions updater crashing and cloning the wrong repository

### LINKED ISSUE #6014: SHA pinned Action being downgraded
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

GitHub Actions

### Package manager version

_No response_

### Language version

_No response_

### Manifest location and content before the Dependabot update

_No response_

### dependabot.yml content

https://github.com/twpayne/chezmoi/blob/4748397a0341cd5f6500880ede84fb3b5225d626/.github/dependabot.yml

### Updated dependency

[cpina/github-action-push-to-another-repository](https://github.com/cpina/github-action-push-to-another-repository) from [`9e487f29582587eeb4837c0552c886bb0644b6b9`](https://github.com/cpina/github-action-push-to-another-repository/commit/9e487f29582587eeb4837c0552c886bb0644b6b9) (2022-09-26T22:44:58Z) to [`940a2857e598a6392bd336330b07416c1ae8ea1f`](https://github.com/cpina/github-action-push-to-another-repository/commit/940a2857e598a6392bd336330b07416c1ae8ea1f) (2021-04-29T21:45:48Z)

### What you expected to see, versus what you actually saw

I expect that no PR is created, given that this is a downgrade.

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

https://github.com/twpayne/chezmoi/pull/2466

https://github.com/twpayne/chezmoi/pull/2527

https://github.com/twpayne/chezmoi/pull/2534

Comparison from the PRs: https://github.com/cpina/github-action-push-to-another-repository/compare/9e487f29582587eeb4837c0552c886bb0644b6b9...940a2857e598a6392bd336330b07416c1ae8ea1f

<details>
<summary>Recent log</summary>

```
  proxy | time="2022-11-01T02:02:10Z" level=info msg="proxy starting" commit=4216c65543e4c05c0989a39f3c0f0b9928f1e5ff
  proxy | 2022/11/01 02:02:10 Listening (:1080)
updater | 2022-11-01T02:02:10.990118655 [496455577:main:WARN:src/devices/src/legacy/serial.rs:214] Detached the serial input due to peer close/error.
updater | time="2022-11-01T02:02:12Z" level=info msg="guest starting" commit=fac0bde928572a22321d745959ee472b2619a5a4
updater | time="2022-11-01T02:02:12Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=496455577 updater_timeout=45m0s updater_version=25088f4469644ccae1ae92fd4df7dcb09869d277
updater | I, [2022-11-01T02:02:14.188937 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
updater | INFO <job_496455577> Starting job processing
  proxy | 2022/11/01 02:02:16 [002] GET https://github.com:443/twpayne/chezmoi/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:16 [002] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:16 [002] 200 https://github.com:443/twpayne/chezmoi/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:16 [004] POST https://github.com:443/twpayne/chezmoi/git-upload-pack
  proxy | 2022/11/01 02:02:16 [004] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:16 [004] 200 https://github.com:443/twpayne/chezmoi/git-upload-pack
  proxy | 2022/11/01 02:02:16 [006] POST https://github.com:443/twpayne/chezmoi/git-upload-pack
  proxy | 2022/11/01 02:02:16 [006] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:16 [006] 200 https://github.com:443/twpayne/chezmoi/git-upload-pack
updater | INFO <job_496455577> Finished job processing
updater | time="2022-11-01T02:02:17Z" level=info msg="task complete" container_id=job-496455577-file-fetcher exit_code=0 job_id=496455577 step=fetcher
updater | I, [2022-11-01T02:02:18.109316 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
updater | INFO <job_496455577> Starting job processing
updater | INFO <job_496455577> Starting update job for twpayne/chezmoi
  proxy | 2022/11/01 02:02:19 [008] GET https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:19 [008] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:19 [008] 200 https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:19 [010] GET https://github.com:443/actions/setup-go.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:19 [010] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:20 [010] 200 https://github.com:443/actions/setup-go.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:20 [012] GET https://github.com:443/dorny/paths-filter.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:20 [012] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:20 [012] 200 https://github.com:443/dorny/paths-filter.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:20 [014] GET https://github.com:443/github/codeql-action.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:20 [014] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:20 [014] 200 https://github.com:443/github/codeql-action.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:20 [016] GET https://github.com:443/reviewdog/action-misspell.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:20 [016] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:20 [016] 200 https://github.com:443/reviewdog/action-misspell.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:20 [018] GET https://github.com:443/actions/cache.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:20 [018] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:20 [018] 200 https://github.com:443/actions/cache.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:20 [020] GET https://github.com:443/goreleaser/goreleaser-action.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:20 [020] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:20 [020] 200 https://github.com:443/goreleaser/goreleaser-action.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:20 [022] GET https://github.com:443/actions/upload-artifact.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:20 [022] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:20 [022] 200 https://github.com:443/actions/upload-artifact.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:20 [024] GET https://github.com:443/ludeeus/action-shellcheck.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:20 [024] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:20 [024] 200 https://github.com:443/ludeeus/action-shellcheck.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:20 [026] GET https://github.com:443/golangci/golangci-lint-action.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:20 [026] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:20 [026] 200 https://github.com:443/golangci/golangci-lint-action.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:21 [028] GET https://github.com:443/sigstore/cosign-installer.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:21 [028] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:21 [028] 200 https://github.com:443/sigstore/cosign-installer.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:21 [030] GET https://github.com:443/cpina/github-action-push-to-another-repository.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:21 [030] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:21 [030] 200 https://github.com:443/cpina/github-action-push-to-another-repository.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:21 [032] GET https://github.com:443/dessant/lock-threads.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:21 [032] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:21 [032] 200 https://github.com:443/dessant/lock-threads.git/info/refs?service=git-upload-pack
updater | INFO <job_496455577> Checking if golangci/golangci-lint-action 3.2.0 needs updating
  proxy | 2022/11/01 02:02:21 [036] GET https://github.com:443/golangci/golangci-lint-action.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:21 [036] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:21 [036] 200 https://github.com:443/golangci/golangci-lint-action.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:21 [038] GET https://github.com:443/golangci/golangci-lint-action.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:21 [038] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:21 [038] 200 https://github.com:443/golangci/golangci-lint-action.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:22 [040] GET https://api.github.com:443/repos/golangci/golangci-lint-action/compare/v3.3.0...537aa1903e5d359d0b27dbc19ddd22c5087f3fbc
  proxy | 2022/11/01 02:02:22 [040] * authenticating github api request
  proxy | 2022/11/01 02:02:25 [040] 200 https://api.github.com:443/repos/golangci/golangci-lint-action/compare/v3.3.0...537aa1903e5d359d0b27dbc19ddd22c5087f3fbc
updater | INFO <job_496455577> Latest version is 3.3.0
updater | INFO <job_496455577> Pull request already exists for golangci/golangci-lint-action with latest version 3.3.0
updater | INFO <job_496455577> Checking if cpina/github-action-push-to-another-repository  needs updating
  proxy | 2022/11/01 02:02:25 [042] GET https://github.com:443/cpina/github-action-push-to-another-repository.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:25 [042] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:25 [042] 200 https://github.com:443/cpina/github-action-push-to-another-repository.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:25 [044] GET https://github.com:443/cpina/github-action-push-to-another-repository.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:25 [044] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:25 [044] 200 https://github.com:443/cpina/github-action-push-to-another-repository.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:25 [046] GET https://api.github.com:443/repos/cpina/github-action-push-to-another-repository/compare/v1.5.1...9e487f29582587eeb4837c0552c886bb0644b6b9
  proxy | 2022/11/01 02:02:25 [046] * authenticating github api request
  proxy | 2022/11/01 02:02:25 [046] 200 https://api.github.com:443/repos/cpina/github-action-push-to-another-repository/compare/v1.5.1...9e487f29582587eeb4837c0552c886bb0644b6b9
  proxy | 2022/11/01 02:02:25 [048] GET https://api.github.com:443/repos/cpina/github-action-push-to-another-repository/compare/v1.5.1...9e487f29582587eeb4837c0552c886bb0644b6b9
  proxy | 2022/11/01 02:02:25 [048] * authenticating github api request
  proxy | 2022/11/01 02:02:26 [048] 200 https://api.github.com:443/repos/cpina/github-action-push-to-another-repository/compare/v1.5.1...9e487f29582587eeb4837c0552c886bb0644b6b9
  proxy | 2022/11/01 02:02:26 [050] GET https://github.com:443/twpayne/chezmoi/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:26 [050] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:26 [050] 200 https://github.com:443/twpayne/chezmoi/info/refs?service=git-upload-pack
updater | INFO <job_496455577> Latest version is 940a2857e598a6392bd336330b07416c1ae8ea1f
  proxy | 2022/11/01 02:02:26 [052] GET https://api.github.com:443/repos/cpina/github-action-push-to-another-repository/compare/v1.5.1...9e487f29582587eeb4837c0552c886bb0644b6b9
  proxy | 2022/11/01 02:02:26 [052] * authenticating github api request
  proxy | 2022/11/01 02:02:26 [052] 200 https://api.github.com:443/repos/cpina/github-action-push-to-another-repository/compare/v1.5.1...9e487f29582587eeb4837c0552c886bb0644b6b9
  proxy | 2022/11/01 02:02:26 [054] GET https://api.github.com:443/repos/cpina/github-action-push-to-another-repository/compare/v1.5.1...9e487f29582587eeb4837c0552c886bb0644b6b9
  proxy | 2022/11/01 02:02:26 [054] * authenticating github api request
  proxy | 2022/11/01 02:02:26 [054] 200 https://api.github.com:443/repos/cpina/github-action-push-to-another-repository/compare/v1.5.1...9e487f29582587eeb4837c0552c886bb0644b6b9
updater | INFO <job_496455577> Pull request already exists for cpina/github-action-push-to-another-repository with latest version 940a2857e598a6392bd336330b07416c1ae8ea1f
updater | INFO <job_496455577> Checking if actions/upload-artifact 3.1.1 needs updating
  proxy | 2022/11/01 02:02:26 [056] GET https://github.com:443/actions/upload-artifact.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:26 [056] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:26 [056] 200 https://github.com:443/actions/upload-artifact.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:26 [058] GET https://github.com:443/actions/upload-artifact.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:26 [058] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:26 [058] 200 https://github.com:443/actions/upload-artifact.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:26 [060] GET https://api.github.com:443/repos/actions/upload-artifact/compare/v3.1.1...83fd05a356d7e2593de66fc9913b3002723633cb
  proxy | 2022/11/01 02:02:26 [060] * authenticating github api request
  proxy | 2022/11/01 02:02:26 [060] 200 https://api.github.com:443/repos/actions/upload-artifact/compare/v3.1.1...83fd05a356d7e2593de66fc9913b3002723633cb
updater | INFO <job_496455577> Latest version is 3.1.1
updater | INFO <job_496455577> No update needed for actions/upload-artifact 3.1.1
updater | INFO <job_496455577> Checking if actions/setup-go 3.3.1 needs updating
  proxy | 2022/11/01 02:02:26 [062] GET https://github.com:443/actions/setup-go.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:26 [062] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:26 [062] 200 https://github.com:443/actions/setup-go.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:26 [064] GET https://github.com:443/actions/setup-go.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:26 [064] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:27 [064] 200 https://github.com:443/actions/setup-go.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:27 [066] GET https://api.github.com:443/repos/actions/setup-go/compare/v3.3.1...c4a742cab115ed795e34d4513e2cf7d472deb55f
  proxy | 2022/11/01 02:02:27 [066] * authenticating github api request
  proxy | 2022/11/01 02:02:27 [066] 200 https://api.github.com:443/repos/actions/setup-go/compare/v3.3.1...c4a742cab115ed795e34d4513e2cf7d472deb55f
updater | INFO <job_496455577> Latest version is 3.3.1
updater | INFO <job_496455577> No update needed for actions/setup-go 3.3.1
updater | INFO <job_496455577> Checking if ludeeus/action-shellcheck 1.1.0 needs updating
  proxy | 2022/11/01 02:02:27 [068] GET https://github.com:443/ludeeus/action-shellcheck.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:27 [068] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:27 [068] 200 https://github.com:443/ludeeus/action-shellcheck.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:27 [070] GET https://github.com:443/ludeeus/action-shellcheck.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:27 [070] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:27 [070] 200 https://github.com:443/ludeeus/action-shellcheck.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:27 [072] GET https://api.github.com:443/repos/ludeeus/action-shellcheck/compare/1.1.0...94e0aab03ca135d11a35e5bfc14e6746dc56e7e9
  proxy | 2022/11/01 02:02:27 [072] * authenticating github api request
  proxy | 2022/11/01 02:02:27 [072] 200 https://api.github.com:443/repos/ludeeus/action-shellcheck/compare/1.1.0...94e0aab03ca135d11a35e5bfc14e6746dc56e7e9
updater | INFO <job_496455577> Latest version is 1.1.0
updater | INFO <job_496455577> No update needed for ludeeus/action-shellcheck 1.1.0
updater | INFO <job_496455577> Checking if sigstore/cosign-installer 2.8.1 needs updating
  proxy | 2022/11/01 02:02:27 [074] GET https://github.com:443/sigstore/cosign-installer.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:27 [074] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:27 [074] 200 https://github.com:443/sigstore/cosign-installer.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:27 [076] GET https://github.com:443/sigstore/cosign-installer.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:27 [076] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:27 [076] 200 https://github.com:443/sigstore/cosign-installer.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:27 [078] GET https://api.github.com:443/repos/sigstore/cosign-installer/compare/v2.8.1...9becc617647dfa20ae7b1151972e9b3a2c338a2b
  proxy | 2022/11/01 02:02:27 [078] * authenticating github api request
  proxy | 2022/11/01 02:02:27 [078] 200 https://api.github.com:443/repos/sigstore/cosign-installer/compare/v2.8.1...9becc617647dfa20ae7b1151972e9b3a2c338a2b
updater | INFO <job_496455577> Latest version is 2.8.1
updater | INFO <job_496455577> No update needed for sigstore/cosign-installer 2.8.1
updater | INFO <job_496455577> Checking if dessant/lock-threads 3.0.0 needs updating
  proxy | 2022/11/01 02:02:27 [080] GET https://github.com:443/dessant/lock-threads.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:27 [080] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:27 [080] 200 https://github.com:443/dessant/lock-threads.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:28 [082] GET https://github.com:443/dessant/lock-threads.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:28 [082] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:28 [082] 200 https://github.com:443/dessant/lock-threads.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:28 [084] GET https://api.github.com:443/repos/dessant/lock-threads/compare/v3.0.0...e460dfeb36e731f3aeb214be6b0c9a9d9a67eda6
  proxy | 2022/11/01 02:02:28 [084] * authenticating github api request
  proxy | 2022/11/01 02:02:28 [084] 200 https://api.github.com:443/repos/dessant/lock-threads/compare/v3.0.0...e460dfeb36e731f3aeb214be6b0c9a9d9a67eda6
updater | INFO <job_496455577> Latest version is 3.0.0
updater | INFO <job_496455577> No update needed for dessant/lock-threads 3.0.0
updater | INFO <job_496455577> Checking if dorny/paths-filter 2.11.1 needs updating
  proxy | 2022/11/01 02:02:28 [086] GET https://github.com:443/dorny/paths-filter.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:28 [086] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:28 [086] 200 https://github.com:443/dorny/paths-filter.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:28 [088] GET https://github.com:443/dorny/paths-filter.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:28 [088] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:28 [088] 200 https://github.com:443/dorny/paths-filter.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:28 [090] GET https://api.github.com:443/repos/dorny/paths-filter/compare/v2.11.1...4512585405083f25c027a35db413c2b3b9006d50
  proxy | 2022/11/01 02:02:28 [090] * authenticating github api request
  proxy | 2022/11/01 02:02:28 [090] 200 https://api.github.com:443/repos/dorny/paths-filter/compare/v2.11.1...4512585405083f25c027a35db413c2b3b9006d50
updater | INFO <job_496455577> Latest version is 2.11.1
updater | INFO <job_496455577> No update needed for dorny/paths-filter 2.11.1
updater | INFO <job_496455577> Checking if reviewdog/action-misspell 1.12.2 needs updating
  proxy | 2022/11/01 02:02:28 [092] GET https://github.com:443/reviewdog/action-misspell.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:28 [092] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:28 [092] 200 https://github.com:443/reviewdog/action-misspell.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:28 [094] GET https://github.com:443/reviewdog/action-misspell.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:28 [094] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:28 [094] 200 https://github.com:443/reviewdog/action-misspell.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:28 [096] GET https://api.github.com:443/repos/reviewdog/action-misspell/compare/v1.12.2...811b1e15f531430be3a5784e3d591bd657df18b0
  proxy | 2022/11/01 02:02:28 [096] * authenticating github api request
  proxy | 2022/11/01 02:02:28 [096] 200 https://api.github.com:443/repos/reviewdog/action-misspell/compare/v1.12.2...811b1e15f531430be3a5784e3d591bd657df18b0
updater | INFO <job_496455577> Latest version is 1.12.2
updater | INFO <job_496455577> No update needed for reviewdog/action-misspell 1.12.2
updater | INFO <job_496455577> Checking if goreleaser/goreleaser-action 3.2.0 needs updating
  proxy | 2022/11/01 02:02:28 [098] GET https://github.com:443/goreleaser/goreleaser-action.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:28 [098] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:29 [098] 200 https://github.com:443/goreleaser/goreleaser-action.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:29 [100] GET https://github.com:443/goreleaser/goreleaser-action.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:29 [100] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:29 [100] 200 https://github.com:443/goreleaser/goreleaser-action.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:29 [102] GET https://api.github.com:443/repos/goreleaser/goreleaser-action/compare/v3.2.0...b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757
  proxy | 2022/11/01 02:02:29 [102] * authenticating github api request
  proxy | 2022/11/01 02:02:29 [102] 200 https://api.github.com:443/repos/goreleaser/goreleaser-action/compare/v3.2.0...b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757
updater | INFO <job_496455577> Latest version is 3.2.0
updater | INFO <job_496455577> No update needed for goreleaser/goreleaser-action 3.2.0
updater | INFO <job_496455577> Checking if github/codeql-action 2.1.29 needs updating
  proxy | 2022/11/01 02:02:29 [104] GET https://github.com:443/github/codeql-action.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:29 [104] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:29 [104] 200 https://github.com:443/github/codeql-action.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:29 [106] GET https://github.com:443/github/codeql-action.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:29 [106] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:29 [106] 200 https://github.com:443/github/codeql-action.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:29 [108] GET https://api.github.com:443/repos/github/codeql-action/compare/v2.1.29...ec3cf9c605b848da5f1e41e8452719eb1ccfb9a6
  proxy | 2022/11/01 02:02:29 [108] * authenticating github api request
  proxy | 2022/11/01 02:02:29 [108] 200 https://api.github.com:443/repos/github/codeql-action/compare/v2.1.29...ec3cf9c605b848da5f1e41e8452719eb1ccfb9a6
updater | INFO <job_496455577> Latest version is 2.1.29
updater | INFO <job_496455577> No update needed for github/codeql-action 2.1.29
updater | INFO <job_496455577> Checking if actions/cache 3.0.11 needs updating
  proxy | 2022/11/01 02:02:29 [110] GET https://github.com:443/actions/cache.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:29 [110] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:29 [110] 200 https://github.com:443/actions/cache.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:29 [112] GET https://github.com:443/actions/cache.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:29 [112] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:30 [112] 200 https://github.com:443/actions/cache.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:30 [114] GET https://api.github.com:443/repos/actions/cache/compare/v3.0.11...9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
  proxy | 2022/11/01 02:02:30 [114] * authenticating github api request
  proxy | 2022/11/01 02:02:30 [114] 200 https://api.github.com:443/repos/actions/cache/compare/v3.0.11...9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
updater | INFO <job_496455577> Latest version is 3.0.11
updater | INFO <job_496455577> No update needed for actions/cache 3.0.11
updater | INFO <job_496455577> Checking if actions/checkout 3.1.0 needs updating
  proxy | 2022/11/01 02:02:30 [116] GET https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:30 [116] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:30 [116] 200 https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:30 [118] GET https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:30 [118] * authenticating git server request (host: github.com)
  proxy | 2022/11/01 02:02:30 [118] 200 https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2022/11/01 02:02:30 [120] GET https://api.github.com:443/repos/actions/checkout/compare/v3.1.0...93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
  proxy | 2022/11/01 02:02:30 [120] * authenticating github api request
  proxy | 2022/11/01 02:02:30 [120] 200 https://api.github.com:443/repos/actions/checkout/compare/v3.1.0...93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
updater | INFO <job_496455577> Latest version is 3.1.0
updater | INFO <job_496455577> No update needed for actions/checkout 3.1.0
updater | INFO <job_496455577> Finished job processing
updater | time="2022-11-01T02:02:30Z" level=info msg="task complete" container_id=job-496455577-updater exit_code=0 job_id=496455577 step=updater
```

</details>

The changes from https://github.com/dependabot/dependabot-core/pull/5576 should be included if I'm not mistaken, and I'm assuming they were sufficient to fix https://github.com/dependabot/dependabot-core/issues/5556, so I'm not sure if the issue is exactly the same. Apologies if this is the case.

### Smallest manifest that reproduces the issue

_No response_

### LINKED ISSUE #6045: Actions updates failing with error `fatal: '{some version}' does not appear to be a git repository`
Got an internal report that an actions update is now failing after https://github.com/dependabot/dependabot-core/pull/5951 was deployed.

Logs:
```
updater | ERROR <job_495965143> Error processing tibdex/github-app-token (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_495965143> fatal: '1.6.0' does not appear to be a git repository
updater | <job_495965143> fatal: Could not read from remote repository.
updater | <job_495965143> 
updater | <job_495965143> Please make sure you have the correct access rights
updater | <job_495965143> and the repository exists.
updater | ERROR <job_495965143> /home/dependabot/common/lib/dependabot/shared_helpers.rb:314:in `run_shell_command'
updater | ERROR <job_495965143> /home/dependabot/github_actions/lib/dependabot/github_actions/update_checker.rb:187:in `find_container_branch'
updater | ERROR <job_495965143> /home/dependabot/github_actions/lib/dependabot/github_actions/update_checker.rb:88:in `block in latest_commit_for_pinned_ref'
updater | ERROR <job_495965143> /home/dependabot/common/lib/dependabot/shared_helpers.rb:36:in `block in in_a_temporary_repo_directory'
updater | ERROR <job_495965143> /home/dependabot/common/lib/dependabot/shared_helpers.rb:36:in `chdir'
updater | ERROR <job_495965143> /home/dependabot/common/lib/dependabot/shared_helpers.rb:36:in `in_a_temporary_repo_directory'
updater | ERROR <job_495965143> /home/dependabot/github_actions/lib/dependabot/github_actions/update_checker.rb:87:in `latest_commit_for_pinned_ref'
updater | ERROR <job_495965143> /home/dependabot/github_actions/lib/dependabot/github_actions/update_checker.rb:75:in `fetch_latest_version_for_git_dependency'
updater | ERROR <job_495965143> /home/dependabot/github_actions/lib/dependabot/github_actions/update_checker.rb:58:in `fetch_latest_version'
updater | ERROR <job_495965143> /home/dependabot/github_actions/lib/dependabot/github_actions/update_checker.rb:13:in `latest_version'
updater | ERROR <job_495965143> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:518:in `all_versions_ignored?'
updater | ERROR <job_495965143> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:217:in `check_and_create_pull_request'
updater | ERROR <job_495965143> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:103:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_495965143> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:74:in `block in run'
updater | ERROR <job_495965143> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:74:in `each'
updater | ERROR <job_495965143> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:74:in `run'
updater | ERROR <job_495965143> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_495965143> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:50:in `run'
updater | ERROR <job_495965143> bin/update_files.rb:23:in `<main>'
```

And here's the line that mentions the `tibdex/github-app-token` action:
```
uses: tibdex/github-app-token@f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06
```

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
This PR wants to fix two issues:

* After #5951, we seem to have started using the `GitCommitChecker#head_commit_for_current_branch` method when `dependency.version` is an actual numbered version and not a ref. This is probably because with #5951 we have to deal with both numeric and ref versions in the same update. The current implementation of this method does not support this. I expect 90612fdda8a2471b66e78f341a649b013f6309a5 to fix this issue.

* Even with the above fix, updates for pinned refs still don't work as expected and we either get a different crash or a downgrade. The reason for this seems to lie in #5576. In that PR, in order to be able to properly detect whether actions pinned to arbitrary references are out of date, we started cloning the whole repository. However, I think the implementation there was incorrect and it started cloning the repository being updated (the one that includes the workflow files), not the repository of the dependency being updated (the repository of the action itself). I expect 721bd2df6cdd8462ddb6b3ab0adfd76978487831 to fix this issue.

With this I get proper updates of repositories pinned to specific references.

Fixes #6014.
Fixes #6045.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
As a note, this does not happen in every repository with actions pinned to refs.

A classic situation when this _does_ happen is:

* Target repository has default branch named "master".
* Action's repository has a default branch named "main", and also a branch named "master", more out of date. Due to the confusion in repo cloning explained above, Dependabot proposed to downgrade to the latest commit in the old "master" branch in this case.

**Comment by deivid-rodriguez** [comment]
I added some specs with VCR. My concern is whether these specs would start failing once more commits land in the sample repository, since these specs are actually cloning the repo to exercise the code changed here. I think no, because latest commit information is fetched from the `git-upload-pack` endpoint which is fixed as recorded by VCR. Cloning the repo is only to figure out the right branch to follow. But I'll fork the sample repo and try with my fork just to make sure.

Still these specs rely on cloning an external repo, which could get brittle. I'm not sure how to approach testing this otherwise. I thought of adding some smoke tests, but this particular situation needs the target repository and the repository where the updated action lives to be different repositories 🤔.

In general, I think this is good enough but I'm happy to hear more opinions.

**Comment by deivid-rodriguez** [comment]
I found and fixed one more issue where refs not tracking the default branch of an action were not being updated properly.

Also I added an optimization to not clone the action's repository if already pinned to the tip of a branch.

I think this should be good to go now.

File: github_actions/spec/dependabot/github_actions/update_checker_spec.rb [hunk 1]
```diff
@@ -392,6 +392,67 @@
...
+          requirements: [{
+            requirement: nil,
+            groups: [],
+            file: ".github/workflows/main.yml",
+            source: dependency_source
+          }],
+          package_manager: "github_actions"
+        )
+      end
+      let(:dependency_name) { "deivid-rodriguez/github-action-push-to-another-repository" }
```
Comment (mctofu) [inline github_actions/spec/dependabot/github_actions/update_checker_spec.rb:409]: suggest we move this to the dependabot-fixtures org

**Review by mctofu — APPROVED** [review]

File: github_actions/spec/dependabot/github_actions/update_checker_spec.rb (hunk 1 above)
Comment (deivid-rodriguez) [reply github_actions/spec/dependabot/github_actions/update_checker_spec.rb:409]: Set as draft until I move the repo, thanks for the review and the suggestion!

Comment (deivid-rodriguez) [reply github_actions/spec/dependabot/github_actions/update_checker_spec.rb]: It's been moved now!
