### PR TITLE
fix: check versions across all the defined maven registries

### LINKED ISSUE #9383: Maven version search should search all repositories, not stop after the first `maven-metadata.xml`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Maven

### Package manager version

_No response_

### Language version

_No response_

### Manifest location and content before the Dependabot update

_No response_

### dependabot.yml content

_No response_

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

Presumably since https://github.com/dependabot/dependabot-core/pull/5872, Dependabot incorrectly stops looking for repositories once a `maven-metadata.xml` is found.

I asked @olamy (a Maven committer) about this, and his response in https://github.com/dependabot/dependabot-core/pull/5872#issuecomment-2024735690 explains that the submitter of #5872 seems to have misunderstood the Maven documentation.

As a result, because the Jenkins project deployed a fork of Mina `sshd-core` to our own Maven repository a decade ago, and referencing that repository in `pom.xml`, Dependabot is unable to find more recent releases in repo1 as described in https://github.com/jenkins-infra/helpdesk/issues/3919#issuecomment-2023726186.

### Native package manager behavior

Using the minimal example below:

```
$ mvn org.codehaus.mojo:versions-maven-plugin:2.16.2:display-dependency-updates
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< org.example:dependabot-example >-------------------
[INFO] Building dependabot-example 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.16.2:display-dependency-updates (default-cli) @ dependabot-example ---
[INFO] The following dependencies in Dependencies have newer versions:
[INFO]   org.apache.sshd:sshd-core ........................... 2.11.0 -> 2.12.1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.850 s
[INFO] Finished at: 2024-03-28T16:03:39+01:00
[INFO] ------------------------------------------------------------------------
```

### Images of the diff or a link to the PR, issue, or logs

Using the minimal example below (at https://github.com/daniel-beck/dependabot-core-issue-9383):

```
./go/bin/dependabot update maven daniel-beck/dependabot-example
    cli | 2024/03/28 15:05:20 using image ghcr.io/github/dependabot-update-job-proxy/dependabot-update-job-proxy:latest at sha256:f8c0686dbbe734670a826b437cbf548934f5cf832f49c50fe407c612bb256b47
    cli | 2024/03/28 15:05:20 using image ghcr.io/dependabot/dependabot-updater-maven at sha256:64b1c014f3ea6330d4538e55fdb6502015511a77d4817b183948a0a86244f7ba
updater | Updating certificates in /etc/ssl/certs...
  proxy | 2024/03/28 15:05:20 proxy starting, commit: cf8623577dad71c128f219df2b27df6de35b909d
  proxy | 2024/03/28 15:05:20 GitHubAPIHandler has no app access tokens
  proxy | 2024/03/28 15:05:20 Listening (:1080)
updater | rehash: warning: skipping ca-certificates.crt,it does not contain exactly one certificate or CRL
updater | 1 added, 0 removed; done.
updater | Running hooks in /etc/ca-certificates/update.d...
updater | done.
updater | 2024/03/28 15:05:34 INFO Starting job processing
updater | 2024/03/28 15:05:34 INFO Job definition: {"job":{"package-manager":"maven","allowed-updates":[{"update-type":"all"}],"debug":false,"dependency-groups":[],"dependencies":null,"dependency-group-to-refresh":null,"existing-pull-requests":[],"existing-group-pull-requests":[],"experiments":null,"ignore-conditions":[],"lockfile-only":false,"requirements-update-strategy":null,"security-advisories":[],"security-updates-only":false,"source":{"provider":"github","repo":"daniel-beck/dependabot-example","directory":"/","hostname":null,"api-endpoint":null},"update-subdependencies":false,"updating-a-pull-request":false,"vendor-dependencies":false,"reject-external-code":false,"repo-private":false,"commit-message-options":null,"credentials-metadata":[],"max-updater-run-time":0}}
  proxy | 2024/03/28 15:05:35 [002] GET https://github.com:443/daniel-beck/dependabot-example/info/refs?service=git-upload-pack
  proxy | 2024/03/28 15:05:35 [002] 200 https://github.com:443/daniel-beck/dependabot-example/info/refs?service=git-upload-pack
  proxy | 2024/03/28 15:05:35 [004] POST https://github.com:443/daniel-beck/dependabot-example/git-upload-pack
  proxy | 2024/03/28 15:05:35 [004] 200 https://github.com:443/daniel-beck/dependabot-example/git-upload-pack
  proxy | 2024/03/28 15:05:35 [006] POST https://github.com:443/daniel-beck/dependabot-example/git-upload-pack
  proxy | 2024/03/28 15:05:35 [006] 200 https://github.com:443/daniel-beck/dependabot-example/git-upload-pack
updater | 2024/03/28 15:05:37 INFO Finished job processing
updater | 2024/03/28 15:05:38 INFO Starting job processing
  proxy | 2024/03/28 15:05:38 [007] POST http://host.docker.internal:50733/update_jobs/cli/update_dependency_list
{"data":{"dependencies":[{"name":"org.apache.sshd:sshd-core","requirements":[{"file":"pom.xml","groups":[],"metadata":{"packaging_type":"jar"},"requirement":"2.11.0","source":null}],"version":"2.11.0"}],"dependency_files":["/pom.xml"]},"type":"update_dependency_list"}
  proxy | 2024/03/28 15:05:38 [007] 200 http://host.docker.internal:50733/update_jobs/cli/update_dependency_list
  proxy | 2024/03/28 15:05:38 [008] POST http://host.docker.internal:50733/update_jobs/cli/increment_metric
{"data":{"metric":"updater.started","tags":{"operation":"update_all_versions"}},"type":"increment_metric"}
  proxy | 2024/03/28 15:05:38 [008] 200 http://host.docker.internal:50733/update_jobs/cli/increment_metric
updater | 2024/03/28 15:05:38 INFO Starting update job for daniel-beck/dependabot-example
updater | 2024/03/28 15:05:38 INFO Checking all dependencies for version updates...
updater | 2024/03/28 15:05:38 INFO Checking if org.apache.sshd:sshd-core 2.11.0 needs updating
  proxy | 2024/03/28 15:05:39 [010] GET https://repo.jenkins-ci.org:443/releases/org/apache/sshd/sshd-core/maven-metadata.xml
  proxy | 2024/03/28 15:05:39 [010] 200 https://repo.jenkins-ci.org:443/releases/org/apache/sshd/sshd-core/maven-metadata.xml
  proxy | 2024/03/28 15:05:39 [012] HEAD https://repo.jenkins-ci.org:443/releases/org/apache/sshd/sshd-core/0.11.0-sshd-314-1/sshd-core-0.11.0-sshd-314-1.jar
  proxy | 2024/03/28 15:05:39 [012] 200 https://repo.jenkins-ci.org:443/releases/org/apache/sshd/sshd-core/0.11.0-sshd-314-1/sshd-core-0.11.0-sshd-314-1.jar
updater | 2024/03/28 15:05:40 INFO Latest version is 0.11.0-sshd-314-1
updater | 2024/03/28 15:05:40 INFO No update needed for org.apache.sshd:sshd-core 2.11.0
  proxy | 2024/03/28 15:05:40 [013] PATCH http://host.docker.internal:50733/update_jobs/cli/mark_as_processed
{"data":{"base-commit-sha":"09fdc063f3278721ac03bebe4e739551fa96ea40"},"type":"mark_as_processed"}
  proxy | 2024/03/28 15:05:40 [013] 200 http://host.docker.internal:50733/update_jobs/cli/mark_as_processed
updater | 2024/03/28 15:05:40 INFO Finished job processing
  proxy | 2024/03/28 15:05:40 Skipping sending metrics because api endpoint is empty
  proxy | 2024/03/28 15:05:40 0/5 calls cached (0%)
```

### Smallest manifest that reproduces the issue

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>dependabot-example</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.apache.sshd</groupId>
            <artifactId>sshd-core</artifactId>
            <version>2.11.0</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>repo.jenkins-ci.org</id>
            <url>https://repo.jenkins-ci.org/releases/</url>
        </repository>
    </repositories>

</project>
```

### PR DESCRIPTION
**Pull request by yeikel**
### What are you trying to accomplish?

When checking for new versions, we shouldn’t assume that the first repository to respond has the latest version, as it might return a stale one. Instead, Dependabot should scan all repositories, aggregate all available metadata for an artifact, and select the highest version available across them

This behavior was introduced with #5872 in order to reduce the network load, and while the following is true while resolving 

> Remote repository URLs are queried in the following order for artifacts until one returns a valid result

This does not directly translate while looking for new versions as documented in the spec. 

For more details, see https://github.com/dependabot/dependabot-core/pull/5872#issuecomment-2024735690

Fixes #9383

### How will you know you've accomplished your goal?

Running the updated version using my reproducer works as expected

See: https://github.com/yeikel/dependabot-reproducer-9383

Current 

> updater | 2025/12/10 06:13:56 INFO Latest version is 0.11.0-sshd-314-1
> updater | 2025/12/10 06:13:56 INFO No update needed for org.apache.sshd:sshd-core 2.11.0
> {"data":{"base-commit-sha":"6dbf65dc2b7a652b60054518953e70fe2a9fa21e"},"type":"mark_as_processed"}
>   proxy | 2025/12/10 06:13:56 [023] PATCH http://host.docker.internal:57186/update_jobs/cli/mark_as_processed
>   proxy | 2025/12/10 06:13:56 [023] 200 http://host.docker.internal:57186/update_jobs/cli/mark_as_processed
> updater | 2025/12/10 06:13:56 INFO Finished job processing
>   proxy | 2025/12/10 06:13:56 Skipping sending metrics because api endpoint is empty
>   proxy | 2025/12/10 06:13:56 0/10 calls cached (0%)

After: 

> updater | 2025/12/10 06:19:56 INFO Latest version is 2.16.0
> {"data":{"base-commit-sha":"6dbf65dc2b7a652b60054518953e70fe2a9fa21e"},"type":"mark_as_processed"}
>   proxy | 2025/12/10 06:20:00 [062] PATCH http://host.docker.internal:57437/update_jobs/cli/mark_as_processed
>   proxy | 2025/12/10 06:20:00 [062] 200 http://host.docker.internal:57437/update_jobs/cli/mark_as_processed
> updater | 2025/12/10 06:20:00 INFO Finished job processing
> updater | 2025/12/10 06:20:00 INFO Results:
> updater | +---------------------------------------------------------------+
> updater | |              Changes to Dependabot Pull Requests              |
> updater | +---------+-----------------------------------------------------+
> updater | | created | org.apache.sshd:sshd-core ( from 2.11.0 to 2.16.0 ) |
> updater | +---------+-----------------------------------------------------+
>   proxy | 2025/12/10 06:20:00 Skipping sending metrics because api endpoint is empty
>   proxy | 2025/12/10 06:20:00 4/29 calls cached (13%)

### Checklist

- [x] I have run the complete test suite to ensure all tests and linters pass.
- [x] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [x] I have written clear and descriptive commit messages.
- [x] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [x] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

**Comment by yeikel** [comment]
@jakecoffman I'd appreciate your review given that you introduced #5872

**Comment by yeikel** [comment]
@kbukum1 Any chance you can find me a reviewer for this change or review it yourself?

Thanks!

**Comment by yeikel** [comment]
@kbukum1

Could you please review this and share your feedback if any?

Thank you in advance!

File: maven/lib/dependabot/maven/package/package_details_fetcher.rb [hunk 1]
```diff
@@ -135,7 +135,7 @@ def versions_details_from_xml
             xml = dependency_metadata(repository_details)
             next [] if xml.nil?
 
-            break extract_metadata_from_xml(xml, url)
+            extract_metadata_from_xml(xml, url)
```
Comment (v-kbukum1) [inline maven/lib/dependabot/maven/package/package_details_fetcher.rb:138]: @yeikel  
With this change, won’t `version_details` end up with duplicate entries for dependencies found in multiple repositories? Is there deduplication to prevent this?

Comment (yeikel) [reply maven/lib/dependabot/maven/package/package_details_fetcher.rb:138]: Yes, but that's exactly the desired behavior we need from this module because we will later on need to iterate all the versions and pick the latest. Based on specs/manual testing, it seems to be working as expected 

See https://github.com/yeikel/dependabot-reproducer-9383

Comment (yeikel) [reply maven/lib/dependabot/maven/package/package_details_fetcher.rb:138]: @kbukum1 Do you have any other feedback or anything I should test before this is scheduled for merge?

Comment (v-kbukum1) [reply maven/lib/dependabot/maven/package/package_details_fetcher.rb:138]: I think we are good. You can test it.

**Review by kbukum1 — APPROVED** [review]

File: maven/lib/dependabot/maven/package/package_details_fetcher.rb (hunk 1 above)
Comment (yeikel) [reply maven/lib/dependabot/maven/package/package_details_fetcher.rb:138]: Thanks! 

I tested it using the reproducer above plus the existing tests and it seems fine

Comment (v-kbukum1) [reply maven/lib/dependabot/maven/package/package_details_fetcher.rb:138]: I am just woried when there is private registery and public registry in the list, how will that behave?

Comment (yeikel) [reply maven/lib/dependabot/maven/package/package_details_fetcher.rb:138]: It should scan both and pick the latest

Comment (v-kbukum1) [reply maven/lib/dependabot/maven/package/package_details_fetcher.rb:138]: I was more concerning about having issues also mixing up public and private registry results. Sometimes companies who uses private registries may not want to get latest from public even if their private registiry is behind. But I think it will be ok.

Comment (yeikel) [reply maven/lib/dependabot/maven/package/package_details_fetcher.rb:138]: I think that this should be fine because if any company wants to only use their private registries they should be intentional in their POM file and disable central and/or use `replaces-base` from the dependabot configuration

**Comment by yeikel** [comment]
@kbukum1 

Could you please clarify what's blocking this merge? Do you need any additional information, reproducer or tests?

Thanks

**Review by kbukum1 — APPROVED** [review]
