### PR TITLE
Fix lockfile incorrectly updated with unrelated path gem version

### LINKED ISSUE #6627: Path-based (vendored) gem version is bumped when bumping any other gems
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

bundler

### Package manager version

rubygems 3.3.26
bundler 2.3.26

### Language version

ruby 2.7.7

### Manifest location and content before the Dependabot update

This is not the full `/Gemfile`, just a small section of it... I'm not sure if it is enough to trigger the bug. 😦

```ruby
source "https://rubygems.org"

gem "rails", "~> 6.1.0"
gem "bootsnap", require: false
gem "backports", "~> 3.18", require: false

# These gems used to be in another private repo, but the hassle of handling
# permissions, between Github Codespaces, dependabot, different developers,
# and deployment... it was far more annoying than it was worth.  So I vendored
# the private_gems repo... and that's when dependabot started making buggy PRs.
gem "our-dblib", path: "vendor/private_gems/our-dblib"
gem "our-utils", path: "vendor/private_gems/our-utils"

group :default, :stdlib do
  # This gem has been vendored for a while now.  Before net-imap was gemified,
  # we used to simply place our forked copy somewhere early in the $LOAD_PATH.
  gem "net-imap", path: "vendor/net-imap"   # we have several big patches in here
end

# and many many more gems...
# some git: "...", some github: "...", most just using rubygems.org.
```

### dependabot.yml content

```yml
---
version: 2
updates:
  - package-ecosystem: "bundler"
    open-pull-requests-limit: 15
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    versioning-strategy: lockfile-only
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    commit-message:
      prefix:             "⬆️  bundle"
      prefix-development: "⬆️  bundle dev"
      include: "scope"
  # also npm, github-actions, gomod
```

### Updated dependency

When _any_ gem whatsoever is (correctly) updated...

The `net-imap` gem is also "updated" from `0.3.2.patched` or `0.3.5` or `0.3.99` (it's vendored, so I've tried a variety of version numbers to see if that would fix the issue) to `0.9.0`...

Coincidentally, 0.9.0, is the same version as "our-dblib" (not the real name, FWIW) in /vendor/private_gems/our-dblib.  And "our-dblib" comes immediately after `net-imap` in Gemfile.lock.  And this problem seems to have started after we vendored "our-dblib".  🤷🏻

### What you expected to see, versus what you actually saw

We're seeing PRs like the following:

```patch
commit 134f8603e8c60a83858a39285f4eb8b1b540877f (HEAD -> dependabot/bundler/net-http-0.3.2, origin/dependabot/bundler/net-http-0.3.2)
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Tue Feb 7 20:12:36 2023 +0000

    :arrow_up:  bundle dev(deps-dev): Bump net-http from 0.3.1 to 0.3.2
    
    Bumps [net-http](https://github.com/ruby/net-http) from 0.3.1 to 0.3.2.
    - [Release notes](https://github.com/ruby/net-http/releases)
    - [Commits](https://github.com/ruby/net-http/compare/v0.3.1...v0.3.2)
    
    ---
    updated-dependencies:
    - dependency-name: net-http
      dependency-type: direct:development
      update-type: version-update:semver-patch
    ...
    
    Signed-off-by: dependabot[bot] <support@github.com>

diff --git a/Gemfile.lock b/Gemfile.lock
index 7ee77c096..106914d39 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -79,7 +79,7 @@ GIT
 PATH
   remote: vendor/net-imap
   specs:
-    net-imap (0.3.1)
+    net-imap (0.9.0)
       date
       net-protocol
 
@@ -459,7 +459,7 @@ GEM
     mutex_m (0.1.2)
     nest (1.1.2)
       redis
-    net-http (0.3.1)
+    net-http (0.3.2)
       uri
     net-http-digest_auth (1.4.1)
     net-http-persistent (3.1.0)
```

When we *should* be getting PRs like the following:
```patch
commit 134f8603e8c60a83858a39285f4eb8b1b540877f (HEAD -> dependabot/bundler/net-http-0.3.2, origin/dependabot/bundler/net-http-0.3.2)
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Tue Feb 7 20:12:36 2023 +0000

    ⬆️ bundle dev(deps-dev): Bump net-http from 0.3.1 to 0.3.2
    
    Bumps [net-http](https://github.com/ruby/net-http) from 0.3.1 to 0.3.2.
    - [Release notes](https://github.com/ruby/net-http/releases)
    - [Commits](https://github.com/ruby/net-http/compare/v0.3.1...v0.3.2)
    
    ---
    updated-dependencies:
    - dependency-name: net-http
      dependency-type: direct:development
      update-type: version-update:semver-patch
    ...
    
    Signed-off-by: dependabot[bot] <support@github.com>

diff --git a/Gemfile.lock b/Gemfile.lock
index 7ee77c096..106914d39 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -459,7 +459,7 @@ GEM
     mutex_m (0.1.2)
     nest (1.1.2)
       redis
-    net-http (0.3.1)
+    net-http (0.3.2)
       uri
     net-http-digest_auth (1.4.1)
     net-http-persistent (3.1.0)
```

There shouldn't be any change to `net-imap` whatsoever.  This is (predictably) causing _all_ bundler dependabot PRs to fail until someone manually fixes the commit.

_(FWIW, I also filed #4565 a year ago... which is also exhibited above.  😉)_

### Native package manager behavior

It simply does the right thing, exactly as you would expect.  Only the requested gem is upgraded (or possible some of that gem's own dependencies).  Generally, the way I fix the PRs is this:

```
/workspace/app_root $ git switch dependabot/bundler/net-http-0.3.2
branch 'dependabot/bundler/net-http-0.3.2' set up to track 'origin/dependabot/bundler/net-http-0.3.2'.
Switched to a new branch 'dependabot/bundler/net-http-0.3.2'
```
```
/workspace/app_root $ git checkout main -- Gemfile.lock
```
```
/workspace/app_root $ bundle update net-http
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies.....
Using rake 13.0.6
Using zeitwerk 2.6.6
Using nio4r 2.5.8
----------------8<-------------[ and so one... ]--------------------
Fetching net-http 0.3.2 (was 0.3.1)
----------------8<-------------[ and so forth... ]------------------
Installing net-http 0.3.2 (was 0.3.1)
----------------8<-------------[ & cetera ]-------------------------
Bundle updated!
3 installed gems you directly depend on are looking for funding.
  Run `bundle fund` for details
```

At which point, the diff looks exactly as it should.

```
/workspace/app_root $ git add .
/workspace/app_root $ git commit --amend --no-edit
[dependabot/bundler/net-http-0.3.2 94f70450b] :arrow_up:  bundle dev(deps-dev): Bump net-http from 0.3.1 to 0.3.2
 Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
 Date: Tue Feb 7 20:12:36 2023 +0000
 1 file changed, 1 insertion(+), 1 deletion(-)
```
```patch
/workspace/app_root $ git -P show
commit 94f70450bc733f3210a5b1ab930080e16f138e59 (HEAD -> dependabot/bundler/net-http-0.3.2)
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Tue Feb 7 20:12:36 2023 +0000

    :arrow_up:  bundle dev(deps-dev): Bump net-http from 0.3.1 to 0.3.2
    
    Bumps [net-http](https://github.com/ruby/net-http) from 0.3.1 to 0.3.2.
    - [Release notes](https://github.com/ruby/net-http/releases)
    - [Commits](https://github.com/ruby/net-http/compare/v0.3.1...v0.3.2)
    
    ---
    updated-dependencies:
    - dependency-name: net-http
      dependency-type: direct:development
      update-type: version-update:semver-patch
    ...
    
    Signed-off-by: dependabot[bot] <support@github.com>

diff --git a/Gemfile.lock b/Gemfile.lock
index 7ee77c096..fa0b2d3d4 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -459,7 +459,7 @@ GEM
     mutex_m (0.1.2)
     nest (1.1.2)
       redis
-    net-http (0.3.1)
+    net-http (0.3.2)
       uri
     net-http-digest_auth (1.4.1)
     net-http-persistent (3.1.0)
```
```
/workspace/app_root $ git push --force-with-lease
----------------8<-------------[ & cetera ]------------------
 + 134f8603e...94f70450b dependabot/bundler/net-http-0.3.2 -> dependabot/bundler/net-http-0.3.2 (forced update)
```

### Images of the diff or a link to the PR, issue, or logs

I can provide plenty of links to PRs... they are all in a private repository though.  Let me know if there's a way I can provide more debug info, semi-privately.  E.g. I wouldn't be surprised if there's something weird in the gemspec for our private gems... they were first created in 2016 with bundler ~>1.10 and ruby 2.2 or 2.3.

### Smallest manifest that reproduces the issue

I've tried to reproduce this in the dependabot test suite, but I wasn't able to... (within my time constraints).  Sorry. 😦

I may have simply been attempting to test it in the wrong place, or perhaps my test fixture simply didn't cause the bug.  If you point me in the right direction of how I might quickly replicate the update process, ideally inside the test suite, then I can try again.

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
If Bundler was unable to infer the name of a gemspec, it would use the version of the first parsed path gemspec, which... is not correct.

This change makes Bundler try harder to find the gem name by also considering the name of the gemspec file, which in most cases matches the gem name.

Fixes #6627.

### CODE REVIEW

File: bundler/spec/dependabot/bundler/file_updater/lockfile_updater_spec.rb [hunk 1]
```diff
@@ -0,0 +1,55 @@
+# frozen_string_literal: true
+
+require "spec_helper"
+require "shared_contexts"
+require "dependabot/dependency"
+require "dependabot/dependency_file"
+require "dependabot/bundler/file_updater/lockfile_updater"
+
+RSpec.describe Dependabot::Bundler::FileUpdater::LockfileUpdater do
+  include_context "stub rubygems compact index"
```
Comment (jeffwidman) [inline bundler/spec/dependabot/bundler/file_updater/lockfile_updater_spec.rb:10]: I had no idea this method existed!

**Review by jeffwidman — APPROVED** [review]
