### PR TITLE
Fix illformed requirement error on "workspace:" dependencies

### LINKED ISSUE #6092: yarn2 workspace monorepo: Can't handle `workspace:` dependencies.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn

### Package manager version

3.2.1

### Language version

Node.js 16.x

### Manifest location and content before the Dependabot update

_No response_

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/databricks-sdk-js"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@databricks/*"          
  - package-ecosystem: "npm"
    directory: "/packages/databricks-vscode"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@databricks/*"    
  - package-ecosystem: "npm"
    directory: "/packages/databricks-vscode-types"
    ignore:
      - dependency-name: "@databricks/*"    
    schedule:
      interval: "daily"
```

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

I'm using the yarn workspace feature to manage a mono repo with several node.js packages. The different packages define dependencies to each other in the form of `workspace:` links:

`"@databricks/databricks-sdk": "workspace:^",`

Dependabot failes to resolve these dependencies and instead tries to look them up on npm, which results in the following error:

```
 Dependabot can't authenticate to a private package registry
The following private package registry was used and caused the update to fail: registry.npmjs.org.
```

Screenshot 2022-11-09 at 15 08 22

From the logs:
```
  proxy | 2022/11/08 17:06:26 [036] GET https://registry.npmjs.org:443/@databricks%2Fdatabricks-sdk
  proxy | 2022/11/08 17:06:26 [036] 404 https://registry.npmjs.org:443/@databricks%2Fdatabricks-sdk
  proxy | 2022/11/08 17:06:26 [038] GET https://www.npmjs.com:443/package/@databricks/databricks-sdk
  proxy | 2022/11/08 17:06:27 [038] 302 https://www.npmjs.com:443/package/@databricks/databricks-sdk
  proxy | 2022/11/08 17:06:27 [040] GET https://www.npmjs.com:443/login?next=%2Fpackage%2F%40databricks%2Fdatabricks-sdk
  proxy | 2022/11/08 17:06:27 [040] 429 https://www.npmjs.com:443/login?next=%2Fpackage%2F%40databricks%2Fdatabricks-sdk
updater | INFO <job_504761053> Handled error whilst updating @databricks/databricks-sdk: private_source_authentication_failure {:source=>"registry.npmjs.org"}
```

This is not a surprise since the package doesn't exist on NPM.

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

_No response_

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Fixes #6092.

### CODE REVIEW

File: npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb [hunk 1]
```diff
@@ -59,6 +59,12 @@
         its(:length) { is_expected.to eq(0) }
       end
 
+      context "with no lockfile, and yarn `workspace:` requirements" do
```
Comment (landongrindheim) [inline npm_and_yarn/spec/dependabot/npm_and_yarn/file_parser_spec.rb:62]: 💅 I first read this to mean "with no lockfile and no yarn `workspace:` requirements". I think this re-ordering makes the intention of the spec 🤏 clearer. What do you think?

```suggestion
      context "with yarn `workspace:` requirements and no lockfile" do
```

**Review by landongrindheim — APPROVED** [review]
