### PR TITLE
Fix Gradle lockfile support against Gradle's version catalog (Fix #12557)

### LINKED ISSUE #12557: Dependabot's support for Gradle lockfiles is not working when Gradle's "Version Catalog" is in use
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Gradle

### Package manager version

8.14.2

### Language version

Java

### `/build.gradle`

```
plugins {
    id "java"
}

repositories {
    mavenCentral()
}

group = "io.github.dmikurube"
version = "0.1.0-SNAPSHOT"

configurations {
    compileClasspath.resolutionStrategy.activateDependencyLocking()
    runtimeClasspath.resolutionStrategy.activateDependencyLocking()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    implementation libs.slf4j.api
}
```

### `/gradle.lockfile`

```
# This is a Gradle generated file for dependency locking.
# Manual edits can break the build and are not advised.
# This file is expected to be part of source control.
org.slf4j:slf4j-api:2.0.0=compileClasspath,runtimeClasspath
empty=
```

### `/gradle/libs.versions.toml`

```
[versions]

slf4j-api = "2.0.0"

[libraries]

slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j-api" }
```

### dependabot.yml content

```
---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
```

### Updated dependency

The dependency was updated in `/gradle/libs.versions.toml`, but `/gradle.lockfile` was not updated.

### What you expected to see, versus what you actually saw

As the "Support for Gradle lockfiles" is generally available, I expected to see an update with `gradle.lockfile` for my Gradle project.

* https://github.com/dependabot/dependabot-core/issues/2222
* https://github.blog/changelog/2025-06-24-dependabot-support-for-gradle-lockfiles-is-now-generally-available/

However, in one of my repository, Dependabot didn't update `gradle.lockfile`. By making some small example repositories, I've identified that it is not working when Gradle's "Version Catalog" is used in the repository.

Similar issues are discussed in https://github.com/dependabot/dependabot-core/issues/2222

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

See the examples below to narrow down the issue. The second one (with Gradle's Version Catalog) is failing.

* https://github.com/dmikurube/dependabot-simple/pull/1 => SUCCESS
* https://github.com/dmikurube/dependabot-catalog/pull/1 => FAIL
* https://github.com/dmikurube/dependabot-bom/pull/1 = SUCCESS

### Smallest manifest that reproduces the issue

Shown in "Manifest location and content before the Dependabot update" -- this is the narrowed down case.

### PR DESCRIPTION
**Pull request by dmikurube**
### What are you trying to accomplish?

Trying to fix #12557 -- a bug in Gradle lockfile support (which is introduced in #12287) against Gradle version catalog (`/gradle/libs.versions.toml`).

Before this fix, Gradle lockfile has not been updated when the versions are managed in Gradle version catalog (`/gradle/libs.versions.toml`), not in build file (`build.gradle(.kts)`). (See #12557 for the bug details.)

The issue came from how `lockfile_updater.rb` determined `cwd`. `cwd` should be where `build.gradle(.kts)` exists.

It determined `cwd` by `File.dirname(build_file)` (in short). However, it does not work for the version catalog file (`build_file` = `/gradle/libs.versions.toml`) because `File.dirname("/gradle/libs.versions.toml")` would be `/gradle`, not `/`.

Against `/gradle/libs.versions.toml`, `cwd` should be `/`.

### Anything you want to highlight for special attention from reviewers?

I tried this so that it would be a minimum fix for the Gradle version catalog issue.

### How will you know you've accomplished your goal?

I confirmed this fix by :

```
$ bin/dry-run.rb gradle dmikurube/dependabot-catalog
```

When adding `--info` and `--stacktrace` in the Gradle commandline below,

https://github.com/dependabot/dependabot-core/blob/58212ab85ead42b51a147a5e05ea30ca4d827ef2/gradle/lib/dependabot/gradle/file_updater/lockfile_updater.rb#L41-L46

an error message could be observed.

```
Project directory 'dependabot_tmp_dir/gradle' is not part of the build defined by settings file 'dependabot_tmp_dir/settings.gradle'. If this is an unrelated build, it must have its own settings file.
```

After this fix, the error message has gone, and `gradle.lockfile` is updated.

### Checklist

- [x] I have run the complete test suite to ensure all tests and linters pass.
- [x] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [x] I have written clear and descriptive commit messages.
- [x] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [x] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

**Comment by dmikurube** [comment]
Cc: @ryanbrandenburg

File: gradle/lib/dependabot/gradle/file_updater/lockfile_updater.rb [hunk 1]
```diff
@@ -31,7 +31,11 @@ def update_lockfiles(build_file)
           SharedHelpers.in_a_temporary_directory do |temp_dir|
             populate_temp_directory(temp_dir)
             cwd = File.join(temp_dir, build_file.directory, build_file.name)
-            cwd = File.dirname(cwd)
+            cwd = if build_file.path.end_with?("/gradle/libs.versions.toml")
```
Comment (yeikel) [inline gradle/lib/dependabot/gradle/file_updater/lockfile_updater.rb:34]: I think that adding a test (integration or unit) may increase the odds that this is meged to main

Comment (dmikurube) [reply gradle/lib/dependabot/gradle/file_updater/lockfile_updater.rb:34]: Yeah, I at first thought to add some tests for this change based on existing tests, of course. But unfortunately, the original lockfile-related code has had almost no practical test code. :(

I'm positive to add some tests, but it'll need non-trivial efforts to write brand-new tests from full scratch. Then, thought to share this fixing code snippet here at fitst.

Do you have any good idea how to test the lockfile-related things?  I'm totally new inside dependabot.

Comment (dmikurube) [reply gradle/lib/dependabot/gradle/file_updater/lockfile_updater.rb:34]: The original pull request #12287 seemed to add some test code in the beginning.

But at https://github.com/dependabot/dependabot-core/pull/12287/commits/00a8e99e4075bd285f6632050f70f35fee781c38, these tests were removed, and the pull request finally had only added `stub_no_content_request(".../gradle.lockfile...")` in existing tests. I'm not sure how these are testing the lockfile-related things...

**Comment by liedQM** [comment]
Is there any update? We're facing the same issues.

**Comment by dmikurube** [comment]
No update from me. Just waiting for their comment.

**Comment by maurofaccenda** [comment]
I have, what seems to me, the same issue. It can be observed here:

https://github.com/faccenda-org/vulnspringbootapp/pull/16

**Comment by wjglerum** [comment]
Can we merge this? Just noticed again that it was not working, which is kinda annoying.

**Comment by maksymilian-magowski-cog** [comment]
Any chance for a merge? Such a feature would be much appreciated.

**Comment by dmikurube** [comment]
I am willing to do follow-up work (like adding tests if required) once the maintainer(s) recognize this, but I have received no reaction so far, so I am leaving it as-is.

**Comment by yeikel** [comment]
Can you guys share a reproducer?

**Comment by dmikurube** [comment]
Some reproducing cases are explained in https://github.com/dependabot/dependabot-core/issues/12557

**Comment by v-kbukum1** [comment]
@dmikurube 

Thanks for this fix! This addresses the main issue for the default `libs.versions.toml` catalog.

**One suggestion:**  
Gradle lets users define custom-named catalog files and multiple catalogs (configurable in `settings.gradle(.kts)`), so it's good to check if this change covers those cases. If not it will be great somehow to find a solution to properly support catalogs, not only default case? Let me know if you need any help for that. Other then that we need to cover the edge cases where catalog is defined (for default and custom cases, multiple catalogs cases), not defined. 

**Official Documentation & References:**

- Gradle User Manual, Version Catalogs:  
  https://docs.gradle.org/current/userguide/version_catalogs.html

  > See the section “Multiple catalogs” for details:  
  > https://docs.gradle.org/current/userguide/version_catalogs.html#sec:multiple-catalogs

- Example from the docs for custom catalogs in `settings.gradle(.kts)`:
    ```kotlin
    dependencyResolutionManagement {
        versionCatalogs {
            create("myCatalog") {
                from(files("gradle/my-catalog.versions.toml"))
            }
            create("otherCatalog") {
                from(files("../some/other.versions.toml"))
            }
        }
    }
    ```
  Source: https://docs.gradle.org/current/userguide/version_catalogs.html#sub:custom-catalog-name

**Comment by dmikurube** [comment]
> Gradle lets users define custom-named catalog files and multiple catalogs (configurable in settings.gradle(.kts)), so it's good to check if this change covers those cases. If not it will be great somehow to find a solution to properly support catalogs, not only default case? Let me know if you need any help for that. Other then that we need to cover the edge cases where catalog is defined (for default and custom cases, multiple catalogs cases), not defined.

I agree that "it will be great somehow" to find a solution to properly support catalogs, not only default case, but it does not seem to be easy for me based on the existing code by #12287.

The original #12287 does not seem to be made to look into such non-default configurations in `build.gradle`. It just actually runs Gradle, and finds some file changes from some "default" hard-coded paths. That's it. #12287 does not look into detailed `build.gradle` configs.

In order to cover such a "non-default" cases configured in `build.gradle`, I guess that it'll be a huge amount of work that we'll have to rennovate almost all the existing code by #12287.

If it could be implemented easily, I am willing to do some work on it, but I don't think it'll be easy. Or, if you have, could you share any ideas how it would be implemented?

----

The original #12287 was merged even with missing a big "corner" case -- the "default" version catalog -- not working. Do we have reasons why this has to be 100% perfect although such a big part of use-cases (use of the version catalog even in the default location) has been ignored for months?

Many Gradle users use the version catalog, but very few users use the version catalog in a different location. At least, this pull-request covers many default use-cases of the version catalog.

**Comment by v-kbukum1** [comment]
> > Gradle lets users define custom-named catalog files and multiple catalogs (configurable in settings.gradle(.kts)), so it's good to check if this change covers those cases. If not it will be great somehow to find a solution to properly support catalogs, not only default case? Let me know if you need any help for that. Other then that we need to cover the edge cases where catalog is defined (for default and custom cases, multiple catalogs cases), not defined.
> 
> I agree that "it will be great somehow" to find a solution to properly support catalogs, not only default case, but it does not seem to be easy for me based on the existing code by #12287.
> 
> The original #12287 does not seem to be made to look into such non-default configurations in `build.gradle`. It just actually runs Gradle, and finds some file changes from some "default" hard-coded paths. That's it. #12287 does not look into detailed `build.gradle` configs.
> 
> In order to cover such a "non-default" cases configured in `build.gradle`, I guess that it'll be a huge amount of work that we'll have to rennovate almost all the existing code by #12287.
> 
> If it could be implemented easily, I am willing to do some work on it, but I don't think it'll be easy. Or, if you have, could you share any ideas how it would be implemented?
> 
> The original #12287 was merged even with missing a big "corner" case -- the "default" version catalog -- not working. Do we have reasons why this has to be 100% perfect although such a big part of use-cases (use of the version catalog even in the default location) has been ignored for months?
> 
> Many Gradle users use the version catalog, but very few users use the version catalog in a different location. At least, this pull-request covers many default use-cases of the version catalog.

Thanks for your response, and apologies for my late reply. I’ll most likely be able to review and deploy this sometime this week—just want to briefly discuss it with the team first. If we end up planning to support additional scenarios beyond the default (like custom-named or multiple catalogs), I’ll let you know. 

Overall, I really appreciate the support and contribution! As it stands, this PR covers the most common use-cases for version catalogs, which is great.

**Review by kbukum1 — APPROVED** [review]

**Comment by dmikurube** [comment]
Thanks! I'm looking for this starting to work (on my Java projects...)

**Comment by v-kbukum1** [comment]
@dmikurube 

Thanks for your contribution. When you are using it in your project, please let me know if everything is alright or if there is any issue.

**Comment by nord-erik** [comment]
Is this PR "live", e.g. does dependabot run this version today? My dependabot repos still struggle to version bump lockfiles in gradle -- same directory hierarchy as described in original PR description
