### PR TITLE
Fix Cargo config file fetching from parent directories

### LINKED ISSUE #13523: Cargo updater does not look for config.toml files at the root of the repo
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Cargo

### Package manager version

_No response_

### Language version

_No response_

### Manifest location and content before the Dependabot update

_No response_

### dependabot.yml content

_No response_

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

Dependabot should detect a config.toml present at the root of the repo and perform an update.

The issue is that the file `.cargo/config.toml" is getting pulled via [fetch_support_file](https://github.com/dependabot/dependabot-core/blob/75ff1e85d5afd8497fd55ba0d8b89d3413cfd784/common/lib/dependabot/file_fetchers/base.rb#L201) which ultimately calls [fetch_file_from_host](https://github.com/dependabot/dependabot-core/blob/75ff1e85d5afd8497fd55ba0d8b89d3413cfd784/common/lib/dependabot/file_fetchers/base.rb#L264) which prepends the job's starting directory, so in our case calling fetch_support_file(".cargo/config.toml") essentially turned into trying to get the file "/some/dir/in/this/repo/.cargo/config.toml" but what we really need is a helper method to start in the job's directory and walk all the way to the root, each time appending ".cargo/config.toml" and trying to find that file.

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

Any cargo.config placed at any of the locations specified.

### PR DESCRIPTION
**Pull request by a-schur**
Cargo searches for .cargo/config.toml hierarchically from the current directory up to the repository root. This fix implements the parent directory search functionality to properly locate config files that exist in parent directories.

The implementation walks up the directory tree from the job directory, trying to fetch .cargo/config.toml (and the legacy .cargo/config) from each parent level until one is found or the repository root is reached.

Closes #13523

### Checklist

- [x] I have run the complete test suite to ensure all tests and linters pass.
- [x] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [x] I have written clear and descriptive commit messages.
- [x] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [x] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

**Review by sebasgomez238 — APPROVED** [review]

**Comment by v-abhishekbhaskar** [comment]
Reproduced the issue [here](https://github.com/dsp-testing/test-npm-core-issues/actions/runs/20727274129/job/59505841453). Confirmed the PR fixes the issue. Attaching screenshot of local dry-run below:
cargo-config-root

**Review by kbukum1 — APPROVED** [review]
LGTM

File: cargo/lib/dependabot/cargo/file_fetcher/config_fetcher.rb [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+require "dependabot/cargo/file_fetcher"
+
+module Dependabot
+  module Cargo
+    class FileFetcher < Dependabot::FileFetchers::Base
+      class ConfigFetcher
+        extend T::Sig
+
+        sig { params(fetcher: Dependabot::Cargo::FileFetcher).void }
+        def initialize(fetcher:)
```
Comment (v-kbukum1) [inline cargo/lib/dependabot/cargo/file_fetcher/config_fetcher.rb]: I'm not sure if passing the parent (fetcher) into the child (config fetcher) is necessary or the best approach here. If there’s a strong reason for this design, could you provide some context? Also, is there a reason this class is defined in a separate file rather than being embedded within the file_fetcher itself?

**Review by kbukum1 — APPROVED** [review]
LGTM
