### PR TITLE
fix(terraform): update `less-than`/`less-than/equals` version constraints

### LINKED ISSUE #8959: Terraform manager applies non-existent version number when using less-than/equals (`<=`)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Terraform

### Package manager version

_No response_

### Language version

_No response_

### Manifest location and content before the Dependabot update

[/edbterraform/data/terraform/versions.tf](https://github.com/EnterpriseDB/edb-terraform/blob/8add4fbcdd99dd660ffc74591fc42941cd94839f/edbterraform/data/terraform/versions.tf)

### dependabot.yml content

```yaml
version: 2

updates:
# Terraform - One entry per directory we want to scan as per https://github.com/dependabot/dependabot-core/issues/649
  - package-ecosystem: "terraform"
    directory: "/edbterraform/data/terraform"
    schedule:
      interval: "weekly"
    labels:
      - "dependency"
      - "terraform"
      - "dependabot"
```

### Updated dependency

EnterpriseDB/biganimal `v0.6.1` -> `v0.7.1`

### What you expected to see, versus what you actually saw

The wrong patch number is applied while using less than/equals, `<=`, constraint.
The minor and patch version should both be updated since the dependabot logs show the latest provider as `0.7.0`, which is the latest release [as of 2024-01-12](https://github.com/EnterpriseDB/terraform-provider-biganimal/releases/tag/v0.7.0).
This bug report was created 2024-02-02.

Expected:
`<= 0.6.1` -> `<= 0.7.0`

Result:
`<= 0.6.1` -> `<= 0.7.1`

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

Pull Request: https://github.com/EnterpriseDB/edb-terraform/pull/109
PR title: `Update EnterpriseDB/biganimal requirement from <= 0.6.1 to <= 0.7.1 in /edbterraform/data/terraform`

Dependabot Logs:
```shell
updater | 2024/02/02 06:32:19 INFO <job_781986058> Starting job processing
updater | 2024/02/02 06:32:19 INFO <job_781986058> Starting PR update job for EnterpriseDB/edb-terraform
updater | 2024/02/02 06:32:19 INFO <job_781986058> Checking if EnterpriseDB/biganimal  needs updating
  proxy | 2024/02/02 06:32:20 [012] GET https://registry.terraform.io:443/.well-known/terraform.json
  proxy | 2024/02/02 06:32:20 [012] 200 https://registry.terraform.io:443/.well-known/terraform.json
  proxy | 2024/02/02 06:32:20 [016] GET https://registry.terraform.io:443/v1/providers/EnterpriseDB/biganimal/versions
  proxy | 2024/02/02 06:32:20 [016] 200 https://registry.terraform.io:443/v1/providers/EnterpriseDB/biganimal/versions
updater | 2024/02/02 06:32:20 INFO <job_781986058> Latest version is 0.7.0
updater | 2024/02/02 06:32:20 INFO <job_781986058> Requirements to unlock own
updater | 2024/02/02 06:32:20 INFO <job_781986058> Requirements update strategy 
updater | 2024/02/02 06:32:20 INFO <job_781986058> Updating EnterpriseDB/biganimal from  to 0.7.0
updater | 2024/02/02 06:32:20 INFO <job_781986058> Submitting EnterpriseDB/biganimal pull request for update
updater | 2024/02/02 06:32:20 INFO <job_781986058> Finished job processing
updater | 2024/02/02 06:32:20 INFO Results:
updater | +-----------------------------------------------------+
updater | |         Changes to Dependabot Pull Requests         |
updater | +---------+-------------------------------------------+
updater | | updated | EnterpriseDB/biganimal ( from  to 0.7.0 ) |
updater | +---------+-------------------------------------------+
```

Dependabot PR changelog:
image
Commit:
image

### Smallest manifest that reproduces the issue

```hcl
terraform {
  required_providers {

    biganimal = {
      source = "registry.terraform.io/EnterpriseDB/biganimal"
      version = "<= 0.6.1"
    }

    toolbox = {
      source = "registry.terraform.io/bryan-bar/toolbox"
      version = "<= 0.2.2"
    }

    aws = {
      source = "registry.terraform.io/hashicorp/aws"
      version = "<= 5.34.0"
    }

    azurerm = {
      source = "registry.terraform.io/hashicorp/azurerm"
      version = "<= 3.89.0"
    }

    google = {
      source = "registry.terraform.io/hashicorp/google"
      version = "<= 5.14.0"
    }

    kubernetes = {
      source = "registry.terraform.io/hashicorp/kubernetes"
      version = "<= 2.25.2"
    }

    null = {
      source = "registry.terraform.io/hashicorp/null"
      version = "<= 3.2.2"
    }

    time = {
      source = "registry.terraform.io/hashicorp/time"
      version = "<= 0.10.0"
    }

    local = {
      source = "registry.terraform.io/hashicorp/local"
      version = "<= 2.4.1"
    }

    random = {
      source = "registry.terraform.io/hashicorp/random"
      version = "<= 3.6.0"
    }

    tls = {
      source = "registry.terraform.io/hashicorp/tls"
      version = "<= 4.0.5"
    }

  }
}
```

### PR DESCRIPTION
**Pull request by bryan-bar**
Issue:
When using the terraform dependency constraints `less-than` or `less-than/equals` to set a max version, only the largest semvar version number is updated. This allows the provider version to be set to a non-existent version.

example: 
Latest provider version: `0.7.0`
Provider version suggested changed: `0.6.1` -> `0.7.1`

fixes #8959

---

Fix:
Update each version index to tighten the constraints:
- `less-than/equals` allows provider versions up to the latest version or latest requirement
- `less-than` allows for a provider version up the latest minus 1 against the smallest defined semvar number.

### CODE REVIEW

**Comment by bryan-bar** [comment]
Hello @caspermeijn @bdragon @sachin-sandhu,

If I could get a reviewer set on this PR or comments on how to move forward with this fix please.

It is similar to the versioning issue with cargo in PR#9828

**Comment by abdulapopoola** [comment]
Thanks @bryan-bar , can you please resolve the conflicts and we can get this merged. Thanks for fixing this.

File: terraform/spec/dependabot/terraform/requirements_updater_spec.rb [hunk 1]
```diff
@@ -76,6 +76,30 @@
...
+          let(:requirement) { "<= #{latest_version}" }
+          it { is_expected.to eq(requirements.first) }
+        end
+
+        context "that is not satisfied" do
+          let(:requirement) { "<= 0.1.9" }
+          its([:requirement]) { is_expected.to eq("<= #{latest_version}") }
+
+          context "specifying two digits" do
+            let(:requirement) { "<= #{latest_version.to_s[0, 3]}" }
```
Comment (caspermeijn) [inline terraform/spec/dependabot/terraform/requirements_updater_spec.rb:90]: Personally, I would not use `#{latest_version}` in these tests, as it makes the test harder to read. Especially when you strip some string, it is not directly clear what is going on. So I suggest to explicitly writing out the requirements.

File: terraform/spec/dependabot/terraform/requirements_updater_spec.rb [hunk 2]
```diff
@@ -85,7 +109,13 @@
         context "that is not satisfied" do
           let(:requirement) { ">= 0.2.1, < 0.3.0" }
           let(:latest_version) { "0.3.7" }
-          its([:requirement]) { is_expected.to eq(">= 0.2.1, < 0.4.0") }
+          its([:requirement]) { is_expected.to eq(">= 0.2.1, < 0.3.7") }
```
Comment (caspermeijn) [inline terraform/spec/dependabot/terraform/requirements_updater_spec.rb:112]: This requirement excludes the latest version. Is that what you meant to do?

File: terraform/lib/dependabot/terraform/requirements_updater.rb [hunk 3]
```diff
@@ -157,17 +157,8 @@ def update_greatest_version(requirement, version_to_be_permitted)
...
-
         new_segments = version.segments.map.with_index do |_, index|
-          if index < index_to_update
-            version_to_be_permitted.segments[index]
-          elsif index == index_to_update
-            version_to_be_permitted.segments[index] + 1
-          else
-            0
-          end
+          version_to_be_permitted.segments[index]
```
Comment (caspermeijn) [inline terraform/lib/dependabot/terraform/requirements_updater.rb:161]: I believe the original implementation of `update_greatest_version` was correct for "<" requirements, but "<=" requirements need to be handles differently. 

This is what I did for cargo: https://github.com/dependabot/dependabot-core/blob/4f2cfb565c839895e28bea5977e4fdfb0dbdfc78/cargo/lib/dependabot/cargo/update_checker/requirements_updater.rb#L134-L147

I think you need to focus on `update_range` for handling "<" and "<=" differently.

**Comment by Zawadidone** [comment]
@bryan-bar are you working on this PR?

File: terraform/spec/dependabot/terraform/requirements_updater_spec.rb (hunk 2 above)
Comment (bryan-bar) [reply terraform/spec/dependabot/terraform/requirements_updater_spec.rb:112]: No, it should be `< 0.3.8`, good catch.

**Comment by bryan-bar** [comment]
> @bryan-bar are you working on this PR?

Yes, thanks for the reminder. I just updated the PR.

File: terraform/lib/dependabot/terraform/requirements_updater.rb (hunk 3 above)
Comment (bryan-bar) [reply terraform/lib/dependabot/terraform/requirements_updater.rb]: @caspermeijn 
The less-than operator should still be incremented. I updated the PR to handle both `<` and `<=`.

The issue with the function is that `<` also returned inconsistent version so I chose to update it.
For example, `< 0.3.0` with a latest version of `0.3.7` would return as `< 0.4.0`
Change the initial version to `< 0.3.2` with a latest version of `0.3.7` and the returned version changed to `< 0.3.8`

It seems `index_to_update`, which could lead to the wrong index being incremented and then anything after is set to `0`.

Another issue is that terraform does not have wild cards and it also did not expand the version like it does for some of cargos operators.
For less-than/greater, that would mean incrementing the version and then restricting it (example assuming new version of `1.6.5` -> `<=1.7, !=1.7`) or expanding the version as is ( `<= 1.6.5`).

Comment (bryan-bar) [reply terraform/lib/dependabot/terraform/requirements_updater.rb]: @caspermeijn @abdulapopoola 
To add, Terraform treats non-semantic versions as being expanded out internally. `0.2` == `0.2.0` | `1` == `1.0.0`
I added this comment in the code as well.

File: terraform/lib/dependabot/terraform/requirements_updater.rb [hunk 4]
```diff
@@ -190,17 +190,20 @@ def update_greatest_version(requirement, version_to_be_permitted)
...
 
-        index_to_update =
-          version.segments.map.with_index { |seg, i| seg.zero? ? 0 : i }.max
-
-        new_segments = version.segments.map.with_index do |_, index|
-          if index < index_to_update
+        # When 'less than'/'<',
+        # increment the last available segment only so that the new version is within the constraint
+        if op == "<"
+          new_segments = version.segments.map.with_index do |_, index|
```
Comment (caspermeijn) [inline terraform/lib/dependabot/terraform/requirements_updater.rb:196]: I don't fully understand why the old code was not sufficient. Does the old code fail the new tests?

The new code is simpler and seems to do the trick.

**Review by caspermeijn — COMMENTED** [review]
Great, that you can make this work with a simple code addition. I like the additional tests. 

The code looks good to me. I don't have any terraform experience, so I can't confirm this is the behavior that is required for terraform.

File: terraform/lib/dependabot/terraform/requirements_updater.rb (hunk 4 above)
Comment (bryan-bar) [reply terraform/lib/dependabot/terraform/requirements_updater.rb:196]: Yes, specifically the test that fails in relation to the `less-than`/`<` operator is this test since it jumps a minor version to `0.4.0` instead of incrementing the patch version when set to 0, `">= 0.2.1, < 0.3.0, <= 0.3.0"`:
```
        context "when not satisfied, 0 patch version" do
          let(:requirement) { ">= 0.2.1, < 0.3.0, <= 0.3.0" }
          let(:latest_version) { "0.3.7" }

          its([:requirement]) { is_expected.to eq(">= 0.2.1, < 0.3.8, <= 0.3.7") }
        end
```
Error:
```
  17) Dependabot::Terraform::RequirementsUpdater#updated_requirements when there is a latest version when a =>,<,<= requirement was previously specified when not satisfied, 0 patch version [:requirement] is expected to eq ">= 0.2.1, < 0.3.8, <= 0.3.7"
      Failure/Error: its([:requirement]) { is_expected.to eq(">= 0.2.1, < 0.3.8, <= 0.3.7") }
      
        expected: ">= 0.2.1, < 0.3.8, <= 0.3.7"
             got: ">= 0.2.1, < 0.4.0, <= 0.4.0"
      
        (compared using ==)
      # ./spec/dependabot/terraform/requirements_updater_spec.rb:134:in `block (6 levels) in <top (required)>'
      # /home/dependabot/common/spec/spec_helper.rb:66:in `block (2 levels) in <top (required)>'
      # /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
```
---
This revealed a second issue where a non-zero patch would be incremented as expected, besides the original `<=` issue, if the patch version was set to a non-zero version, `">= 0.2.1, < 0.3.2, <= 0.3.2"`:
```
        context "when not satisfied, non-0 patch version" do
          let(:requirement) { ">= 0.2.1, < 0.3.2, <= 0.3.2" }
          let(:latest_version) { "0.3.7" }

          its([:requirement]) { is_expected.to eq(">= 0.2.1, < 0.3.8, <= 0.3.7") }
        end
```
Error:
```
  16) Dependabot::Terraform::RequirementsUpdater#updated_requirements when there is a latest version when a =>,<,<= requirement was previously specified when not satisfied, non-0 patch version [:requirement] is expected to eq ">= 0.2.1, < 0.3.8, <= 0.3.7"
      Failure/Error: its([:requirement]) { is_expected.to eq(">= 0.2.1, < 0.3.8, <= 0.3.7") }
      
        expected: ">= 0.2.1, < 0.3.8, <= 0.3.7"
             got: ">= 0.2.1, < 0.3.8, <= 0.3.8"
      
        (compared using ==)
      # ./spec/dependabot/terraform/requirements_updater_spec.rb:141:in `block (6 levels) in <top (required)>'
      # /home/dependabot/common/spec/spec_helper.rb:66:in `block (2 levels) in <top (required)>'
      # /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
```

**Comment by bryan-bar** [comment]
> Great, that you can make this work with a simple code addition. I like the additional tests.
> 
> The code looks good to me. I don't have any terraform experience, so I can't confirm this is the behavior that is required for terraform.

Who would be the proper person to tag for this PR?

**Comment by abdulapopoola** [comment]
Thanks @bryan-bar , I'm tagging @randhircs  so we can review this week and deploy it if it meets the bar.

**Review by randhircs — APPROVED** [review]
