### PR TITLE
Maven: Ignore repositories from profiles that are not activated

### LINKED ISSUE #14148: Updates being proposed from repositories defined only in optional profiles
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Maven

### Package manager version

_No response_

### Language version

_No response_

### Manifest location and content before the Dependabot update

_No response_

### dependabot.yml content

For example

```yaml
version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
```

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

@jenkinsci has observed a recent change in Dependabot behavior which I suspect is due to https://github.com/dependabot/dependabot-core/pull/13747 and which is a serious regression tracked in https://github.com/jenkins-infra/helpdesk/issues/4990: updates are being offered for a repository defined only in an [optional profile](https://github.com/jenkinsci/plugin-pom/blob/999f813cd6c325282a7a4962d67fb8a5d78e8469/pom.xml#L1410-L1431) which was never intended to be visible to Dependabot and which previously was not.

Initially I thought the problem was limited to a specific artifact, a parent POM, but I just saw the same behavior in a private repository inheriting the same profile but referring to an artifact used as a regular dependency.

### Native package manager behavior

`mvn versions:display-dependency-updates` offers only versions coming from repositories which are actually active.

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

I can try to put together a minimal test case if that would be helpful in understanding the problem. Initially observed in a large batch of PRs such as https://github.com/jenkinsci/mailer-plugin/pull/616. You will note that `mvn validate` fails now in the `master` branch of that repo.

### PR DESCRIPTION
**Pull request by yeikel**
### What are you trying to accomplish?

In #13747, we updated Dependabot to consider all repositories defined in a project rather than only the first match. 

Unfortunately, this revealed a gap in Dependabot’s repository parsing: repositories that were expected to be disabled via Maven profiles were still being extracted. As a result, Dependabot started to query repositories that users had explicitly disabled in their Maven configuration leading to unexpected updates

With this change, we now respect the user’s configuration and only include repositories that are:

1. Defined at the top level of the project
2. Defined in profiles that are explicitly activated

Profiles that are explicitly deactivated, or that lack activation configuration, are treated as disabled to match native Maven behavior.

Fixes #14148

### Anything you want to highlight for special attention from reviewers?

The diff looks larger than it is because I had to reduce the code complexity as per  `rubocop`

#### Both new and existing spec pass

The new specs focused on parsing the profile and show how it should ignore profiles that are not activated

#### Validated using the provided reproducer

I ran this version against the reproducer documented in #14148 and produces the expected output (only `https://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/mock-slave/` is consulted)

<details>
  <summary>Logs</summary>
  
```
    cli | 2026/02/11 01:22:18 Inserting $LOCAL_GITHUB_ACCESS_TOKEN into credentials
    cli | 2026/02/11 01:22:19 image ghcr.io/dependabot/proxy:latest is already up to date
    cli | 2026/02/11 01:22:19 using image ghcr.io/dependabot/proxy:latest at sha256:01973f1077a283381e979987aae6e70fbe1104f04186863985539e4d2472f019
    cli | 2026/02/11 01:22:19 digest sha256:ce2b5f94e3b0ea3ac519c6fe593a2e3a7200100e7e7283f1ab92dbefefe4b8e4 for image ghcr.io/dependabot/dependabot-updater-maven does not exist remotely
  proxy | 2026/02/11 01:22:20 proxy starting, commit: c1aef7567fe8d0d42a65ac01dd05b2504af53a3b
  proxy | 2026/02/11 01:22:20 Listening (:1080)
updater | Updating certificates in /etc/ssl/certs...
updater | rehash: warning: skipping ca-certificates.crt,it does not contain exactly one certificate or CRL
updater | 1 added, 0 removed; done.
updater | Running hooks in /etc/ca-certificates/update.d...
updater | Processing triggers for ca-certificates-java (20240118) ...
updater | Adding debian:dbot-ca.pem
updater | done.
updater | done.
updater | fetch_files command is no longer used directly
updater | 2026/02/11 01:22:33 INFO Starting job processing
updater | 2026/02/11 01:22:33 INFO Job definition: {"job":{"command":"version","package-manager":"maven","allowed-updates":[{"dependency-type":"direct","update-type":"all"}],"debug":false,"dependency-groups":[],"dependencies":null,"dependency-group-to-refresh":null,"existing-pull-requests":[],"existing-group-pull-requests":[],"experiments":{"allow-refresh-for-existing-pr-dependencies":true,"allow-refresh-group-with-all-dependencies":true,"avoid-duplicate-updates-package-json":true,"deprecate-cancel-merge-command":true,"deprecate-close-command":true,"deprecate-merge-command":true,"deprecate-reopen-command":true,"deprecate-squash-merge-command":true,"disable-cancel-merge-command":true,"disable-close-command":true,"disable-merge-command":true,"disable-reopen-command":true,"disable-squash-merge-command":true,"enable-corepack-for-npm-and-yarn":true,"enable-dependabot-setting-up-cronjob":true,"enable-engine-version-detection":true,"enable-enhanced-error-details-for-updater":true,"enable-exclude-paths-subdirectory-manifest-files":true,"enable-private-registry-for-corepack":true,"enable-record-ecosystem-meta":true,"enable-shared-helpers-command-timeout":true,"gradle-lockfile-updater":true,"gradle-wrapper-updater":true,"group-membership-enforcement":true,"proxy-cached":true,"record-ecosystem-versions":true,"record-update-job-unknown-error":true},"ignore-conditions":[],"lockfile-only":false,"requirements-update-strategy":null,"security-advisories":[],"security-updates-only":false,"source":{"provider":"github","repo":"jglick/dependabot-14148-demo","directory":"/.","hostname":"github.com","api-endpoint":"https://api.github.com/"},"update-subdependencies":false,"updating-a-pull-request":false,"vendor-dependencies":false,"reject-external-code":false,"repo-private":false,"commit-message-options":{},"credentials-metadata":[{"host":"github.com","type":"git_source"}],"max-updater-run-time":2700,"exclude-paths":null,"multi-ecosystem-update":false}}
updater | 2026/02/11 01:22:33 INFO Started process PID: 1132 with command: {} git config --global credential.helper '!/home/dependabot/common/lib/dependabot/../../bin/git-credential-store-immutable --file /home/dependabot/dependabot-updater/git.store' {}
updater | 2026/02/11 01:22:33 INFO Process PID: 1132 completed with status: pid 1132 exit 0
updater | 2026/02/11 01:22:33 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:33 INFO Started process PID: 1141 with command: {} git config --global --replace-all url.https://github.com/.insteadOf ssh://git@github.com/ {}
updater | 2026/02/11 01:22:33 INFO Process PID: 1141 completed with status: pid 1141 exit 0
updater | 2026/02/11 01:22:33 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:33 INFO Started process PID: 1149 with command: {} git config --global --add url.https://github.com/.insteadOf ssh://git@github.com: {}
updater | 2026/02/11 01:22:33 INFO Process PID: 1149 completed with status: pid 1149 exit 0
updater | 2026/02/11 01:22:33 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:33 INFO Started process PID: 1157 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com: {}
updater | 2026/02/11 01:22:33 INFO Process PID: 1157 completed with status: pid 1157 exit 0
updater | 2026/02/11 01:22:33 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:33 INFO Started process PID: 1164 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com/ {}
updater | 2026/02/11 01:22:33 INFO Process PID: 1164 completed with status: pid 1164 exit 0
updater | 2026/02/11 01:22:33 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:33 INFO Started process PID: 1171 with command: {} git config --global --add url.https://github.com/.insteadOf git://github.com/ {}
updater | 2026/02/11 01:22:33 INFO Process PID: 1171 completed with status: pid 1171 exit 0
updater | 2026/02/11 01:22:33 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:33 INFO Started process PID: 1178 with command: {} git config --global --replace-all url.https://github.com/.insteadOf ssh://git@github.com/ {}
updater | 2026/02/11 01:22:33 INFO Process PID: 1178 completed with status: pid 1178 exit 0
updater | 2026/02/11 01:22:33 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:33 INFO Started process PID: 1185 with command: {} git config --global --add url.https://github.com/.insteadOf ssh://git@github.com: {}
updater | 2026/02/11 01:22:33 INFO Process PID: 1185 completed with status: pid 1185 exit 0
updater | 2026/02/11 01:22:33 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:33 INFO Started process PID: 1192 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com: {}
updater | 2026/02/11 01:22:33 INFO Process PID: 1192 completed with status: pid 1192 exit 0
updater | 2026/02/11 01:22:33 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:33 INFO Started process PID: 1200 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com/ {}
updater | 2026/02/11 01:22:33 INFO Process PID: 1200 completed with status: pid 1200 exit 0
updater | 2026/02/11 01:22:33 INFO Total execution time: 0.02 seconds
updater | 2026/02/11 01:22:33 INFO Started process PID: 1207 with command: {} git config --global --add url.https://github.com/.insteadOf git://github.com/ {}
updater | 2026/02/11 01:22:33 INFO Process PID: 1207 completed with status: pid 1207 exit 0
updater | 2026/02/11 01:22:33 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:33 INFO Started process PID: 1214 with command: {} git clone --no-tags --depth 1 --recurse-submodules --shallow-submodules https://github.com/jglick/dependabot-14148-demo /home/dependabot/dependabot-updater/repo {}
  proxy | 2026/02/11 01:22:33 [002] GET https://github.com:443/jglick/dependabot-14148-demo/info/refs?service=git-upload-pack
  proxy | 2026/02/11 01:22:33 [002] * authenticating git server request (host: github.com)
  proxy | 2026/02/11 01:22:34 [002] 200 https://github.com:443/jglick/dependabot-14148-demo/info/refs?service=git-upload-pack
  proxy | 2026/02/11 01:22:34 [004] POST https://github.com:443/jglick/dependabot-14148-demo/git-upload-pack
  proxy | 2026/02/11 01:22:34 [004] * authenticating git server request (host: github.com)
  proxy | 2026/02/11 01:22:34 [004] 200 https://github.com:443/jglick/dependabot-14148-demo/git-upload-pack
  proxy | 2026/02/11 01:22:34 [006] POST https://github.com:443/jglick/dependabot-14148-demo/git-upload-pack
  proxy | 2026/02/11 01:22:34 [006] * authenticating git server request (host: github.com)
  proxy | 2026/02/11 01:22:34 [006] 200 https://github.com:443/jglick/dependabot-14148-demo/git-upload-pack
updater | 2026/02/11 01:22:34 INFO Process PID: 1214 completed with status: pid 1214 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.79 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1254 with command: {} git -C /home/dependabot/dependabot-updater/repo ls-files --stage {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1254 completed with status: pid 1254 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1271 with command: {} git config --global credential.helper '!/home/dependabot/common/lib/dependabot/../../bin/git-credential-store-immutable --file /home/dependabot/dependabot-updater/git.store' {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1271 completed with status: pid 1271 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1279 with command: {} git config --global --replace-all url.https://github.com/.insteadOf ssh://git@github.com/ {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1279 completed with status: pid 1279 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1286 with command: {} git config --global --add url.https://github.com/.insteadOf ssh://git@github.com: {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1286 completed with status: pid 1286 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1293 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com: {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1293 completed with status: pid 1293 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1300 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com/ {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1300 completed with status: pid 1300 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1307 with command: {} git config --global --add url.https://github.com/.insteadOf git://github.com/ {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1307 completed with status: pid 1307 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1314 with command: {} git config --global --replace-all url.https://github.com/.insteadOf ssh://git@github.com/ {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1314 completed with status: pid 1314 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1321 with command: {} git config --global --add url.https://github.com/.insteadOf ssh://git@github.com: {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1321 completed with status: pid 1321 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1328 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com: {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1328 completed with status: pid 1328 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1335 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com/ {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1335 completed with status: pid 1335 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1342 with command: {} git config --global --add url.https://github.com/.insteadOf git://github.com/ {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1342 completed with status: pid 1342 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1350 with command: {} git rev-parse HEAD {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1350 completed with status: pid 1350 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1365 with command: {} git config --global credential.helper '!/home/dependabot/common/lib/dependabot/../../bin/git-credential-store-immutable --file /home/dependabot/dependabot-updater/git.store' {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1365 completed with status: pid 1365 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1373 with command: {} git config --global --replace-all url.https://github.com/.insteadOf ssh://git@github.com/ {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1373 completed with status: pid 1373 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1380 with command: {} git config --global --add url.https://github.com/.insteadOf ssh://git@github.com: {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1380 completed with status: pid 1380 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1387 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com: {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1387 completed with status: pid 1387 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1394 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com/ {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1394 completed with status: pid 1394 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1402 with command: {} git config --global --add url.https://github.com/.insteadOf git://github.com/ {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1402 completed with status: pid 1402 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1409 with command: {} git config --global --replace-all url.https://github.com/.insteadOf ssh://git@github.com/ {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1409 completed with status: pid 1409 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1416 with command: {} git config --global --add url.https://github.com/.insteadOf ssh://git@github.com: {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1416 completed with status: pid 1416 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1424 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com: {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1424 completed with status: pid 1424 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1431 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com/ {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1431 completed with status: pid 1431 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1438 with command: {} git config --global --add url.https://github.com/.insteadOf git://github.com/ {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1438 completed with status: pid 1438 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO Started process PID: 1445 with command: {} git rev-parse HEAD {}
updater | 2026/02/11 01:22:34 INFO Process PID: 1445 completed with status: pid 1445 exit 0
updater | 2026/02/11 01:22:34 INFO Total execution time: 0.01 seconds
updater | 2026/02/11 01:22:34 INFO DEBUG filter_excluded: entries=4, exclude_paths=[]
updater | 2026/02/11 01:22:34 INFO Base commit SHA: 86efedd3ca70f02b7220af511074547036385bb8
updater | 2026/02/11 01:22:34 INFO Finished job processing
updater | 2026/02/11 01:22:34 INFO Starting job processing
  proxy | 2026/02/11 01:22:34 [007] POST http://host.docker.internal:59308/update_jobs/cli/update_dependency_list
{"data":{"dependencies":[{"name":"org.jenkins-ci.plugins:mock-slave","requirements":[{"file":"pom.xml","groups":[],"metadata":{"packaging_type":"jar"},"requirement":"193.v88c279d0c584","source":null}],"version":"193.v88c279d0c584"}],"dependency_files":["/pom.xml"]},"type":"update_dependency_list"}
  proxy | 2026/02/11 01:22:34 [007] 200 http://host.docker.internal:59308/update_jobs/cli/update_dependency_list
  proxy | 2026/02/11 01:22:34 [008] POST http://host.docker.internal:59308/update_jobs/cli/increment_metric
{"data":{"metric":"updater.started","tags":{"operation":"group_update_all_versions"}},"type":"increment_metric"}
  proxy | 2026/02/11 01:22:34 [008] 200 http://host.docker.internal:59308/update_jobs/cli/increment_metric
updater | 2026/02/11 01:22:34 INFO Starting update job for jglick/dependabot-14148-demo
updater | 2026/02/11 01:22:34 INFO Checking all dependencies for version updates...
updater | 2026/02/11 01:22:34 INFO Checking if org.jenkins-ci.plugins:mock-slave 193.v88c279d0c584 needs updating
  proxy | 2026/02/11 01:22:34 [010] GET https://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/mock-slave/maven-metadata.xml
  proxy | 2026/02/11 01:22:35 [010] 200 https://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/mock-slave/maven-metadata.xml
  proxy | 2026/02/11 01:22:35 [012] GET https://repo.maven.apache.org/maven2/org/jenkins-ci/plugins/mock-slave/maven-metadata.xml
  proxy | 2026/02/11 01:22:35 [012] 404 https://repo.maven.apache.org/maven2/org/jenkins-ci/plugins/mock-slave/maven-metadata.xml
  proxy | 2026/02/11 01:22:36 [014] GET https://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/mock-slave
  proxy | 2026/02/11 01:22:36 [014] 302 https://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/mock-slave
  proxy | 2026/02/11 01:22:36 [016] GET https://repo.jenkins-ci.org/artifactory/public/org/jenkins-ci/plugins/mock-slave/
  proxy | 2026/02/11 01:22:36 [016] 200 https://repo.jenkins-ci.org/artifactory/public/org/jenkins-ci/plugins/mock-slave/
  proxy | 2026/02/11 01:22:36 [018] GET https://repo.maven.apache.org/maven2/org/jenkins-ci/plugins/mock-slave
  proxy | 2026/02/11 01:22:36 [018] 404 https://repo.maven.apache.org/maven2/org/jenkins-ci/plugins/mock-slave
updater | 2026/02/11 01:22:36 INFO Filtered out 1 pre-release versions
updater | 2026/02/11 01:22:36 INFO Filtered out 5 non-v88c279d0c584 classifier versions
  proxy | 2026/02/11 01:22:36 [020] HEAD https://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/mock-slave/193.v88c279d0c584/mock-slave-193.v88c279d0c584.jar
  proxy | 2026/02/11 01:22:36 [020] 200 https://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/mock-slave/193.v88c279d0c584/mock-slave-193.v88c279d0c584.jar
updater | 2026/02/11 01:22:36 INFO Latest version is 193.v88c279d0c584
updater | 2026/02/11 01:22:36 INFO Filtered out 1 pre-release versions
updater | 2026/02/11 01:22:36 INFO Filtered out 5 non-v88c279d0c584 classifier versions
updater | 2026/02/11 01:22:36 INFO Filtered out 1 pre-release versions
updater | 2026/02/11 01:22:36 INFO Filtered out 5 non-v88c279d0c584 classifier versions
updater | 2026/02/11 01:22:36 INFO Filtered out 1 pre-release versions
updater | 2026/02/11 01:22:36 INFO Filtered out 5 non-v88c279d0c584 classifier versions
updater | 2026/02/11 01:22:36 INFO No update needed for org.jenkins-ci.plugins:mock-slave 193.v88c279d0c584
  proxy | 2026/02/11 01:22:36 [021] POST http://host.docker.internal:59308/update_jobs/cli/record_ecosystem_meta
{"data":[{"ecosystem":{"name":"maven","package_manager":{"name":"maven","version":"NOT-AVAILABLE","raw_version":"NOT-AVAILABLE"},"language":{"name":"java","version":"NOT-AVAILABLE","raw_version":"NOT-AVAILABLE"}}}],"type":"record_ecosystem_meta"}
  proxy | 2026/02/11 01:22:36 [021] 200 http://host.docker.internal:59308/update_jobs/cli/record_ecosystem_meta
  proxy | 2026/02/11 01:22:36 [022] PATCH http://host.docker.internal:59308/update_jobs/cli/mark_as_processed
{"data":{"base-commit-sha":"86efedd3ca70f02b7220af511074547036385bb8"},"type":"mark_as_processed"}
  proxy | 2026/02/11 01:22:36 [022] 200 http://host.docker.internal:59308/update_jobs/cli/mark_as_processed
updater | 2026/02/11 01:22:36 INFO Finished job processing
  proxy | 2026/02/11 01:22:37 Skipping sending metrics because api endpoint is empty
  proxy | 2026/02/11 01:22:37 0/9 calls cached (0%)
```

  
</details>

### Checklist

- [x] I have run the complete test suite to ensure all tests and linters pass.
- [x] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [x] I have written clear and descriptive commit messages.
- [x] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [x] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

File: maven/spec/dependabot/maven/file_parser/repositories_finder_spec.rb [hunk 1]
```diff
@@ -348,5 +348,21 @@
...
+      let(:base_pom_fixture_name) { "custom_repositories_pom_with_profiles.xml" }
+
+      it "does not include repositories from profiles that are not activated by default" do
+        expect(repository_urls).to eq(
+          %w(
+            https://repo.jenkins-ci.org/public
+            https://repo.jenkins-ci.org/incrementals-activated
+            https://repo.jenkins-ci.org/incrementals-activated-2
+            https://repo.jenkins-ci.org/another-activated
+            https://repo.maven.apache.org/maven2
```
Comment (jglick) [inline maven/spec/dependabot/maven/file_parser/repositories_finder_spec.rb:362]: Looks right.

**Comment by yeikel** [comment]
@kbukum1 Could you please review this?

**Comment by v-kbukum1** [comment]
Thanks @yeikel — as always, your continued contributions mean a lot. This is deployed! 🚀

**Comment by yeikel** [comment]
> Thanks @yeikel — as always, your continued contributions mean a lot. This is deployed! 🚀

Awesome, thanks!
