### PR TITLE
fix broken updates due to incorrect directory filtering

### LINKED ISSUE #8398: Nuget - No project file or packages.config!
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Nuget 

### Package manager version

_No response_

### Language version

.NET 6/7

### Manifest location and content before the Dependabot update

_No response_

### dependabot.yml content

https://github.com/thomhurst/ModularPipelines/blob/main/.github/dependabot.yml

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

Any updates to be successfully detected and pull requests raised

What actually happened was dependabot fails to run. This has only started today. Runs prior to today were passing fine.

It states no project, but I'm using a working directory with a solution file in it, so it should pick that up.

The error being shown in logs is:
updater | 2023/11/14 22:02:54 INFO <job_749952138> Starting grouped update job for thomhurst/ModularPipelines
updater | 2023/11/14 22:02:54 INFO <job_749952138> Found 3 group(s).
updater | 2023/11/14 22:02:54 INFO <job_749952138> Starting update group for 'aws-dependencies'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> No project file or packages.config!
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/nuget/lib/dependabot/nuget/file_parser.rb:113:in `check_required_files'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/common/lib/dependabot/file_parsers/base.rb:18:in `initialize'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:80:in `new'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:80:in `dependency_file_parser'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:41:in `block in compile_all_dependency_changes_for'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:29:in `each'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:29:in `compile_all_dependency_changes_for'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:44:in `perform'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:114:in `run_update_for'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:96:in `block in run_grouped_dependency_updates'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:95:in `each'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:95:in `run_grouped_dependency_updates'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:45:in `perform'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:39:in `perform_job'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/11/14 22:02:54 ERROR <job_749952138> bin/update_files.rb:24:in `<main>'
updater | 2023/11/14 22:02:54 INFO <job_749952138> Sending event b818f5783a3942009aa32f616433a7f5 to Sentry
  proxy | 2023/11/14 22:02:55 [144] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/11/14 22:02:55 [144] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/11/14 22:02:55 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------+
updater | |    Errors     |
updater | +---------------+
updater | | unknown_error |
updater | +---------------+
updater | time="2023-11-14T22:02:55Z" level=info msg="task complete" container_id=job-749952138-updater exit_code=0 job_id=749952138 step=updater

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

_No response_

### PR DESCRIPTION
**Pull request by jakecoffman**
fixes #8398

In #8331 I introduced filtering files by directory so we could achieve multi-directory updates. This filtering was too naive though as it has broken updates for a few ecosystems that have special handling for directories:

- In NuGet, [src](https://github.com/dependabot/dependabot-core/blob/641de673efbcfb0b92641f7051a7325b473dd44e/nuget/lib/dependabot/nuget/file_fetcher.rb#L98-L102) is used at in some cases
- In GitHub Actions, `.github/workflows` is automatically used if the directory is `/`

And there may be others!

These special cases resulted in the directory of the file being different than the directory of the update (the job's configured directory).

By marking the files fetched with a `job_directory`, we can remove the special cases and the filtering works as expected.

### CODE REVIEW

File: updater/lib/dependabot/file_fetcher_command.rb [hunk 1]
```diff
@@ -97,6 +97,7 @@ def dependency_files_for_multi_directories
         ff = with_retries { file_fetcher_for_directory(dir) }
         files = ff.files
         post_ecosystem_versions(ff) if should_record_ecosystem_versions?
+        files.each { |f| f.job_directory = dir }
```
Comment (deivid-rodriguez) [inline updater/lib/dependabot/file_fetcher_command.rb:100]: Could/should this be set [here](https://github.com/dependabot/dependabot-core/blob/bb7a2eb0998c29180184301611f78d38eec5a37f/common/lib/dependabot/file_fetchers/base.rb#L107) instead, using `FileFetcher#directory`?

Comment (jakecoffman) [reply updater/lib/dependabot/file_fetcher_command.rb:100]: Yep, that works!

File: common/lib/dependabot/file_fetchers/base.rb [hunk 2]
```diff
@@ -105,6 +105,8 @@ def target_branch
       sig { returns(T::Array[DependencyFile]) }
       def files
         @files ||= T.let(fetch_files, T.nilable(T::Array[DependencyFile]))
+        @files.each { |f| f.job_directory = directory }
```
Comment (deivid-rodriguez) [inline common/lib/dependabot/file_fetchers/base.rb:108]: They will be set each time `FileFetcher#files` is used, should it be memoized instead?

File: common/lib/dependabot/dependency_file.rb [hunk 3]
```diff
@@ -66,14 +71,15 @@ class Mode
...
+        mode: T.nilable(String),
+        job_directory: String
       )
         .void
     end
     def initialize(name:, content:, directory: "/", type: "file",
                    support_file: false, vendored_file: false, symlink_target: nil,
                    content_encoding: ContentEncoding::UTF_8, deleted: false,
-                   operation: Operation::UPDATE, mode: nil)
+                   operation: Operation::UPDATE, mode: nil, job_directory: "")
```
Comment (deivid-rodriguez) [inline common/lib/dependabot/dependency_file.rb:82]: Why making the default the empty string instead of `nil`?

**Review by deivid-rodriguez — COMMENTED** [review]
Minor neats, but looking good!

File: common/lib/dependabot/dependency_file.rb (hunk 3 above)
Comment (jakecoffman) [reply common/lib/dependabot/dependency_file.rb:82]: The empty string makes the types simpler instead of a nilable String it's always a String. I don't mind either way.

Comment (deivid-rodriguez) [reply common/lib/dependabot/dependency_file.rb:82]: I prefer a nilable String, and it's already used as a default here for example for `symlink_target`. I would keep it consistent even if it needs to wrap the type with `T.nilable`.

File: common/lib/dependabot/file_fetchers/base.rb [hunk 4]
```diff
@@ -104,7 +104,10 @@ def target_branch
 
       sig { returns(T::Array[DependencyFile]) }
       def files
-        @files ||= T.let(fetch_files, T.nilable(T::Array[DependencyFile]))
+        @files ||= T.let(
+          fetch_files.each { |f| f.job_directory = directory },
```
Comment (deivid-rodriguez) [inline common/lib/dependabot/file_fetchers/base.rb:108]: I can't believe I never realized `Array#each` returns the original array 😲.

**Review by deivid-rodriguez — APPROVED** [review]
Looks great @jakecoffman!

File: common/lib/dependabot/file_fetchers/base.rb (hunk 4 above)
Comment (jakecoffman) [reply common/lib/dependabot/file_fetchers/base.rb:108]: I had to hop into `irb` to check 😁.

At first I tried refactoring to use the `return... if defined?` pattern but the types were having me sprinkle `T.must` everywhere which was quite ugly. This seemed more elegant.
