### PR TITLE
Terraform unknown git repo dependency name

### LINKED ISSUE #4491: Terraform with source type of git results in exception for repos that do not match SOURCE_REGEX in v0.169.3
As a result of the fix for #4392 git sources with unknown repositories based on SOURCE_REGEX in /common/lib/dependabot/source.rb now result in ` undefined method `provider' for nil:NilClass (NoMethodError)`

As an example, aws code commit repos do not have a regex that matches, thus no provider is set and an exception is met

**Package ecosystem**
terraform

As the author of the fix for #4392 I am beginning the fix for this immediately.

### PR DESCRIPTION
**Pull request by dwc0011**
Fixes #4491. 

Since the original issue that I set out to address in [4392](https://github.com/dependabot/dependabot-core/issues/4392) requires unique naming conventions due to valid terraform and we do not have regex to address every single git repo url structure, a generic naming convention is needed when urls are not parsed into sources.

This is a patch to address unknown git repos whose Source.from_url cannot be parsed.  These include AWS CodeCommit and other git repos that do not match on the source regex in [common/lib/dependabot/source.rb](https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/source.rb) and are not a GitHub Enterprise Source, or are an Ignored host.  

In order to create a unique git dependency name the code relies on a parsed Source, in the above cases the object is nil.  I have added url source parsing for AWS CodeCommit, for other un-parseable urls nil is detected, which triggers creating a unique name by using the module name, hardcoded strings, and hash of the url.  The naming convention is similar to parsed sources
`module_name::unknown_provider::repo_name/unknown_name(hash_value)::[ref]`
**module_name** = the name of the terraform module for the git source url
**unknown_provider::repo_name/unknown_name** = a hardcoded string (this is the same for each unknown repo)
**(hash_value)** = Digest::SHA1.hexdigest on the source url
**[ref]** = optional ref

### CODE REVIEW

**Comment by dwc0011** [comment]
In addition to comments on the solution if there are other tests that should be implemented in other providers / directories please point me in the right direction.

**Comment by dwc0011** [comment]
Been doing some other testing with this and so far dry run success is good.  Any review/feedback will be greatly appreciated.

**Comment by dwc0011** [comment]
I am finished with my testing and waiting for code review.

**Comment by jurre** [comment]
Thanks @dwc0011, have added it to our backlog of things to review

**Comment by dwc0011** [comment]
Now that there is a test for dependency name, once it is merged I will need to add the unknow repo name to the test suite.

**Comment by Nishnha** [comment]
Hi @dwc0011,

We recently updated our CI to publish docker built images to GHCR, which requires secrets. Unfortunately, [forked repos do not have access to secrets](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/), so you will need to either re-open this PR on `dependabot/dependabot-core` as a branch to test against our CI or hold off on this until we find a potential solution for forked PRs running our CI suite.

Sorry for the inconvenience.

**Comment by lorengordon** [comment]
Hi @Nishnha, I work with @dwc0011 and he is on holiday this week. Would you be able to push the branch to `dependabot/dependabot-core` yourself and open a new pr?

**Comment by Nishnha** [comment]
> Hi @Nishnha, I work with @dwc0011 and he is on holiday this week. Would you be able to push the branch to `dependabot/dependabot-core` yourself and open a new pr?

ah right, only maintainers can open a branch 😬 
I'll have to do a code review and some manual testing before I open a branch, but I will work towards that end.

Hopefully we can find a satisfactory solution forked PRs soon.

**Comment by lorengordon** [comment]
Heh, yeah, I've run into this problem also. But I couldn't find a reasonable way around it. So I just avoid any use of secrets in the CI for pull requests on public projects. :/

**Comment by mctofu** [comment]
CI for fork PRs was fixed in https://github.com/dependabot/dependabot-core/pull/4569

**Comment by dwc0011** [comment]
> > Hi @Nishnha, I work with @dwc0011 and he is on holiday this week. Would you be able to push the branch to `dependabot/dependabot-core` yourself and open a new pr?
> 
> ah right, only maintainers can open a branch 😬 I'll need to do a code review and some manual testing before I open a branch, but I will work towards that end.
> 
> Hopefully we can find a satisfactory solution for forked PRs soon.

I am back, I see you all figured out a solution and all checks have passed.  Let me know if there are any questions or concerns!  Happy New Year!

File: terraform/spec/dependabot/terraform/file_parser_spec.rb [hunk 1]
```diff
@@ -445,9 +445,17 @@
         end
       end
 
+      before do
+        stub_request(:get, "https://unkown-git-repo-example.com/status").to_return(
```
Comment (Nishnha) [inline terraform/spec/dependabot/terraform/file_parser_spec.rb:449]: nit
```suggestion
        stub_request(:get, "https://unknown-git-repo-example.com/status").to_return(
```

File: terraform/spec/dependabot/terraform/file_parser_spec.rb [hunk 2]
```diff
@@ -570,6 +578,44 @@
...
+              url: "https://git-codecommit.us-east-1.amazonaws.com/v1/repos/test-repo",
+              branch: nil,
+              ref: "0.10.0"
+            }
+          }])
+        end
+
+        it "has the right details for the unknown git repo example" do
+          dependency = subject.find do |x|
+            x.name.include? "unknown_repo::unknown_provider::repo_name/unknown_name("
```
Comment (Nishnha) [inline terraform/spec/dependabot/terraform/file_parser_spec.rb:603]:
```suggestion
            x.name.include? "unknown_repo::git_provider::git_repo("
```

File: terraform/spec/fixtures/projects/git_tags_013/main.tf [hunk 3]
```diff
@@ -29,3 +29,11 @@ module "dns_dup" {
   target_dns_name  = aws_cloudfront_distribution.default.domain_name
   target_zone_id   = aws_cloudfront_distribution.default.hosted_zone_id
 }
+
+module "codecommit_repo" {
+  source           = "git::https://git-codecommit.us-east-1.amazonaws.com/v1/repos/test-repo//modules/test_module?ref=0.10.0"
+}
+
+module "unknown_repo" {
+  source           = "git::https://unkown-git-repo-example.com/reponame/test?ref=1.0.0"
```
Comment (Nishnha) [inline terraform/spec/fixtures/projects/git_tags_013/main.tf:38]: nit
```suggestion
  source           = "git::https://unknown-git-repo-example.com/reponame/test?ref=1.0.0"
```

File: terraform/spec/dependabot/terraform_spec.rb [hunk 4]
```diff
@@ -51,5 +51,19 @@
...
+      end
+
+      it { is_expected.to eq("module_name::unknown_name(9685A3B07E8D9C45BE0A3D92B02F13978FB311D8)") }
+    end
+
+    context "git unknown source without ref" do
+      let(:name) { "module_name::unknown_provider::repo_name/unknown_name(9685A3B07E8D9C45BE0A3D92B02F13978FB311D8)" }
+
+      it { is_expected.to eq("module_name::unknown_name(9685A3B07E8D9C45BE0A3D92B02F13978FB311D8)") }
+    end
```
Comment (Nishnha) [inline terraform/spec/dependabot/terraform_spec.rb:67]: These `display names` are shown in PR titles and might be too long if we include the SHA. 
If we do not know the source maybe we should just use the `module_name`? What do you think?

This would require further modifying the `register_display_name_builder` in https://github.com/dependabot/dependabot-core/blob/main/terraform/lib/dependabot/terraform.rb

File: terraform/spec/dependabot/terraform/file_parser_spec.rb [hunk 5]
```diff
@@ -570,6 +578,44 @@
...
+          end
+          expect(dependency).to_not be_nil
+          expect(dependency.version).to eq("1.0.0")
+          expect(dependency.requirements).to match_array([{
+            requirement: nil,
+            groups: [],
+            file: "main.tf",
+            source: {
+              type: "git",
+              url: "https://unkown-git-repo-example.com/reponame/test",
```
Comment (Nishnha) [inline terraform/spec/dependabot/terraform/file_parser_spec.rb:613]: nit
```suggestion
              url: "https://unknown-git-repo-example.com/reponame/test",
```

**Review by Nishnha — CHANGES_REQUESTED** [review]
Happy new year!

This looks really good overall 👍🏾 

I found a small typo in the word "unknown" and commented with nit.

Another suggestion I have is instead of using `unknown_provider::repo_name/unknown_name` as the provider and repo, we should use `git_provider::git_repo` since it's more descriptive and terse.

**Comment by dwc0011** [comment]
@Nishnha I concur with the recommended changes and will be addressing them shortly

File: terraform/spec/dependabot/terraform_spec.rb (hunk 4 above)
Comment (dwc0011) [reply terraform/spec/dependabot/terraform_spec.rb:67]: I can definitely strip the hash, I just assumed it would truncate it if to long.  It doesn't provide any other function other than uniqueness and I believe PRs can have duplicate titles, can you confirm that is true @Nishnha

Comment (Nishnha) [reply terraform/spec/dependabot/terraform_spec.rb:67]: Yep, PRs can have duplicate titles, and Dependabot uses a unique id (not the title) to interact with PRs anyway.

Removing the hash seems like a good move regardless since we should avoid having an arbitrary SHA in the title of a Dependabot PR. Descriptive is better 😃

File: terraform/lib/dependabot/terraform/file_parser.rb [hunk 6]
```diff
@@ -215,10 +216,15 @@ def registry_source_details_from(source_string)
...
       def git_dependency_name(name, source)
         git_source = Source.from_url(source[:url])
-        if source[:ref]
+        if git_source && source[:ref]
           name + "::" + git_source.provider + "::" + git_source.repo + "::" + source[:ref]
-        else
+        elsif git_source
           name + "::" + git_source.provider + "::" + git_source.repo
+        elsif source[:ref]
+          name + "::unknown_provider::repo_name/unknown_name(" \
```
[the remark this answers is not in the document]
Comment (dwc0011) [reply terraform/lib/dependabot/terraform/file_parser.rb:224]: I am changing this to "git_provider::repo_name/git_repo" so it is the same naming format as known git repos.  The register_display_name_builder splits on the "/"  I could do more checks in that function but I want to simplify that.

[the remark this answers is not in the document]
Comment (Nishnha) [reply terraform/lib/dependabot/terraform/file_parser.rb:224]: sounds good

File: terraform/lib/dependabot/terraform/file_parser.rb [hunk 7]
```diff
@@ -215,10 +216,15 @@ def registry_source_details_from(source_string)
...
+          + Digest::SHA1.hexdigest(source[:url]) + ")::" + source[:ref]
```
[the remark this answers is not in the document]
Comment (dwc0011) [reply terraform/lib/dependabot/terraform/file_parser.rb:225]: Just confirming you are validating this will work and not suggesting anything different, correct?

[the remark this answers is not in the document]
Comment (Nishnha) [reply terraform/lib/dependabot/terraform/file_parser.rb:225]: Correct. That comment is just to explain why we're using a SHA1 digest :)

**Comment by dwc0011** [comment]
@Nishnha I believe I addressed all of the changes, I had some git rebase issues and I fixed them the best I can.  Something has changed in my ruby environment so I can't run the tests locally so that is why there were so many CI runs.  I get a new dev laptop tomorrow so didn't want to try and fix it on this machine.

**Comment by Nishnha** [comment]
Great work on this @dwc0011 
This will be released with our next version of Dependabot-Core, which should happen within the next few days!

**Comment by dwc0011** [comment]
> Great work on this @dwc0011 This will be released with our next version of Dependabot-Core, which should happen within the next few days!

Thanks @Nishnha  I appreciate the kind words.  Look forward to the release!
