### PR TITLE
python: Handle explicit PyPI source in pyproject.toml

### LINKED ISSUE #7431: Poetry 1.5 Source Priority (Error processing NoMethodError)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Poetry

### Package manager version

>=1.5.0

### Language version

python 3.10

### Manifest location and content before the Dependabot update

_No response_

### dependabot.yml content

```
version: 2
registries:
  artifactory-pypi:
    type: python-index
    url: ***
    username: ${{ secrets.SECRET_USERNAME }}
    password: ${{ secrets.SECRET_PASSWORD }}
    replaces-base: false
updates:
  - package-ecosystem: "pip"
    directory: "/"
    insecure-external-code-execution: allow
    registries:
      - artifactory-pypi
    schedule:
      interval: "daily"
      time: "22:00"
    allow:
      - dependency-name: "*"
        dependency-type: "all"
```

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

**Context**
  
Poetry 1.5.0 introduces priority key to sources. After the priority key was introduced all the dependencies failed to update with the following error. 

Our `pyproject.toml` has two sources one for pypi and one for out private repo. 

```
[[tool.poetry.source]]
name = "jfrog-repo"
url = "***"
priority = "supplemental"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"
```

**What is the error**

All the packages fail to update the root of the error starts with ` Error processing (NoMethodError)` following with and attempt to strip the url in the updater. The example below is only one error for pyyaml package but all other packages yield the same error.
```
....
updater | 2023/06/14 08:16:55 ERROR <job_678219019> Error processing pyyaml (NoMethodError)
updater | 2023/06/14 08:16:55 ERROR <job_678219019> undefined method `strip' for nil:NilClass
updater | 
updater |           url = url.strip.gsub(%r{/*$}, "") + "/"
updater |                    ^^^^^^
updater | 2023/06/14 08:16:55 ERROR <job_678219019> /home/dependabot/python/lib/dependabot/python/update_checker/index_finder.rb:153:in `clean_check_and_remove_environment_variables'
updater | 2023/06/14 08:16:55 ERROR <job_678219019> /home/dependabot/python/lib/dependabot/python/update_checker/index_finder.rb:28:in `block in index_urls'
updater | 2023/06/14 08:16:55 ERROR <job_678219019> /home/dependabot/python/lib/dependabot/python/update_checker/index_finder.rb:27:in `map'
updater | 2023/06/14 08:16:55 ERROR <job_678219019> /home/dependabot/python/lib/dependabot/python/update_checker/index_finder.rb:27:in `index_urls'
updater | 2023/06/14 08:16:55 ERROR <job_678219019> /home/dependabot/python/lib/dependabot/python/update_checker/latest_version_finder.rb:216:in `index_urls'
updater | 2023/06/14 08:16:55 ERROR <job_678219019> /home/dependabot/python/lib/dependabot/python/update_checker/latest_version_finder.rb:145:in `available_versions'
updater | 2023/06/14 08:16:55 ERROR <job_678219019> /home/dependabot/python/lib/dependabot/python/update_checker/latest_version_finder.rb:52:in `fetch_latest_version'
updater | 2023/06/14 08:16:55 ERROR <job_678219019> /home/dependabot/python/lib/dependabot/python/update_checker/latest_version_finder.rb:33:in `latest_version'
updater | 2023/06/14 08:16:55 ERROR <job_678219019> /home/dependabot/python/lib/dependabot/python/update_checker.rb:241:in `fetch_latest_version'
updater | 2023/06/14 08:16:55 ERROR <job_678219019> /home/dependabot/python/lib/dependabot/python/update_checker.rb:32:in `latest_version'
updater | 2023/06/14 08:16:55 ERROR <job_678219019> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:165:in `all_versions_ignored?'
updater | 2023/06/14 08:16:55 ERROR <job_678219019> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:78:in `check_and_create_pull_request'
updater | 2023/06/14 08:16:55 ERROR <job_678219019> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:59:in `check_and_create_pr_with_error_handling'
updater | 2023/06/14 08:16:55 ERROR <job_678219019> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `block in perform'
updater | 2023/06/14 08:16:55 ERROR <job_678219019> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `each'
updater | 2023/06/14 08:16:55 ERROR <job_678219019> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `perform'
updater | 2023/06/14 08:16:55 ERROR <job_678219019> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:72:in `run'
updater | 2023/06/14 08:16:55 ERROR <job_678219019> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:38:in `perform_job'
updater | 2023/06/14 08:16:55 ERROR <job_678219019> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:52:in `run'
updater | 2023/06/14 08:16:55 ERROR <job_678219019> bin/update_files.rb:23:in `<main>'
.....
```

**What we expect**

We would have expected the dependecies to be updated without the above errors.
### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

The easiest way to reproduce this error is to create a basic poetry project and add two sources one for pypi and one for private repo. 
```
poetry source add --priority=primary PyPI
```
```
poetry source add --priority=supplemental foo ***
```
Next navigate to the Insights and observe the dependabot attempting to update the packages with the failure above.

### LINKED ISSUE #7724: Dependabot should properly handle PyPI sources that don't have a custom `url` field in `pyproject.toml`
When reading `pyproject.toml`, [Dependabot is expecting](https://github.com/dependabot/dependabot-core/blob/cde6c97863027d0ff44c408dbab6cc0738a4d542/python/lib/dependabot/python/update_checker/index_finder.rb#L120-L126) every `tool.poetry.source` entry to have a `url` field. As a result, if this field is omitted, Dependabot will fail while [attempting to process a `nil` URL](https://github.com/dependabot/dependabot-core/blob/cde6c97863027d0ff44c408dbab6cc0738a4d542/python/lib/dependabot/python/update_checker/index_finder.rb#L152-L153).

[Poetry explicitly forbids](https://github.com/python-poetry/poetry/blob/1.5/src/poetry/factory.py#L228-L231) the presence of the `url` field when the source is PyPI. Poetry will currently add PyPI as the default package source automatically if it's not specified, so it is possible to omit the entry altogether to get around the issue; however, [in a future version of Poetry this will no longer be the case](https://python-poetry.org/docs/repositories/#default-package-source):

Screenshot 2023-08-04 at 11 07 26

### PR DESCRIPTION
**Pull request by torarvid**
Fixes #7431.
Fixes #7724.

When a github user has poetry >= 1.5.0, they will be nagged by a warning to run `poetry source add pypi`, which will add the following section to the users pyproject.toml:

    [[tool.poetry.source]]
    name = "PyPI"
    priority = "primary"

This causes the problem outlined in #7431, that the index_finder will fail due to this section missing a `url`.

This commit works around this issue by explicitly adding a url for the case where the source "name" is equal to "PyPI".

### CODE REVIEW

File: python/spec/dependabot/python/update_checker/index_finder_spec.rb [hunk 1]
```diff
@@ -124,6 +124,19 @@
...
+      context "set pypi explicitly in a pyproject.toml" do
+        let(:pyproject_fixture_name) { "pypi_explicit.toml" }
+        let(:dependency_files) { [pyproject] }
+
+        it { is_expected.to eq(["https://pypi.org/pypi/"]) }
+
+        context "that is unparseable" do
+          let(:pyproject_fixture_name) { "unparseable.toml" }
+
+          it { is_expected.to eq(["https://pypi.org/simple/"]) }
```
Comment (jurre) [inline python/spec/dependabot/python/update_checker/index_finder_spec.rb:136]: I wouldn't expect the unparseable example to be able to return anything here? 🤔

Comment (torarvid) [reply python/spec/dependabot/python/update_checker/index_finder_spec.rb:136]: Whoops. This is the first time a cloned this repo, and also my first PR. It seems your keen eyes caught on to the fact that I copy-pasted the test from above 😉 

Good catch! I will remove it

**Review by jurre — APPROVED** [review]

File: python/lib/dependabot/python/update_checker/index_finder.rb [hunk 2]
```diff
@@ -120,6 +120,8 @@ def pyproject_index_urls
           sources.each do |source|
             if source["default"]
               urls[:main] = source["url"]
+            elsif source["name"] == "PyPI"
```
Comment (GriceTurrble) [inline python/lib/dependabot/python/update_checker/index_finder.rb:123]: Perhaps check for case-insensitive match (is that already the case?)?

File: python/lib/dependabot/python/update_checker/index_finder.rb [hunk 3]
```diff
@@ -120,6 +120,8 @@ def pyproject_index_urls
...
+              urls[:main] = "https://pypi.org/pypi/"
```
Comment (GriceTurrble) [inline python/lib/dependabot/python/update_checker/index_finder.rb:124]: Is this the correct index to target? Or does it need to point to `/simple`?

File: python/lib/dependabot/python/update_checker/index_finder.rb (hunk 2 above)
Comment (torarvid) [reply python/lib/dependabot/python/update_checker/index_finder.rb:123]: I just chose the string that gets added by running `poetry source add pypi` (the command that the poetry warning suggests). To me that sounds fine, but I don't feel strongly about it 🤷🏻‍♂️

File: python/lib/dependabot/python/update_checker/index_finder.rb (hunk 3 above)
Comment (torarvid) [reply python/lib/dependabot/python/update_checker/index_finder.rb:124]: I copied that url from https://github.com/dependabot/dependabot-core/blob/97fc09053fc9fe5e6a14192bffe3055cefc9db20/python/lib/dependabot/python/metadata_finder.rb#L15 and just figured that should work, but I'm not sure.

It seems poetry doesn't require the `url` to be there at all (assuming that since the change introduced by running `poetry source add pypi` doesn't add a `url`), so in some sense I'm simply trying to get dependabot to not crash here, and assuming that poetry itself will work as it does when running it locally 😄

**Comment by jurre** [comment]
cc @jeffwidman or @pavera as my go-to python people, could you take a quick look at this?

File: python/lib/dependabot/python/update_checker/index_finder.rb (hunk 3 above)
Comment (maksbotan) [reply python/lib/dependabot/python/update_checker/index_finder.rb:124]: According to poetry source, it does `https://pypi.org/simple`:

https://github.com/python-poetry/poetry/blob/01657ddeca182259e4350794a4f378241336085f/src/poetry/repositories/pypi_repository.py#L35-L47

**Comment by ekampf** [comment]
@jurre any ETA on this fix?   It's really crippling teams upgraded to latest Poetry...  should we downgrade?

File: python/lib/dependabot/python/update_checker/index_finder.rb (hunk 3 above)
Comment (torarvid) [reply python/lib/dependabot/python/update_checker/index_finder.rb]: Sounds good to me, @maksbotan 👍🏼 I changed it now

**Comment by jeffwidman** [comment]
I'll try to take a deeper look at this later this week, we're planning to invest some more time into Python and Python package manager work this quarter, as we know we're a little behind on supporting the newest versions.

File: python/lib/dependabot/python/update_checker/index_finder.rb (hunk 2 above)
Comment (GriceTurrble) [reply python/lib/dependabot/python/update_checker/index_finder.rb:123]: Double-checked on this, trying some workarounds locally.

Poetry will check itself for the source name matching `pypi`, case insensitive: both `PyPI` and `pypi` work from that primary source.

Attempting to add a `url = "https://pypi.org/simple"` field to the TOML for either of those names throws an error from Poetry: `The PyPI repository cannot be configured with a custom url.`

Therefore, a case-insensitive match would be safest. I'm not too familiar with Ruby, but my quick search turns up `casecmp`, so maybe this would help?

```suggestion
            elsif source["name"].casecmp?("PyPI")
```

File: python/lib/dependabot/python/update_checker/index_finder.rb [hunk 4]
```diff
@@ -120,6 +120,8 @@ def pyproject_index_urls
           sources.each do |source|
             if source["default"]
               urls[:main] = source["url"]
+            elsif source["name"] == "PyPI"
+              urls[:main] = "https://pypi.org/pypi/simple/"
```
Comment (GriceTurrble) [inline python/lib/dependabot/python/update_checker/index_finder.rb:124]: This URL is actually incorrect, it is `pypi.org/simple`:
```suggestion
              urls[:main] = "https://pypi.org/simple/"
```

File: python/spec/dependabot/python/update_checker/index_finder_spec.rb [hunk 5]
```diff
@@ -124,6 +124,13 @@
         end
       end
 
+      context "set pypi explicitly in a pyproject.toml" do
+        let(:pyproject_fixture_name) { "pypi_explicit.toml" }
+        let(:dependency_files) { [pyproject] }
+
+        it { is_expected.to eq(["https://pypi.org/pypi/simple/"]) }
```
Comment (GriceTurrble) [inline python/spec/dependabot/python/update_checker/index_finder_spec.rb:131]:
```suggestion
        it { is_expected.to eq(["https://pypi.org/simple/"]) }
```

File: python/lib/dependabot/python/update_checker/index_finder.rb (hunk 4 above)
Comment (deivid-rodriguez) [reply python/lib/dependabot/python/update_checker/index_finder.rb]: Updated this PR to correct that (with a slightly simpler approach).

**Comment by deivid-rodriguez** [comment]
Thanks @torarvid and @GriceTurrble for the patience.

I amended this PR with Galen's suggestions and a slightly simpler approach, and hope to be deploying it soon!

**Comment by torarvid** [comment]
Thanks, @deivid-rodriguez! I'm very happy to see this fix go in 👍🏼

**Comment by deivid-rodriguez** [comment]
Test failures here are unrelated and should be fixed by https://github.com/dependabot/dependabot-core/pull/7862.

**Review by jeffwidman — APPROVED** [review]
