### PR TITLE
Fix build.gradle files missing some updates

### LINKED ISSUE #6598: [BUG] dependabot-core does not update all dependencies in build.gradle
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gradle

### Package manager version

7.5

### Language version

java 17

### Manifest location and content before the Dependabot update

`build.gradle`
```gradle
dependencies {
	compileOnly 'org.projectlombok:lombok:1.18.24'
	annotationProcessor 'org.projectlombok:lombok:1.18.24'
}
```

### dependabot.yml content

```yml
version: 2
updates:

  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    commit-message:
      include: "scope"
    open-pull-requests-limit: 16
```

### Updated dependency

`build.gradle`
```gradle
dependencies {
	compileOnly 'org.projectlombok:lombok:1.18.26'
	annotationProcessor 'org.projectlombok:lombok:1.18.24'
}
```

#### Current behavior
Dependabot does not update the annotationProcessor dependency.
I have not tested this, but there may be other dependency types that are not updated.

#### Expected behavior
AnnotationProcessor is also updated.

### Impact
Could be a security impact if dependencies with security implications are not updated.

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

`build.gradle`
```gradle
plugins {
	id 'java'
}

repositories {
	mavenCentral()
}

dependencies {
	compileOnly 'org.projectlombok:lombok:1.18.24'
	annotationProcessor 'org.projectlombok:lombok:1.18.24'
}
```

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
When multiple configurations include the same dependency, only one would be updated.

Fixes #6598.

### CODE REVIEW

File: gradle/lib/dependabot/gradle/file_updater.rb [hunk 1]
```diff
@@ -112,26 +112,30 @@ def update_files_for_dep_set_change(buildfiles, old_req, new_req)
...
 
         raise "Expected content to change!" if updated_content == buildfile.content
 
         updated_file(file: buildfile, content: updated_content)
       end
 
-      def original_buildfile_declaration(dependency, requirement)
+      def original_buildfile_declarations(dependency, requirement)
         # This implementation is limited to declarations that appear on a
         # single line.
```
Comment (jeffwidman) [inline gradle/lib/dependabot/gradle/file_updater.rb:136]: A reminder that we'd benefit greatly from:
* https://github.com/dependabot/dependabot-core/issues/1164

**Review by jeffwidman — APPROVED** [review]
