### PR TITLE
Fix Python libraries misclassification regression due to PR 14709

### LINKED ISSUE #14740: Regression #14702
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

pypi

### Package manager version

_No response_

### Language version

_No response_

### Manifest location and content before the Dependabot update

_No response_

### dependabot.yml content

_No response_

### Updated dependency

_No response_

### What you expected to see, versus what you actually saw

Since there is no one reacting to the initial ticket #14702, I will open a new one. The issue is still very much in existence and creates tons of wrong PRs.
Image

### Native package manager behavior

_No response_

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

_No response_

### PR DESCRIPTION
**Pull request by AbhishekBhaskar**
### What are you trying to accomplish?
This PR fixes a regression where Python libraries with dynamic `description` fields in `pyproject.toml` are misclassified as applications, causing `BumpVersions` to be used instead of WidenRanges.
Fixes https://github.com/dependabot/dependabot-core/issues/14740.

After #14709, projects published on PyPI but declaring `dynamic = ["description"]` in their `pyproject.toml` (e.g. django-health-check) had `library_details["description"]` resolve to nil. When PyPI returned 200, the comparison `pypi_summary == nil` evaluated to false, incorrectly treating the package as a non-library.

### Anything you want to highlight for special attention from reviewers?
The fix adds a short-circuit: when PyPI returns 200 (confirming the package exists) but the local description is `nil` (dynamic), we return `true` immediately — the package is on PyPI, so it's a library. The description comparison only runs when both sides have a value.

### How will you know you've accomplished your goal?
Projects with `dynamic = ["description"]` in `pyproject.toml` that are published on PyPI are correctly classified as libraries, using the `WidenRanges` strategy.

### Checklist

- [x] I have run the complete test suite to ensure all tests and linters pass.
- [x] I have thoroughly tested my code changes to ensure they work as expected, including adding additional tests for new functionality.
- [x] I have written clear and descriptive commit messages.
- [x] I have provided a detailed description of the changes in the pull request, including the problem it addresses, how it fixes the problem, and any relevant details about the implementation.
- [x] I have ensured that the code is well-documented and easy to understand.

### CODE REVIEW

File: python/spec/dependabot/python/update_checker_spec.rb [hunk 1]
```diff
@@ -1978,6 +2006,20 @@
...
+          before do
+            stub_request(:get, "https://pypi.org/pypi/pendulum/json/")
+              .to_return(
+                status: 200,
+                body: fixture("pypi", "pypi_response_pendulum.json")
+              )
+          end
+
+          its([:requirement]) { is_expected.to eq(">=1.0,<2.20") }
+        end
```
[the remark this answers is not in the document]
Comment (AbhishekBhaskar) [reply python/spec/dependabot/python/update_checker_spec.rb:2021]: Fixed

File: python/spec/fixtures/pyproject_files/poetry_missing_description.toml [hunk 2]
```diff
@@ -0,0 +1,10 @@
+[tool.poetry]
+name = "pendulum"
+version = "2.0.0"
+homepage = "https://github.com/roghu/py3_projects"
+license = "MIT"
+readme = "README.md"
+authors = ["Dependabot <support@dependabot.com>"]
+
+[tool.poetry.dependencies]
+requests = "~1.0.0"
```
[the remark this answers is not in the document]
Comment (AbhishekBhaskar) [reply python/spec/fixtures/pyproject_files/poetry_missing_description.toml:10]: Fixed

File: python/lib/dependabot/python/update_checker.rb [hunk 3]
```diff
@@ -409,16 +409,19 @@ def library?
...
 
         response = Dependabot::RegistryClient.get(
           url: "https://pypi.org/pypi/#{normalised_name(T.must(library_details)['name'])}/json/"
         )
         return has_library_metadata unless response.status == 200
 
-        (JSON.parse(response.body)["info"] || {})["summary"] == T.must(library_details)["description"]
+        # If the package exists on PyPI but the local description is unavailable,
+        # trust that the package is a library.
+        local_description = T.must(library_details)["description"]
```
Comment (kbukum1) [inline python/lib/dependabot/python/update_checker.rb]: Is there a reason we don't get the following variable on top? `has_library_metadata` also seems to be using  `local_description`.nil?

```
local_description = T.must(library_details)["description"]
```

Comment (kbukum1) [reply python/lib/dependabot/python/update_checker.rb]: Also maybe you can make `T.must(library_details)` as a variable so you don't need to create variable for `T.must(library_details)` and use it in the function anywhere since it always require must?

Comment (AbhishekBhaskar) [reply python/lib/dependabot/python/update_checker.rb]: There are cases where the `description` field is dynamic and not statically defined in the `pyproject.toml` file similar to the following:
```
[project]
name = "project-name"
dynamic = [
  "version",
  "description",
]
```
This causes `library_details["description"]` to be nil and the method returns false for a package that is on PyPI, misclassifying a library as an application.

When PyPI returns 200, the package exists on PyPI — that alone is strong evidence it's a library. If the local description is nil (dynamic), we should return true instead of false. The description comparison should only reject when both descriptions exist and don't match.

Comment (AbhishekBhaskar) [reply python/lib/dependabot/python/update_checker.rb]: I've assigned `library_details` to the `local` local variable.

**Review by kbukum1 — DISMISSED** [review]

**Review by kbukum1 — APPROVED** [review]
